import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';

const W=7,H=6,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const lines=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}const uu=new Set();for(const l of lines){const cs=[];for(let i=0;i<CELLS;i++)if((l>>BigInt(i))&1n)cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);uu.add(m.toString());}}
const masks=[...uu].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const id=new Map(masks.map((m,i)=>[m.toString(),i]));
const reqSize=Uint8Array.from(masks,pc),singletonCell=new Int16Array(625).fill(-1),reqCols=new Uint8Array(625),reqSupportBase=new Uint8Array(625);const target=Array.from({length:CELLS},()=>new Int16Array(625).fill(-1)),contains=Array.from({length:CELLS},()=>new Uint8Array(625));
for(let rid=0;rid<625;rid++){const hi=new Int8Array(W);hi.fill(-1);let cols=0;for(let cell=0;cell<CELLS;cell++)if((masks[rid]>>BigInt(cell))&1n){const row=Math.trunc(cell/W),col=cell-row*W;cols|=1<<col;if(row>hi[col])hi[col]=row;if(reqSize[rid]===1)singletonCell[rid]=cell;contains[cell][rid]=1;const n=masks[rid]&~(1n<<BigInt(cell));target[cell][rid]=n===0n?-2:id.get(n.toString());}let base=0;for(let c=0;c<W;c++)if(hi[c]>=0)base+=hi[c]+1;reqCols[rid]=cols;reqSupportBase[rid]=base;}
function canon(xs){xs.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of xs){if(rid===prev)continue;prev=rid;const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}function ownMove(rs,cell){const out=[];for(const rid of rs){const n=target[cell][rid];if(n===-2)return[null,true];out.push(n>=0?n:rid);}return[canon(out),false];}function oppMove(rs,cell){const out=[];for(const rid of rs)if(!contains[cell][rid])out.push(rid);return out;}
function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}function parse(seq){let p0=0n,p1=0n;const h=new Uint8Array(W);for(let mv=0;mv<seq.length;mv++){const c=seq.charCodeAt(mv)-49,r=h[c];assert(c>=0&&c<W&&r<H);const bit=1n<<BigInt(r*W+c);if(mv&1){p1|=bit;assert(!won(p1,bit));}else{p0|=bit;assert(!won(p0,bit));}h[c]++;}return{p0,p1,h,moves:seq.length};}function compile(root,pl){const occ=root.p0|root.p1,opp=pl?root.p0:root.p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(id.get(rem.toString()));}return canon(out);}function packH(h){let v=0;for(let c=0;c<W;c++)v|=h[c]<<(3*c);return v>>>0;}function key(h,a,b){return`${packH(h)}|${a.join('.')}/${b.join('.')}`;}
function density(rs){let s=0;for(const rid of rs)s+=1<<(4-reqSize[rid]);return s;}function parity(rs,h,moves){let cls=0,future=0;for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W,d=row-h[col]+1;if(d<=1)continue;future++;if(((((W-1)*H)-moves+row+1)&1)===1)cls=1;}return{cls,future};}function playable(rs,h){const out=[];for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W;if(h[col]===row)out.push(cell);}return out;}
function deltaTurn(d,player,moves){const wantsOdd=((moves&1)===player);if(((d&1)===1)!==wantsOdd)d++;return d;}function cardMag(rs,player,moves,s){s.cardChecks++;if(!rs.length)return 0;let min=99;for(const rid of rs){s.cardReqOps++;if(reqSize[rid]<min)min=reqSize[rid];}const d=((moves&1)===player)?2*min-1:2*min,before=moves+d-1;return before>=CELLS?0:Math.trunc((CELLS+1-before)/2);}function sewbMag(rs,player,moves,h,s){s.sewbChecks++;if(!rs.length)return 0;let best=99;for(const rid of rs){s.sewbReqOps++;let fills=reqSupportBase[rid],cols=reqCols[rid];while(cols){const bit=cols&-cols,c=31-Math.clz32(bit);fills-=h[c];cols^=bit;s.sewbColOps++;}let d=Math.max(fills,((moves&1)===player)?2*reqSize[rid]-1:2*reqSize[rid]);d=deltaTurn(d,player,moves);if(d<best)best=d;}const before=moves+best-1;return before>=CELLS?0:Math.trunc((CELLS+1-before)/2);}
const colMasks=[];for(let c=0;c<W;c++){let m=0n;for(let r=0;r<H;r++)m|=1n<<BigInt(r*W+c);colMasks.push(m);}function swapMask(mask,a,b){const ma=colMasks[a],mb=colMasks[b],aa=mask&ma,bb=mask&mb,rest=mask&~(ma|mb),d=b-a;return d>0?rest|(aa<<BigInt(d))|(bb>>BigInt(d)):rest|(aa>>BigInt(-d))|(bb<<BigInt(-d));}const swapMap=Array.from({length:W},()=>Array(W).fill(null));for(let a=0;a<W;a++)for(let b=a+1;b<W;b++){const map=new Int16Array(625).fill(-1);for(let rid=0;rid<625;rid++){const x=id.get(swapMask(masks[rid],a,b).toString());if(x!==undefined)map[rid]=x;}swapMap[a][b]=map;swapMap[b][a]=map;}function has(v,t){let lo=0,hi=v.length-1;while(lo<=hi){const m=(lo+hi)>>1;if(v[m]===t)return true;if(v[m]<t)lo=m+1;else hi=m-1;}return false;}function invariant(rs,map){for(const rid of rs){const x=map[rid];if(x<0||!has(rs,x))return false;}return true;}function equiv(h,a,b,c1,c2,s){s.symmetryChecks++;if(h[c1]!==h[c2])return false;const map=swapMap[c1][c2];if(!invariant(a,map)||!invariant(b,map))return false;s.symmetryHits++;return true;}
function eventOwner(row,moves){const d=(W-1)*H-moves+row+1,pl=moves&1;return(d&1)?pl:1-pl;}function empty(h,cell){const row=Math.trunc(cell/W),col=cell-row*W;return row>=h[col];}function popBig(v){let n=0;while(v){v&=v-1n;n++;}return n;}
function a123NoWin(reqs,h,moves,s,limit=10000){s.allisChecks++;const n=reqs.length;if(!n){s.allisHits++;return true;}const targetBits=(1n<<BigInt(n))-1n,instances=[],controller=1-(moves&1);function add(cells,solved){if(solved)instances.push({cells,solved});}
 for(let col=0;col<W;col++)for(let lower=0;lower<H-1;lower++){const upper=lower+1,a=lower*W+col,b=upper*W+col;if(!empty(h,a)||!empty(h,b))continue;const pair=1n<<BigInt(a)|1n<<BigInt(b);let solved=0n;if(eventOwner(upper,moves)===controller){for(let i=0;i<n;i++)if((masks[reqs[i]]>>BigInt(b))&1n)solved|=1n<<BigInt(i);}else{for(let i=0;i<n;i++)if((masks[reqs[i]]&pair)===pair)solved|=1n<<BigInt(i);}add(pair,solved);}
 const ps=[];for(let c=0;c<W;c++)if(h[c]<H)ps.push(h[c]*W+c);for(let x=0;x<ps.length;x++)for(let y=x+1;y<ps.length;y++){const pair=1n<<BigInt(ps[x])|1n<<BigInt(ps[y]);let solved=0n;for(let i=0;i<n;i++)if((masks[reqs[i]]&pair)===pair)solved|=1n<<BigInt(i);add(pair,solved);}s.allisInstances+=instances.length;let union=0n;for(const q of instances)union|=q.solved;if(union!==targetBits)return false;s.allisRawFull++;
 const byReq=Array.from({length:n},()=>[]);for(let j=0;j<instances.length;j++){let z=instances[j].solved;for(let i=0;z;i++,z>>=1n)if(z&1n)byReq[i].push(j);}for(const a of byReq)a.sort((x,y)=>popBig(instances[y].solved)-popBig(instances[x].solved));let steps=0;function dfs(covered,used){if(++steps>limit)return false;if(covered===targetBits)return true;const missing=targetBits&~covered;let ri=0;while(((missing>>BigInt(ri))&1n)===0n)ri++;for(const j of byReq[ri]){const q=instances[j];if(q.cells&used)continue;if((q.solved&~covered)===0n)continue;if(dfs(covered|q.solved,used|q.cells))return true;}return false;}const found=dfs(0n,0n);s.allisDfsSteps+=steps;if(steps>limit)s.allisCapped++;if(found)s.allisHits++;return found;}
function applyBound(kind,p0,p1,moves,h,s,alpha,beta){let lo=-99,hi=99;if(kind==='card'){lo=-cardMag(p1,1,moves,s);hi=cardMag(p0,0,moves,s);}else if(kind==='sewb'){lo=-sewbMag(p1,1,moves,h,s);hi=sewbMag(p0,0,moves,h,s);}else throw new Error(kind);if(alpha<lo)alpha=lo;if(beta>hi)beta=hi;return{alpha,beta};}
function applyAllis(p0,p1,moves,h,s,alpha,beta){const pl=moves&1,reqs=pl?p1:p0;if(a123NoWin(reqs,h,moves,s)){if(pl===0){if(beta>0)beta=0;}else{if(alpha<0)alpha=0;}}return{alpha,beta};}
function solve(root,{bound='sewb',auto=true,allis='off'}={}){const h=root.h.slice(),p0r=compile(root,0),p1r=compile(root,1),tt=new Map();let nodes=0;const s={cardChecks:0,cardReqOps:0,sewbChecks:0,sewbReqOps:0,sewbColOps:0,allisChecks:0,allisInstances:0,allisRawFull:0,allisDfsSteps:0,allisCapped:0,allisHits:0,allisCuts:0,boundCuts:0,symmetryChecks:0,symmetryHits:0,movesSkipped:0};
 function rec(p0in,p1in,movesIn,alpha,beta){let p0=p0in,p1=p1in,moves=movesIn;const forced=[];const cleanup=()=>{for(let i=forced.length-1;i>=0;i--)h[forced[i]]--;};while(true){const pl=moves&1,mine=pl?p1:p0,other=pl?p0:p1,own=playable(mine,h);if(own.length){const v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);cleanup();return v;}const opp=[...new Set(playable(other,h))];if(opp.length>=2){const op=1-pl,v=op?-Math.trunc((CELLS-moves)/2):Math.trunc((CELLS-moves)/2);cleanup();return v;}if(opp.length!==1)break;const cell=opp[0],row=Math.trunc(cell/W),col=cell-row*W,[nm,win]=ownMove(mine,cell);assert(!win);const no=oppMove(other,cell);h[col]++;forced.push(col);moves++;if(pl){p1=nm;p0=no;}else{p0=nm;p1=no;}}
  nodes++;const a0=alpha,b0=beta,k=key(h,p0,p1);let e=tt.get(k);if(e){if(e.lo===e.up){cleanup();return e.lo;}if(e.lo>=beta){cleanup();return e.lo;}if(e.up<=alpha){cleanup();return e.up;}if(alpha<e.lo)alpha=e.lo;if(beta>e.up)beta=e.up;}if((!p0.length&&!p1.length)||moves===CELLS){tt.set(k,{lo:0,up:0});cleanup();return 0;}
  if(allis==='before'){({alpha,beta}=applyAllis(p0,p1,moves,h,s,alpha,beta));if(alpha>=beta){s.allisCuts++;cleanup();return alpha;}}
  ({alpha,beta}=applyBound(bound,p0,p1,moves,h,s,alpha,beta));if(alpha>=beta){s.boundCuts++;cleanup();return alpha;}
  if(allis==='after'){({alpha,beta}=applyAllis(p0,p1,moves,h,s,alpha,beta));if(alpha>=beta){s.allisCuts++;cleanup();return alpha;}}else if(allis!=='off'&&allis!=='before')throw new Error(allis);
  const pl=moves&1,reps=[],children=[];for(let oi=0;oi<ORDER.length;oi++){const col=ORDER[oi],row=h[col];if(row===H)continue;if(auto){let same=false;for(const rep of reps)if(equiv(h,p0,p1,col,rep,s)){same=true;break;}if(same){s.movesSkipped++;continue;}reps.push(col);}const cell=row*W+col,mine=pl?p1:p0,other=pl?p0:p1,[nm,win]=ownMove(mine,cell),no=win?null:oppMove(other,cell),e1=win?1e9:density(nm)-density(no),pf=win?{cls:1,future:99}:parity(nm,h,moves+1);children.push({col,oi,nm,no,win,e1,e2a:pf.cls,e2b:pf.future});}children.sort((a,b)=>b.e1-a.e1||b.e2a-a.e2a||b.e2b-a.e2b||a.oi-b.oi);
  let best=pl?99:-99;for(const ch of children){h[ch.col]++;let v;if(ch.win)v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);else v=pl?rec(ch.no,ch.nm,moves+1,alpha,beta):rec(ch.nm,ch.no,moves+1,alpha,beta);h[ch.col]--;if(!pl){if(v>best)best=v;if(best>alpha)alpha=best;}else{if(v<best)best=v;if(best<beta)beta=best;}if(alpha>=beta)break;}e=tt.get(k)??{lo:-99,up:99};if(best<=a0)e.up=Math.min(e.up,best);else if(best>=b0)e.lo=Math.max(e.lo,best);else e={lo:best,up:best};assert(e.lo<=e.up);tt.set(k,e);cleanup();return best;}
 const t=performance.now(),score=rec(p0r,p1r,root.moves,-99,99);return{score:Object.is(score,-0)?0:score,nodes,ms:performance.now()-t,...s};}
const frozen=[['764353221241721325116531',-2],['5563576621726752473477144213',7],['3253472274311154254412135',-9],['24763565123272565531172315',2],['544111352647536626717444135',-8],['3412761563244125763551573',-9],['11745346256273533274533652316'.replace('735','735'),-6],['463141571213634656162165252',7]];
// Preserve the canonical seventh sequence explicitly; the expression above is only to keep formatting stable.
frozen[6][0]='1174534625627233274533652316';
const configs=[];for(const bound of['card','sewb'])for(const auto of[false,true])for(const allis of['off','before','after'])configs.push({bound,auto,allis,id:`B${bound}-A${+auto}-L${allis}`});
const REPS=7,WARM=2,records=[],ledger=new Map();for(let rep=0;rep<REPS;rep++){const rotated=configs.slice(rep%configs.length).concat(configs.slice(0,rep%configs.length));for(const cfg of rotated){let nodes=0,ms=0,allisChecks=0,allisRawFull=0,allisHits=0,allisCuts=0,allisDfsSteps=0,boundCuts=0;for(const[seq,oracle]of frozen){const r=solve(parse(seq),cfg);assert.equal(r.score,oracle,`${cfg.id} ${seq}`);nodes+=r.nodes;ms+=r.ms;allisChecks+=r.allisChecks;allisRawFull+=r.allisRawFull;allisHits+=r.allisHits;allisCuts+=r.allisCuts;allisDfsSteps+=r.allisDfsSteps;boundCuts+=r.boundCuts;}const prior=ledger.get(cfg.id);if(prior===undefined)ledger.set(cfg.id,{nodes,allisHits,allisCuts,boundCuts});else{assert.equal(nodes,prior.nodes,`nodes ${cfg.id}`);assert.equal(allisHits,prior.allisHits,`hits ${cfg.id}`);assert.equal(allisCuts,prior.allisCuts,`cuts ${cfg.id}`);}records.push({rep,id:cfg.id,nodes,ms,allisChecks,allisRawFull,allisHits,allisCuts,allisDfsSteps,boundCuts});}}
function med(v){const a=[...v].sort((x,y)=>x-y),n=a.length;return n&1?a[n>>1]:(a[(n>>1)-1]+a[n>>1])/2;}function pct(a,b){return 100*(1-a/b);}const summary={};for(const cfg of configs){const rows=records.filter(r=>r.id===cfg.id),timed=rows.filter(r=>r.rep>=WARM),x=rows[0];summary[cfg.id]={...cfg,nodes:x.nodes,medianMs:med(timed.map(r=>r.ms)),allisChecks:x.allisChecks,allisRawFull:x.allisRawFull,allisHits:x.allisHits,allisCuts:x.allisCuts,allisDfsSteps:x.allisDfsSteps,boundCuts:x.boundCuts};}
const comparisons=[];for(const bound of['card','sewb'])for(const auto of[false,true]){const off=summary[`B${bound}-A${+auto}-Loff`];for(const stage of['before','after']){const on=summary[`B${bound}-A${+auto}-L${stage}`];comparisons.push({bound,auto,stage,nodePct:pct(on.nodes,off.nodes),timePct:pct(on.medianMs,off.medianMs),offNodes:off.nodes,onNodes:on.nodes,allisChecks:on.allisChecks,allisRawFull:on.allisRawFull,allisHits:on.allisHits,allisCuts:on.allisCuts,allisDfsSteps:on.allisDfsSteps});}}
const order=[];for(const bound of['card','sewb'])for(const auto of[false,true]){const before=summary[`B${bound}-A${+auto}-Lbefore`],after=summary[`B${bound}-A${+auto}-Lafter`];order.push({bound,auto,beforeVsAfterNodePct:pct(before.nodes,after.nodes),beforeVsAfterTimePct:pct(before.medianMs,after.medianMs),beforeChecks:before.allisChecks,afterChecks:after.allisChecks,beforeHits:before.allisHits,afterHits:after.allisHits});}
console.log(JSON.stringify({kind:'connect4-minimax-a123-stage-order',status:'pass',semanticBoundary:'A1-A3/U1 certificate evaluated on physical support before DEAD quotienting',pipeline:'IWIN->DTH->FBLK->FMAC->[A123 before/after exact bound]->AUTO-pre->E1E2',configCount:configs.length,reps:REPS,warmReps:WARM,comparisons,order,best:Object.values(summary).sort((a,b)=>a.nodes-b.nodes)},null,2));
