import assert from 'node:assert/strict';
import { parse } from '../../../reference/research-prototypes/2026-09-09-winspace-native/support.mjs';
import { Wsl625ResidualSolver } from '../semantic-residual-mq5/residual_solver_wsl625.mjs';

const W=7,H=6,CELLS=42,TYPES=['A1','A2','A3','A4','A5','A6','A7','A8','A9'];
const CODES={A1:{A1:'1'},A2:{A1:'1',A2:'1'},A3:{A1:'1',A2:'1',A3:'1'},A4:{A1:'1',A2:'1',A3:'1',A4:'3'},A5:{A1:'2',A2:'1',A3:'1',A4:'1&2',A5:'4'},A6:{A1:'2',A2:'1',A3:'1',A4:'1&2',A5:'4',A6:'4'},A7:{A1:'1',A2:'1',A3:'1',A4:'1',A5:'1&2',A6:'1&2',A7:'1'},A8:{A1:'1',A2:'1',A3:'1',A4:'3',A5:'2&3',A6:'1&2',A7:'1',A8:'3'},A9:{A1:'1',A2:'1',A3:'1',A4:'3',A5:'2&3',A6:'1&2',A7:'1',A8:'3',A9:'3'}};
const lines=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}function bit(cell){return 1n<<BigInt(cell);}function row(cell){return Math.trunc(cell/W);}function col(cell){const r=row(cell);return cell-r*W;}
const uu=new Set();for(const l of lines){const cs=[];for(let i=0;i<CELLS;i++)if(l&bit(i))cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=bit(cs[j]);uu.add(m.toString());}}
const masks=[...uu].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const ridByMask=new Map(masks.map((m,i)=>[m.toString(),i]));
function canon(ids){ids.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of ids){if(rid===prev)continue;prev=rid;const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}
function compile(p0,p1,pl){const occ=p0|p1,opp=pl?p0:p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(ridByMask.get(rem.toString()));}return canon(out);}function won(bits,b){for(const l of lines)if((l&b)!==0n&&(l&bits)===l)return true;return false;}
function empty(h,cell){return row(cell)>=h[col(cell)];}function playable(h,cell){return row(cell)===h[col(cell)];}function directContains(reqs,bm){let z=0n;for(let i=0;i<reqs.length;i++)if((masks[reqs[i]]&bm)===bm)z|=1n<<BigInt(i);return z;}
function componentBlocker(q,s){return (((row(s)+1)&1)===0)?bit(s):(bit(q)|bit(s));}
function liveOwnGroups(p0,p1,pl){const opp=pl?p0:p1,occ=p0|p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push({line:l,rem});}return out;}
function enumerateTailBlockers(cols,starts,limit=256){const out=[];function rec(i,m){if(out.length>=limit)return;if(i===cols.length){out.push(m);return;}const c=cols[i],start=starts[i];for(let r=start+1;r<H;r++)rec(i+1,m|bit(r*W+c));}rec(0,0n);return out;}
function frag(kind,cells){return{kind,cells,key:`${kind}:${cells.toString(16)}`};}
function desc(type,squares,fragments=[],inverses=[],special=0n){const cols=new Array(W).fill(0n),claims=[];for(let cell=0;cell<CELLS;cell++)if(squares&bit(cell))cols[col(cell)]|=bit(cell);for(const f of fragments)if(f.kind==='claim'){const cs=[];for(let i=0;i<CELLS;i++)if(f.cells&bit(i))cs.push(i);if(cs.length===2&&col(cs[0])===col(cs[1]))claims.push({col:col(cs[0]),low:Math.min(row(cs[0]),row(cs[1])),high:Math.max(row(cs[0]),row(cs[1]))});}return{type,squares,fragments,inverses,special,cols,claims};}
function codeFor(a,b){const ia=TYPES.indexOf(a),ib=TYPES.indexOf(b),hi=ia>=ib?a:b,lo=ia>=ib?b:a;return CODES[hi][lo];}function c1(a,b){return(a.squares&b.squares)===0n;}function noClaimBelowInverse(claims,inverses){for(const q of claims)for(const inv of inverses)if(q.col===inv.col&&q.high<inv.low)return false;return true;}function c2(a,b){return noClaimBelowInverse(a.claims,b.inverses)&&noClaimBelowInverse(b.claims,a.inverses);}function c3(a,b){for(let c=0;c<W;c++){const x=a.cols[c],y=b.cols[c],over=x&y;if(over!==0n){if((over&(a.special|b.special))!==0n)return false;if(x!==y)return false;}}return true;}function inverseCols(d){let m=0;for(const x of d.inverses)m|=1<<x.col;return m;}function c4(a,b){if(!c1(a,b))return false;const x=inverseCols(a),y=inverseCols(b),o=x&y;return o===0||x===y;}function compatible(a,b){for(const k of codeFor(a.type,b.type).split('&')){if(k==='1'&&!c1(a,b))return false;if(k==='2'&&!c2(a,b))return false;if(k==='3'&&!c3(a,b))return false;if(k==='4'&&!c4(a,b))return false;}return true;}
function makeRule(type,d,coverage){return coverage?{...d,type,coverage,gain:pc(coverage)}:null;}function addRule(out,rule){if(rule)out.push(rule);}function unionCoverage(reqs,bms){let z=0n;for(const bm of bms)z|=directContains(reqs,bm);return z;}
function collectRules(root,reqs){const h=root.h,by=Object.fromEntries(TYPES.map(t=>[t,[]]));
 for(let c=0;c<W;c++)for(let lo=0;lo<H-1;lo++){const up=lo+1,a=lo*W+c,b=up*W+c;if(!empty(h,a)||!empty(h,b))continue;const pair=bit(a)|bit(b);if(((up+1)&1)===0)addRule(by.A1,makeRule('A1',desc('A1',pair,[frag('claim',pair)]),directContains(reqs,bit(b))));else addRule(by.A3,makeRule('A3',desc('A3',pair,[frag('vertical',pair)]),directContains(reqs,pair)));}
 const play=[];for(let c=0;c<W;c++)if(h[c]<H)play.push(h[c]*W+c);for(let i=0;i<play.length;i++)for(let j=i+1;j<play.length;j++){const pair=bit(play[i])|bit(play[j]);addRule(by.A2,makeRule('A2',desc('A2',pair,[frag('baseinverse',pair)]),directContains(reqs,pair)));}
 for(let c1=0;c1<W;c1++)for(let c2=c1+1;c2<W;c2++)for(let l1=0;l1<H-1;l1++)for(let l2=0;l2<H-1;l2++){const u1=l1+1,u2=l2+1;if(((u1+1)&1)!==1||((u2+1)&1)!==1)continue;const a=l1*W+c1,b=u1*W+c1,d=l2*W+c2,e=u2*W+c2;if(![a,b,d,e].every(x=>empty(h,x)))continue;const p1=bit(a)|bit(b),p2=bit(d)|bit(e),cross=bit(b)|bit(e),squares=p1|p2;const cov=unionCoverage(reqs,[p1,p2,cross]);addRule(by.A5,makeRule('A5',desc('A5',squares,[frag('vertical',p1),frag('vertical',p2)],[{col:c1,low:l1,high:u1},{col:c2,low:l2,high:u2}]),cov));}
 for(let c1=0;c1<W;c1++)for(let c2=c1+1;c2<W;c2++)for(let l1=0;l1<H-2;l1++)for(let l2=0;l2<H-2;l2++){const m1=l1+1,u1=l1+2,m2=l2+1,u2=l2+2;if(((u1+1)&1)!==0||((u2+1)&1)!==0)continue;const a=l1*W+c1,b=m1*W+c1,c=u1*W+c1,d=l2*W+c2,e=m2*W+c2,f=u2*W+c2;if(![a,b,c,d,e,f].every(x=>empty(h,x)))continue;const bs=[bit(b)|bit(c),bit(e)|bit(f),bit(c)|bit(f),bit(b)|bit(e)];if(playable(h,a))bs.push(bit(a)|bit(f));if(playable(h,d))bs.push(bit(d)|bit(c));const s1=bit(a)|bit(b)|bit(c),s2=bit(d)|bit(e)|bit(f),squares=s1|s2;addRule(by.A6,makeRule('A6',desc('A6',squares,[frag('highinverse',s1),frag('highinverse',s2)],[{col:c1,low:l1,high:u1},{col:c2,low:l2,high:u2}]),unionCoverage(reqs,bs)));}
 for(let j=0;j<play.length;j++){const p2=play[j],r2=row(p2),c2=col(p2);if(r2+1>=H)continue;const q2=(r2+1)*W+c2;if(((r2+2)&1)!==0||!empty(h,q2))continue;for(let i=0;i<play.length;i++)if(i!==j)for(let z=i+1;z<play.length;z++)if(z!==j){const p1=play[i],p3=play[z],b1=bit(p1)|bit(q2),b2=bit(p2)|bit(p3),claim=bit(p2)|bit(q2),squares=bit(p1)|bit(p2)|bit(p3)|bit(q2);addRule(by.A7,makeRule('A7',desc('A7',squares,[frag('claim',claim),frag('baseinverse',b1),frag('baseinverse',b2)]),unionCoverage(reqs,[b1,b2])));}}
 for(const g of liveOwnGroups(root.p0,root.p1,1)){const empt=[];for(let cell=0;cell<CELLS;cell++)if(g.rem&bit(cell))empt.push(cell);if(!empt.length||empt.some(q=>row(q)===H-1))continue;const succ=empt.map(q=>q+W),beforeFrags=[],beforeBlockers=[];let beforeSquares=0n,succMask=0n;for(let i=0;i<empt.length;i++){const q=empt[i],s=succ[i],pair=bit(q)|bit(s),kind=(((row(s)+1)&1)===0)?'claim':'vertical';beforeFrags.push(frag(kind,pair));beforeBlockers.push(componentBlocker(q,s));beforeSquares|=pair;succMask|=bit(s);}addRule(by.A8,makeRule('A8',desc('A8',beforeSquares,beforeFrags),unionCoverage(reqs,[succMask,...beforeBlockers])));
  let ae=true;const cols=[],starts=[],claimFrags=[],bms=[];for(const q of empt){const r=row(q),c=col(q);if(((r+1)&1)!==0||r===0||!empty(h,q-W)){ae=false;break;}cols.push(c);starts.push(r);const pair=bit(q-W)|bit(q);claimFrags.push(frag('claim',pair));bms.push(bit(q));}if(ae){const uniq=[],st=[];for(let i=0;i<cols.length;i++){const j=uniq.indexOf(cols[i]);if(j<0){uniq.push(cols[i]);st.push(starts[i]);}else st[j]=Math.min(st[j],starts[i]);}bms.push(...enumerateTailBlockers(uniq,st));const squares=claimFrags.reduce((z,f)=>z|f.cells,0n);addRule(by.A4,makeRule('A4',desc('A4',squares,claimFrags),unionCoverage(reqs,bms)));}
  for(const q of empt){if(!playable(h,q))continue;for(const x of play){if(x===q||col(x)===col(q))continue;const special=bit(q)|bit(x),sblock=succMask|bit(x);addRule(by.A9,makeRule('A9',desc('A9',beforeSquares|special,[...beforeFrags,frag('special',special)],[],special),unionCoverage(reqs,[sblock,special,...beforeBlockers])));}}
 }
 const all=[];for(const type of TYPES){const dedup=new Map();for(const r of by[type]){const key=`${r.squares}:${r.coverage}`;const old=dedup.get(key);if(!old||r.gain>old.gain)dedup.set(key,r);}const arr=[...dedup.values()].sort((a,b)=>b.gain-a.gain||pc(a.squares)-pc(b.squares));if(arr.length>64)arr.length=64;all.push(...arr);}return all;}
function cover(reqs,rules,allowedTypes,limit=80000){const full=(1n<<BigInt(reqs.length))-1n,rs=rules.filter(r=>allowedTypes.has(r.type));let union=0n;for(const r of rs)union|=r.coverage;if(union!==full)return{hit:false,steps:0,selected:[]};const byReq=Array.from({length:reqs.length},()=>[]);for(let i=0;i<rs.length;i++){let z=rs[i].coverage;while(z){const b=z&-z,ri=lowBitIndex(b);byReq[ri].push(i);z^=b;}}for(const a of byReq)a.sort((i,j)=>rs[j].gain-rs[i].gain);let steps=0;const chosen=[];function dfs(cov){if(++steps>limit)return false;if(cov===full)return true;let target=-1,best=1e9;for(let ri=0;ri<reqs.length;ri++)if(((cov>>BigInt(ri))&1n)===0n){let n=0;for(const idx of byReq[ri]){let ok=true;for(const c of chosen)if(!compatible(rs[idx],rs[c])){ok=false;break;}if(ok)n++;}if(n<best){best=n;target=ri;if(n===0)break;}}if(target<0||best===0)return false;for(const idx of byReq[target]){if(chosen.includes(idx))continue;const r=rs[idx];let ok=true;for(const c of chosen)if(!compatible(r,rs[c])){ok=false;break;}if(!ok)continue;const next=cov|r.coverage;if(next===cov)continue;chosen.push(idx);if(dfs(next))return true;chosen.pop();}return false;}const hit=dfs(0n);return{hit,steps,selected:hit?chosen.map(i=>rs[i].type):[]};}
function lowBitIndex(z){const lo=Number(z&0xffffffffn);if(lo)return 31-Math.clz32(lo&-lo);let shift=32;z>>=32n;while(z){const w=Number(z&0xffffffffn);if(w)return shift+31-Math.clz32(w&-w);z>>=32n;shift+=32;}return-1;}
let seed=0xa10c0de>>>0;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;}function randomRoot(ply){let p0=0n,p1=0n,seq='';const h=new Uint8Array(W);for(let mv=0;mv<ply;mv++){const cs=[];for(let c=0;c<W;c++)if(h[c]<H){const b=bit(h[c]*W+c),mine=(mv&1)?p1:p0;if(!won(mine|b,b))cs.push(c);}if(!cs.length)return null;const c=cs[rnd()%cs.length],b=bit(h[c]*W+c);if(mv&1)p1|=b;else p0|=b;h[c]++;seq+=String(c+1);}return{p0,p1,h,ply,seq};}
function immediate(reqs,h){for(const rid of reqs)if(pc(masks[rid])===1){let cell=0,x=masks[rid];while((x&1n)===0n){x>>=1n;cell++;}if(playable(h,cell))return true;}return false;}
function exact(seq){const pos=parse(seq),s=new Wsl625ResidualSolver(19),score=s.solve(pos);return{score,nodes:s.metrics().nodes};}
const A123=new Set(['A1','A2','A3']),A1A9=new Set(TYPES),plies=[28,30,32,34,36],MAX_PER_PLY=260,TARGET_NEW=64;let scanned=0,eligible=0,a123Claims=0,allClaims=0,newClaims=0,falseClaims=0,oracleNodes=0;const byPly={},examples=[],failures=[];
outer:for(const ply of plies){const ps=byPly[ply]={scanned:0,eligible:0,a123Claims:0,allClaims:0,newClaims:0};for(let k=0;k<MAX_PER_PLY;k++){const root=randomRoot(ply);if(!root)continue;scanned++;ps.scanned++;const reqs=compile(root.p0,root.p1,0);if(!reqs.length||immediate(reqs,root.h))continue;eligible++;ps.eligible++;const rules=collectRules(root,reqs),a=cover(reqs,rules,A123),b=cover(reqs,rules,A1A9);if(a.hit){a123Claims++;ps.a123Claims++;}if(!b.hit)continue;allClaims++;ps.allClaims++;if(!a.hit){newClaims++;ps.newClaims++;}const o=exact(root.seq);oracleNodes+=o.nodes;const ok=o.score<=0;if(!ok){falseClaims++;failures.push({seq:root.seq,ply,score:o.score,reqs:reqs.length,a123:a.hit,a1a9:b.hit,a123Steps:a.steps,a1a9Steps:b.steps,selected:b.selected});if(failures.length>=8)break outer;}else if(examples.length<20)examples.push({seq:root.seq,ply,score:o.score,reqs:reqs.length,a123:a.hit,newBeyondA123:!a.hit,selected:b.selected,a1a9Steps:b.steps});if(newClaims>=TARGET_NEW&&allClaims>=TARGET_NEW+20)break outer;}}
console.log(JSON.stringify({kind:'connect4-allis-a1-a9-compatible-a10-exact',status:falseClaims===0?'pass':'falsified',authority:'sampled falsification of legacy/even-ply responder orientation only; proof combinations use conservative Allis section 7.4 table, never generic U1-extra compatibility',searchPolicy:{perTypeInstanceCap:64,coverStepLimit:80000,note:'caps/limits can miss certificates but cannot create a certificate'},scanned,eligible,a123Claims,allClaims,newClaims,falseClaims,oracleNodes,byPly,examples,failures},null,2));if(falseClaims)process.exitCode=2;
