import {Worker} from 'node:worker_threads';import{fileURLToPath}from'node:url';import{dirname,resolve}from'node:path';
const WIDTH=7,HEIGHT=6,STRIDE=7,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const SEQ=process.argv[2]??'663152175',WORKERS=Math.max(1,Number(process.argv[3]??4)|0),SPLIT=Math.max(0,Number(process.argv[4]??4)|0),REPEATS=Math.max(1,Number(process.argv[5]??3)|0),LANES=Math.max(1,Number(process.argv[6]??2)|0),SLABS=Math.max(1,Number(process.argv[7]??8)|0),SLAB_POW=Math.max(10,Number(process.argv[8]??15)|0),REGION_LOG=Math.max(0,Number(process.argv[9]??3)|0);
const workerFile=resolve(dirname(fileURLToPath(import.meta.url)),'ybwc_shareddep_regions_worker.mjs');
let bottom=0n;const bottomMasks=[],columnMasks=[],topMasks=[];for(let c=0;c<WIDTH;c++){const sh=BigInt(c*STRIDE);bottomMasks[c]=1n<<sh;topMasks[c]=1n<<BigInt(HEIGHT-1+c*STRIDE);columnMasks[c]=((1n<<6n)-1n)<<sh;bottom|=bottomMasks[c];}const board=bottom*((1n<<6n)-1n);
function wins(p,m){let r=(p<<1n)&(p<<2n)&(p<<3n);let q=(p<<7n)&(p<<14n);r|=q&(p<<21n);r|=q&(p>>7n);q=(p>>7n)&(p>>14n);r|=q&(p<<7n);r|=q&(p>>21n);q=(p<<6n)&(p<<12n);r|=q&(p<<18n);r|=q&(p>>6n);q=(p>>6n)&(p>>12n);r|=q&(p<<6n);r|=q&(p>>18n);q=(p<<8n)&(p<<16n);r|=q&(p<<24n);r|=q&(p>>8n);q=(p>>8n)&(p>>16n);r|=q&(p<<8n);r|=q&(p>>24n);return r&(board^m);}const possible=m=>(m+bottom)&board,play=(m,c)=>(m+bottomMasks[c])&columnMasks[c];
function parse(seq){let current=0n,mask=0n,moves=0;for(const ch of seq){const c=ch.charCodeAt(0)-49;if(c<0||c>=7||(mask&topMasks[c])!==0n||(wins(current,mask)&possible(mask)&columnMasks[c])!==0n)throw Error('bad sequence');const mv=play(mask,c);current^=mask;mask|=mv;moves++;}return{current,mask,moves};}function pair(x){return[Number(x&0xffffffffn)>>>0,Number((x>>32n)&0xffffffffn)>>>0];}function popBig(x){let n=0;while(x){x&=x-1n;n++;}return n;}function multiBit(x){return x!==0n&&(x&(x-1n))!==0n;}const median=xs=>{const a=[...xs].sort((a,b)=>a-b);return a[(a.length-1)>>1];};
function absOwners(s){const opp=s.current^s.mask;return(s.moves&1)===0?[s.current,opp]:[opp,s.current];}
class Pool{constructor(n,root){this.n=n;this.root=root;this.workers=[];this.idle=[];this.queue=[];this.waiters=new Map();this.id=1;this.resetMetrics();}
 resetMetrics(){for(const k of['nodes','workerSeconds','ttHits','crossHits','writeAttempts','writeSuccess','writeBusy','allocations','mapHits','noRegion','depTransitions','allocSpins','allocatedSlabs','tasks','cleanScans','reclaims','reclaimedSlabs'])this[k]=0;}
 async init(){const size=SLABS*(1<<SLAB_POW);this.keyLoSab=new SharedArrayBuffer(size*4);this.keyHiSab=new SharedArrayBuffer(size*4);this.valSab=new SharedArrayBuffer(size);this.ctrlSab=new SharedArrayBuffer(size*4);this.ownerSab=new SharedArrayBuffer(size);this.logicalMapSab=new SharedArrayBuffer((1<<21)*4);this.slabSigSab=new SharedArrayBuffer(SLABS*4);this.regionSpanSab=new SharedArrayBuffer(SLABS);this.anchorP0LoSab=new SharedArrayBuffer(SLABS*4);this.anchorP0HiSab=new SharedArrayBuffer(SLABS*4);this.anchorP1LoSab=new SharedArrayBuffer(SLABS*4);this.anchorP1HiSab=new SharedArrayBuffer(SLABS*4);this.allocLockSab=new SharedArrayBuffer(4);this.slabSig=new Int32Array(this.slabSigSab);this.regionSpan=new Uint8Array(this.regionSpanSab);this.logicalMap=new Int32Array(this.logicalMapSab);this.a0l=new Uint32Array(this.anchorP0LoSab);this.a0h=new Uint32Array(this.anchorP0HiSab);this.a1l=new Uint32Array(this.anchorP1LoSab);this.a1h=new Uint32Array(this.anchorP1HiSab);this.allocLock=new Int32Array(this.allocLockSab);
  for(let i=0;i<this.n;i++){const data={workerId:i,slabCount:SLABS,slabPow:SLAB_POW,regionSpanLog2:REGION_LOG,keyLoSab:this.keyLoSab,keyHiSab:this.keyHiSab,valSab:this.valSab,ctrlSab:this.ctrlSab,ownerSab:this.ownerSab,logicalMapSab:this.logicalMapSab,slabSigSab:this.slabSigSab,regionSpanSab:this.regionSpanSab,anchorP0LoSab:this.anchorP0LoSab,anchorP0HiSab:this.anchorP0HiSab,anchorP1LoSab:this.anchorP1LoSab,anchorP1HiSab:this.anchorP1HiSab,allocLockSab:this.allocLockSab};const w=new Worker(workerFile,{workerData:data});w.on('message',m=>this.onMessage(w,m));await new Promise((res,rej)=>{const f=m=>{if(m.type==='ready'){w.off('message',f);res();}};w.on('message',f);w.once('error',rej)});this.workers.push(w);this.idle.push(w);}const[cLo,cHi]=pair(this.root.current),[mLo,mHi]=pair(this.root.mask);await Promise.all(this.workers.map(w=>new Promise((res,rej)=>{const f=m=>{if(m.type==='warmed'){w.off('message',f);res();}};w.on('message',f);w.once('error',rej);w.postMessage({type:'warm',cLo,cHi,mLo,mHi,moves:this.root.moves,alpha:-1,beta:0,limit:30000});})));this.clear();}
 clear(){new Uint32Array(this.keyLoSab).fill(0);new Uint32Array(this.keyHiSab).fill(0);new Uint8Array(this.valSab).fill(0);new Int32Array(this.ctrlSab).fill(0);new Uint8Array(this.ownerSab).fill(0);this.logicalMap.fill(0);this.slabSig.fill(-1);this.regionSpan.fill(0);this.a0l.fill(0);this.a0h.fill(0);this.a1l.fill(0);this.a1h.fill(0);this.allocLock[0]=0;}
 onMessage(w,m){if(m.type!=='result')return;for(const k of['nodes','ttHits','crossHits','writeAttempts','writeSuccess','writeBusy','allocations','mapHits','noRegion','depTransitions','allocSpins','allocatedSlabs'])this[k]+=m[k]??0;this.workerSeconds+=m.seconds;this.tasks++;const q=this.waiters.get(m.id);if(q){this.waiters.delete(m.id);q.resolve(m);}this.idle.push(w);this.pump();}
 pump(){while(this.idle.length&&this.queue.length){const w=this.idle.pop(),m=this.queue.shift();w.postMessage(m);}}
 run(s,a,b){const id=this.id++,[cLo,cHi]=pair(s.current),[mLo,mHi]=pair(s.mask);return new Promise((resolve,reject)=>{this.waiters.set(id,{resolve,reject});this.queue.push({type:'task',id,cLo,cHi,mLo,mHi,moves:s.moves,alpha:a,beta:b});this.pump();});}
 clean(frontier){if(frontier.size===0)return;this.cleanScans++;const live=[...frontier].map(s=>{const[p0,p1]=absOwners(s),[p0l,p0h]=pair(p0),[p1l,p1h]=pair(p1);return[p0l,p0h,p1l,p1h];});let spins=0;while(Atomics.compareExchange(this.allocLock,0,0,1)!==0){if(++spins>100000)return;}try{for(let base=0;base<SLABS;base++){const sig=this.slabSig[base];if(sig<0)continue;const log=(this.regionSpan[base]|0)-1;if(log<0)continue;let impossible=true;for(const[p0l,p0h,p1l,p1h]of live){if((((this.a0l[base]&p1l)|(this.a0h[base]&p1h)|(this.a1l[base]&p0l)|(this.a1h[base]&p0h))>>>0)===0){impossible=false;break;}}if(!impossible)continue;const enc=(((log+1)<<16)|(base+1))|0;if(Atomics.load(this.logicalMap,sig)!==enc)continue;Atomics.store(this.logicalMap,sig,0);const span=1<<log;for(let j=0;j<span;j++)this.slabSig[base+j]=-1;this.regionSpan[base]=0;this.reclaims++;this.reclaimedSlabs+=span;}}finally{Atomics.store(this.allocLock,0,0);Atomics.notify(this.allocLock,0,1);}}
 async drain(){while(this.waiters.size||this.queue.length||this.idle.length!==this.workers.length)await new Promise(r=>setImmediate(r));}async close(){await Promise.all(this.workers.map(w=>w.terminate()));}}
let shellNodes=0,splitNodes=0,siblingTasks=0;const frontier=new Set();
function prep(s,alpha,beta){shellNodes++;const{current,mask,moves}=s;let cand=possible(mask),ow=wins(current^mask,mask),forced=cand&ow;if(forced!==0n){if(multiBit(forced))return{terminal:-Math.trunc((CELLS-moves)/2)};cand=forced;}cand&=~(ow>>1n);if(cand===0n)return{terminal:-Math.trunc((CELLS-moves)/2)};if(moves>=CELLS-2)return{terminal:0};const min=-Math.trunc((CELLS-2-moves)/2);if(alpha<min){alpha=min;if(alpha>=beta)return{terminal:alpha};}const max=Math.trunc((CELLS-1-moves)/2);if(beta>max){beta=max;if(alpha>=beta)return{terminal:beta};}const children=[];for(let oi=0;oi<WIDTH;oi++){const c=ORDER[oi],mv=cand&columnMasks[c];if(!mv)continue;const sc=popBig(wins(current|mv,mask)),child={current:current^mask,mask:mask|mv,moves:moves+1,sc};let at=children.length;while(at>0&&children[at-1].sc<sc)at--;children.splice(at,0,child);}return{alpha,beta,children};}
async function pneg(pool,s,alpha,beta,depth){if(depth<=0){const r=await pool.run(s,alpha,beta);frontier.delete(s);pool.clean(frontier);return r.score;}const p=prep(s,alpha,beta);if('terminal'in p){frontier.delete(s);pool.clean(frontier);return p.terminal;}alpha=p.alpha;beta=p.beta;const cs=p.children;frontier.delete(s);for(const c of cs)frontier.add(c);pool.clean(frontier);if(!cs.length)return alpha;splitNodes++;let score=-await pneg(pool,cs[0],-beta,-alpha,depth-1);if(score>=beta){for(const c of cs)frontier.delete(c);pool.clean(frontier);return score;}if(score>alpha)alpha=score;if(cs.length===1)return alpha;siblingTasks+=cs.length-1;let next=1,cutoff=null,best=alpha;const lanes=Math.min(pool.n,LANES,Math.max(1,pool.idle.length),cs.length-1);async function lane(){while(cutoff===null){const i=next++;if(i>=cs.length)return;const v=-await pneg(pool,cs[i],-beta,-best,depth-1);if(v>=beta){cutoff=v;return;}if(v>best)best=v;}}await Promise.all(Array.from({length:lanes},()=>lane()));for(const c of cs)frontier.delete(c);pool.clean(frontier);return cutoff===null?best:cutoff;}
async function solve(pool,root){let min=-Math.trunc((CELLS-root.moves)/2),max=Math.trunc((CELLS+1-root.moves)/2);while(min<max){let med=min+Math.trunc((max-min)/2);if(med<=0&&Math.trunc(min/2)<med)med=Math.trunc(min/2);else if(med>=0&&Math.trunc(max/2)>med)med=Math.trunc(max/2);frontier.clear();frontier.add(root);const s=await pneg(pool,root,med,med+1,SPLIT);await pool.drain();frontier.clear();if(s<=med)max=s;else min=s;}return min===0?0:min;}
const root=parse(SEQ),pool=new Pool(WORKERS,root);await pool.init();const runs=[];for(let r=0;r<REPEATS;r++){pool.clear();pool.resetMetrics();frontier.clear();shellNodes=splitNodes=siblingTasks=0;const t0=process.hrtime.bigint();const score=await solve(pool,root);const sec=Number(process.hrtime.bigint()-t0)/1e9,totalNodes=pool.nodes+shellNodes;runs.push({score,sec,totalNodes,nps:totalNodes/sec,ttHits:pool.ttHits,crossHits:pool.crossHits,crossPct:pool.ttHits?100*pool.crossHits/pool.ttHits:0,writeBusy:pool.writeBusy,allocations:pool.allocations,mapHits:pool.mapHits,noRegion:pool.noRegion,depTransitions:pool.depTransitions,allocSpins:pool.allocSpins,allocatedSlabs:pool.allocatedSlabs,cleanScans:pool.cleanScans,reclaims:pool.reclaims,reclaimedSlabs:pool.reclaimedSlabs,tasks:pool.tasks});}
console.log(JSON.stringify({sequence:SEQ,workers:WORKERS,split:SPLIT,lanes:LANES,slabs:SLABS,slabPow:SLAB_POW,regionSpanLog2:REGION_LOG,totalEntries:SLABS*(1<<SLAB_POW),medianSec:median(runs.map(x=>x.sec)),medianNodes:median(runs.map(x=>x.totalNodes)),medianNps:median(runs.map(x=>x.nps)),scores:[...new Set(runs.map(x=>x.score))],runs}));await pool.close();
