import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';import {parse} from 'acorn';
const campaign='C:/r/isomax-isograph-019/research/isograph/discovery/2026-09-26-isomax-core019',out=campaign+'/evidence/v2-b',source='C:/r/isomax-lazy-smoke';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');const read=p=>fs.readFileSync(campaign+'/'+p);const manifest=JSON.parse(read('packet-v2/MANIFEST.json'));const oracleBytes=read('author-only/packet-v2-source-oracle.json'),oracle=JSON.parse(oracleBytes);const a=JSON.parse(read('evidence/v2-a/reconstruction.json')),b=JSON.parse(read('evidence/v2-b/reconstruction.json'));
assert.equal(sha(read('packet-v2/NATIVE.isg')),manifest.nativeSha256);assert.equal(sha(oracleBytes),manifest.semanticOracleSha256);assert.deepEqual(a,oracle);assert.deepEqual(b,oracle);assert.deepEqual(a,b);
const revisions={main:'2ed88683ba46fc4d99790414ad99a2e409acf400',library:'04d37498607ace16dae33c79462ddfe1503c8a0d'};
function git(repo,...args){return execFileSync('git',['-C',repo,...args],{maxBuffer:32*1024*1024})}
function clean(v){if(Array.isArray(v))return v.map(clean);if(v&&typeof v==='object'){return Object.fromEntries(Object.entries(v).filter(([k])=>!['start','end','loc','range'].includes(k)).map(([k,x])=>[k,clean(x)]))}assert.notEqual(typeof v,'bigint');return v}
const nodes={},edges=[],risks=[],texts=[],actualModules=new Map();
function walk(n,name){if(!n||typeof n!=='object')return;if(n.type){nodes[n.type]=(nodes[n.type]??0)+1;
 if(['ImportDeclaration','ExportNamedDeclaration','ExportAllDeclaration'].includes(n.type)&&n.source){let spec=n.source.value;edges.push({from:name,to:spec.startsWith('.')?path.posix.normalize(path.posix.join(path.posix.dirname(name),spec)):spec,kind:spec.startsWith('.')?n.type:'external'})}
 if(n.type==='NewExpression'&&n.callee.name==='URL'&&n.arguments[0]?.value?.endsWith('.mjs'))edges.push({from:name,to:path.posix.normalize(path.posix.join(path.posix.dirname(name),n.arguments[0].value)),kind:'workerURL'});
 if(n.type==='ImportExpression'||n.type==='CallExpression'&&['eval','Function'].includes(n.callee?.name)||n.type==='NewExpression'&&n.callee?.name==='Function'||n.type==='Literal'&&(n.regex||n.bigint))risks.push({name,type:n.type});
 }for(const x of Object.values(n))if(x&&typeof x==='object')if(Array.isArray(x))x.forEach(v=>walk(v,name));else walk(x,name)}
for(const item of manifest.sourceInventory){const library=item.path.startsWith('vendor/jsminsys/'),repo=library?source+'/vendor/jsminsys':source,rev=library?revisions.library:revisions.main,rel=library?item.path.slice(16):item.path;assert.equal(item.revision,rev);const raw=git(repo,'show',rev+':'+rel);assert.equal(sha(raw),item.sha256,item.path);const text=raw.toString('utf8');const ast=parse(text,{ecmaVersion:2025,sourceType:'module',preserveParens:true});walk(ast,item.path);const normalized=clean(ast);assert.deepEqual(normalized,b.modules.find(m=>m.path===item.path)?.program,item.path);actualModules.set(item.path,normalized);texts.push({path:item.path,revision:rev,sha256:sha(raw),syntaxEqual:true});}
assert.equal(actualModules.size,26);assert.deepEqual(nodes,manifest.counts);assert.equal(Object.values(nodes).reduce((a,b)=>a+b,0),manifest.totalSyntaxNodes);
const edgeKey=e=>JSON.stringify(e);assert.deepEqual(edges.map(edgeKey).sort(),b.imports.map(edgeKey).sort());const reachable=new Set(),todo=[...b.entries];while(todo.length){const p=todo.pop();if(reachable.has(p))continue;assert.ok(actualModules.has(p),p);reachable.add(p);for(const e of edges)if(e.from===p&&e.kind!=='external')todo.push(e.to)}assert.equal(reachable.size,actualModules.size);assert.equal(risks.length,0);
const modelPaths=['packet-v2/PROFILE.md','render.mjs','semantic-bridge.mjs','controls.mjs','PLAN.md','score-reconstruction.mjs','reconstruct-program.mjs','evidence/v2-a/REPORT.md','evidence/v2-b/REPORT.md'];
const result={status:'PASS',scope:'full static module closure, no solver execution',sourceRevisions:revisions,sourceModules:texts,sourceNodes:manifest.totalSyntaxNodes,sourceKinds:Object.keys(nodes).length,edges:edges.length,reachability:reachable.size,dynamicEvaluationRisks:risks,oracleHash:sha(oracleBytes),nativeHash:manifest.nativeSha256,decoderHashes:{a:sha(read('evidence/v2-a/reconstruction.json')),b:sha(read('evidence/v2-b/reconstruction.json'))},completeDeepEquality:true,authorityScope:'whole stipulated pinned ECMAScript and Node source model',evidenceHashes:Object.fromEntries(modelPaths.map(p=>[p,sha(read(p))]))};fs.writeFileSync(out+'/independent-source-verification.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify({...result,sourceModules:result.sourceModules.length},null,2));
