import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
function atomicWrite(filePath, content) { fs.mkdirSync(path.dirname(filePath), { recursive: true }); const temp = `${filePath}.tmp-${process.pid}`; fs.writeFileSync(temp, content, 'utf8'); fs.renameSync(temp, filePath); }
export function writeJson(filePath, value) { atomicWrite(filePath, `${JSON.stringify(value, null, 2)}\n`); }
export function readJson(filePath) { return JSON.parse(fs.readFileSync(filePath, 'utf8')); }
export function createRunId(now = new Date()) { return `${now.toISOString().replace(/[-:.]/g, '')}-${crypto.randomUUID().slice(0, 8)}`; }
export function createJournal({ spoolRoot, runId, initialState }) {
  const runDir = path.resolve(spoolRoot, 'runs', runId); fs.mkdirSync(runDir, { recursive: true }); const statePath = path.join(runDir, 'state.json'); const eventsPath = path.join(runDir, 'events.jsonl'); const state = { ...initialState, runId, status: 'running', startedAt: new Date().toISOString(), publishStatus: 'pending' }; writeJson(statePath, state);
  function appendEvent(event) { const fd = fs.openSync(eventsPath, 'a'); try { fs.writeSync(fd, `${JSON.stringify({ at: new Date().toISOString(), ...event })}\n`, null, 'utf8'); fs.fsyncSync(fd); } finally { fs.closeSync(fd); } }
  function updateState(patch) { Object.assign(state, patch); writeJson(statePath, state); }
  appendEvent({ type: 'qualification-run-started', runId }); return Object.freeze({ runId, runDir, statePath, eventsPath, state, appendEvent, updateState });
}
export function listRecoverableRuns(spoolRoot) {
  const runsRoot = path.resolve(spoolRoot, 'runs'); if (!fs.existsSync(runsRoot)) return []; const recovered = [];
  for (const name of fs.readdirSync(runsRoot)) { const runDir = path.join(runsRoot, name); const statePath = path.join(runDir, 'state.json'); if (!fs.existsSync(statePath)) continue; try { const state = readJson(statePath); const publicationWasRequested = state.config?.publish !== false; const retryablePublication = publicationWasRequested && state.status === 'finalized' && ['pending', 'failed'].includes(state.publishStatus); if (state.status === 'running' || retryablePublication) recovered.push({ runDir, statePath, state }); } catch {} }
  return recovered;
}
export function recoverInterruptedRun(entry) {
  const eventsPath = path.join(entry.runDir, 'events.jsonl');
  if (entry.state.status === 'running') {
    const fd = fs.openSync(eventsPath, 'a'); try { fs.writeSync(fd, `${JSON.stringify({ at: new Date().toISOString(), type: 'recovered-interrupted-run', reason: 'previous qualifier process did not finalize' })}\n`, null, 'utf8'); fs.fsyncSync(fd); } finally { fs.closeSync(fd); }
    const failure = { kind: 'aborted-prior-process-or-host', recoveredAt: new Date().toISOString(), explanation: 'The previous qualifier process or host stopped before finalization. Existing durable journals/logs are preserved.' }; writeJson(path.join(entry.runDir, 'failure.json'), failure);
    if (!fs.existsSync(path.join(entry.runDir, 'results.json'))) writeJson(path.join(entry.runDir, 'results.json'), { schemaVersion: 1, outcome: 'aborted-prior-process-or-host', cases: [] });
    if (!fs.existsSync(path.join(entry.runDir, 'summary.md'))) atomicWrite(path.join(entry.runDir, 'summary.md'), `# CUDA-BSFP qualification ${entry.state.runId}\n\nRecovered an interrupted run. See \`failure.json\`, \`events.jsonl\`, and case logs for the last durable state.\n`);
    entry.state.status = 'finalized'; entry.state.outcome = 'aborted-prior-process-or-host'; entry.state.finishedAt = new Date().toISOString(); entry.state.publishStatus = entry.state.publishStatus === 'published' ? 'published' : 'pending'; writeJson(entry.statePath, entry.state);
  }
  return entry;
}
export function caseDirectory(runDir, index, spec) { const id = `${String(index + 1).padStart(2, '0')}-${spec.columns}x${spec.rows}-c${spec.connect}`; const dir = path.join(runDir, 'cases', id); fs.mkdirSync(dir, { recursive: true }); return Object.freeze({ id, dir }); }
function formatBytes(bytes) { if (bytes === null || bytes === undefined) return 'n/a'; const value = typeof bytes === 'string' ? BigInt(bytes) : BigInt(bytes); const mib = Number(value / (1024n * 1024n)); return `${mib.toLocaleString('en-US')} MiB`; }
export function buildSummary({ runId, system, config, cases, outcome, publication = null }) {
  const gpu = system.gpu?.available ? `${system.gpu.name} (${system.gpu.totalMiB} MiB, driver ${system.gpu.driverVersion})` : `unavailable (${system.gpu?.error ?? 'unknown'})`;
  const lines = [`# CUDA-BSFP qualification ${runId}`, '', `- Outcome: **${outcome}**`, `- Profile: \`${config.profile}\``, `- Source revision: \`${system.source?.revision ?? 'unknown'}\``, `- Anonymous machine ID: \`${system.machineId}\``, `- GPU: ${gpu}`, `- Node: ${system.node.version}`, `- Per-case timeout: ${config.limits.caseTimeoutMs} ms`, `- Run timeout: ${config.limits.runTimeoutMs} ms`, `- VRAM policy: min(${Math.round(config.limits.vramSafeFraction * 100)}% free, free-${config.limits.vramReserveMiB} MiB, ${config.limits.vramAbsoluteMaxMiB} MiB absolute); emergency reserve ${config.limits.emergencyFreeMiB} MiB`, publication?.url ? `- Evidence PR: ${publication.url}` : '- Evidence PR: pending/not published', '', '| Case | Tier | Status | Elapsed | Estimated device bound | Result |', '| --- | --- | --- | ---: | ---: | --- |'];
  for (const result of cases) { const estimate = result.estimate?.upperBoundBytes ?? result.estimate?.denseTableBytes ?? null; const detail = result.solverResult?.outcome ?? result.reason ?? ''; lines.push(`| ${result.geometry.columns}x${result.geometry.rows} c${result.geometry.connect} | ${result.geometry.tier} | ${result.status} | ${result.durationMs ?? 0} ms | ${formatBytes(estimate)} | ${String(detail).replace(/\|/g, '\\|')} |`); }
  lines.push('', 'Timeouts, memory-safety refusals, unsupported geometries, crashes, and correctness failures are evidence outcomes; they are not silently omitted.'); return `${lines.join('\n')}\n`;
}
export function finalizeRun({ journal, system, config, cases, outcome, failure = null }) { writeJson(path.join(journal.runDir, 'system.json'), system); writeJson(path.join(journal.runDir, 'results.json'), { schemaVersion: 1, runId: journal.runId, outcome, cases }); if (failure) writeJson(path.join(journal.runDir, 'failure.json'), failure); atomicWrite(path.join(journal.runDir, 'summary.md'), buildSummary({ runId: journal.runId, system, config, cases, outcome })); journal.appendEvent({ type: 'qualification-run-finalized', outcome }); journal.updateState({ status: 'finalized', outcome, finishedAt: new Date().toISOString(), publishStatus: 'pending' }); }
function sanitizeText(text, repositoryRoot) { let sanitized = text; const replacements = new Set([os.homedir(), repositoryRoot, process.env.HOME, process.env.USERPROFILE].filter(Boolean).map((value) => path.resolve(value))); for (const value of replacements) sanitized = sanitized.split(value).join(value === path.resolve(repositoryRoot) ? '<REPO>' : '<HOME>'); sanitized = sanitized.replace(/github_pat_[A-Za-z0-9_]+/g, '<REDACTED_TOKEN>'); sanitized = sanitized.replace(/gh[pousr]_[A-Za-z0-9_]{20,}/g, '<REDACTED_TOKEN>'); sanitized = sanitized.replace(/(authorization\s*:\s*(?:bearer|token)\s+)[^\s]+/ig, '$1<REDACTED_TOKEN>'); return sanitized; }
function boundedLog(text, maximumBytes) { const bytes = Buffer.from(text, 'utf8'); if (bytes.length <= maximumBytes) return { text, sourceBytes: bytes.length, publishedBytes: bytes.length, truncated: false }; const headBytes = Math.floor(maximumBytes / 4); const tailBytes = maximumBytes - headBytes; const head = bytes.subarray(0, headBytes).toString('utf8'); const tail = bytes.subarray(bytes.length - tailBytes).toString('utf8'); const marker = `\n\n[... ${bytes.length - maximumBytes} bytes omitted by C4-0009-Q1 publication cap; local spool retains full log ...]\n\n`; const published = `${head}${marker}${tail}`; return { text: published, sourceBytes: bytes.length, publishedBytes: Buffer.byteLength(published), truncated: true }; }
function walkFiles(root, current = root, out = []) { for (const entry of fs.readdirSync(current, { withFileTypes: true })) { const absolute = path.join(current, entry.name); if (entry.isDirectory()) walkFiles(root, absolute, out); else out.push({ absolute, relative: path.relative(root, absolute).split(path.sep).join('/') }); } return out; }
export function buildPublishBundle({ runDir, repositoryRoot, maxLogBytes }) {
  const records = [];
  for (const file of walkFiles(runDir)) { if (file.relative === 'state.json' || file.relative === 'manifest.json') continue; let text = fs.readFileSync(file.absolute, 'utf8'); text = sanitizeText(text, repositoryRoot); let truncation = { sourceBytes: Buffer.byteLength(text), publishedBytes: Buffer.byteLength(text), truncated: false }; if (file.relative.endsWith('.log')) { const bounded = boundedLog(text, maxLogBytes); text = bounded.text; truncation = bounded; } records.push({ relativePath: file.relative, content: text, sha256: crypto.createHash('sha256').update(text).digest('hex'), ...truncation }); }
  records.sort((a, b) => a.relativePath.localeCompare(b.relativePath)); const manifest = { schemaVersion: 1, generatedAt: new Date().toISOString(), files: records.map(({ content, ...record }) => record) }; const manifestText = `${JSON.stringify(manifest, null, 2)}\n`; return Object.freeze([...records, Object.freeze({ relativePath: 'manifest.json', content: manifestText, sha256: crypto.createHash('sha256').update(manifestText).digest('hex'), sourceBytes: Buffer.byteLength(manifestText), publishedBytes: Buffer.byteLength(manifestText), truncated: false })]);
}
