import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';
import { parse } from '../../../reference/research-prototypes/2026-09-09-winspace-native/support.mjs';
import { Wsl625ResidualSolver } from './residual_solver_wsl625.mjs';
import { TypedWsl625ResidualSolver } from './residual_solver_wsl625_typed.mjs';

const ROOTS=[{seq:'663152175',expected:-4,label:'anchor-loss'},{seq:'41267575',expected:3,label:'anchor-win'}],REPS=7,WARM=2;
function run(Ctor,pos){const s=new Ctor(19),t=performance.now(),score=s.solve(pos),elapsedMs=performance.now()-t,m=s.metrics();return{score,elapsedMs,...m};}
function parity(a,b,label){for(const k of['score','nodes','ttHits','writeAttempts','writeSuccess','forcedTransitions','drawStops'])assert.equal(b[k],a[k],`${label} ${k}`);for(const k of['states','internHits','prepareCalls'])assert.equal(b.stateArena[k],a.stateArena[k],`${label} state.${k}`);for(const k of['sideStates','storedRequirementIds','moverTransitionCacheEntries','blockerTransitionCacheEntries','normalizeCalls','internHits'])assert.equal(b.sideArena[k],a.sideArena[k],`${label} side.${k}`);}
function med(v){const a=[...v].sort((x,y)=>x-y),n=a.length;return n&1?a[n>>1]:(a[n/2-1]+a[n/2])/2;}
const results=[];
for(const root of ROOTS){const pos=parse(root.seq),rows=[];let canonical=null;for(let rep=0;rep<REPS;rep++){const order=(rep&1)?[['typed',TypedWsl625ResidualSolver],['base',Wsl625ResidualSolver]]:[['base',Wsl625ResidualSolver],['typed',TypedWsl625ResidualSolver]];const row={rep};for(const[name,Ctor]of order){const r=run(Ctor,pos);assert.equal(r.score,root.expected);row[name]=r;}parity(row.base,row.typed,`${root.label} rep=${rep}`);if(!canonical)canonical={nodes:row.base.nodes,ttHits:row.base.ttHits,writes:row.base.writeSuccess};else{assert.equal(row.base.nodes,canonical.nodes);assert.equal(row.typed.nodes,canonical.nodes);assert.equal(row.base.ttHits,canonical.ttHits);assert.equal(row.typed.ttHits,canonical.ttHits);assert.equal(row.base.writeSuccess,canonical.writes);assert.equal(row.typed.writeSuccess,canonical.writes);}rows.push(row);}const timed=rows.filter(r=>r.rep>=WARM),base=med(timed.map(r=>r.base.elapsedMs)),typed=med(timed.map(r=>r.typed.elapsedMs)),baseSearch=med(timed.map(r=>r.base.searchMs)),typedSearch=med(timed.map(r=>r.typed.searchMs));results.push({...root,reps:REPS,warm:WARM,nodes:canonical.nodes,baseMedianMs:base,typedMedianMs:typed,speedup:base/typed,elapsedRatio:typed/base,baseSearchMedianMs:baseSearch,typedSearchMedianMs:typedSearch,searchSpeedup:baseSearch/typedSearch,typedMetrics:rows.at(-1).typed});console.error(`[typed repeated] ${root.label} nodes=${canonical.nodes} base=${base.toFixed(1)} typed=${typed.toFixed(1)} speedup=${(base/typed).toFixed(3)}x`);}
console.log(JSON.stringify({kind:'connect4-minimax-mq5-typed-exact-interning-repeated',status:'pass',policy:'7 alternating-order runs per anchor, first 2 treated as warmup; exact proof-tree parity asserted every repetition',results},null,2));
