// Source-only audit plus finite Boolean/count checks. No board solver imports.
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
import {fileURLToPath,pathToFileURL} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'../../../..');
const late='research/isograph/discovery/2026-09-29-isomax-late-xor-components/';
const core='research/isograph/discovery/2026-09-29-isomax-core020-ia-closure/';
const prior='research/isograph/discovery/2026-09-29-isomax-foundational-prior-audit/';
const sources=new Map();
function read(file){const bytes=fs.readFileSync(path.join(root,file));sources.set(file,{path:file,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length});return bytes.toString('utf8');}
function ref(file,needle,pointer){const text=read(file),at=text.indexOf(needle);assert.ok(at>=0,`${file}: ${needle}`);return {path:file,line:text.slice(0,at).split('\n').length,...(pointer?{jsonPointer:pointer}:{})};}
const lateJsonFile=late+'ISOGRAPH_FULL_DECOMPOSITION_0_1.json',lateMdFile=late+'ISOGRAPH_FULL_DECOMPOSITION_0_1.md';
const latePacket=JSON.parse(read(lateJsonFile));
const admissionFile=core+'COMPLETE_IA_ADMISSION_0_2.json',nativeFile=core+'COMPLETE_IA_CORE020_0_2.isg';
const admission=JSON.parse(read(admissionFile)),native=read(nativeFile);
const sourceAdmission=JSON.parse(read(core+'COMPLETE_SOURCE_ADMISSION_0_1.json'));
assert.equal(latePacket.implicitAssertions.length,11);assert.equal(admission.admitted.length,64);assert.equal(sourceAdmission.admitted.length,31);
function nativeBody(id){const start=native.indexOf(`(^150019 ${id}`);assert.ok(start>=0);let depth=0;for(let i=start;i<native.length;i++){if(native[i]==='(')depth++;if(native[i]===')'&&--depth===0)return native.slice(start,i+1).replace(`^150019 ${id}`,'^150019 ROOT').replace(/\s+/g,' ');}throw Error('Unclosed root');}

// Execute the existing algebra-only checker unchanged except import binding,
// import.meta URL and intercepted output. Its original evidence file is untouched.
const checkerFile=late+'verify-isograph-full-decomposition-identities.mjs';
const checker=read(checkerFile);let captured;
const executable=checker.replace("import fs from 'node:fs';",'').replace("import assert from 'node:assert/strict';",'').replaceAll('import.meta.url',JSON.stringify(pathToFileURL(path.join(root,checkerFile)).href));
vm.runInNewContext(executable,{assert,URL,fs:{writeFileSync:(_file,bytes)=>{assert.equal(captured,undefined);captured=JSON.parse(bytes);}},console:{log:()=>{}}},{timeout:10000});
assert.deepEqual(captured,JSON.parse(read(late+'ISOGRAPH_FULL_DECOMPOSITION_IDENTITY_CHECK_0_1.json')));

const equations=({sA,sB,b,c,tA,tB})=>[sA^b,b^tA,sB^c,c^tB];
const sourceSplit={sA:0,sB:1,b:0,c:1,tA:0,tB:0};
assert.deepEqual(equations(sourceSplit),[0,0,0,1]);assert.equal(sourceSplit.tA,sourceSplit.tB);assert.notEqual(sourceSplit.sA,sourceSplit.sB);
let assignmentsChecked=0,fixedSourceModels=0,guardViolations=0;
for(let bits=0;bits<64;bits++){
  const [sA,sB,b,c,tA,tB]=Array.from({length:6},(_,i)=>(bits>>i)&1),m={sA,sB,b,c,tA,tB};assignmentsChecked++;
  if(equations(m).join('')!=='0001'||sA!==sB)continue;fixedSourceModels++;if(tA===tB)guardViolations++;
}
assert.equal(guardViolations,0);assert.equal(fixedSourceModels,2);
assert.ok(nativeBody(211044).includes('(^150008 ?a0 ?a1)'));
assert.ok(nativeBody(211052).includes('(^150008 ?a0 ?a1)'));
assert.equal(nativeBody(211056),nativeBody(211057));
const compatibleFunctions=Array.from({length:4},(_,bits)=>[bits&1,(bits>>1)&1]).filter(f=>f[0]===1);
assert.equal(compatibleFunctions.length,2);
const routeMaps=[[0,1,3,2,4],[1,0,2,3,4]],routePhases=[0,1];
const permutationParity=p=>p.reduce((sum,x,i)=>sum^p.slice(i+1).reduce((n,y)=>n^(x>y?1:0),0),0);
const enlargedPairDomain=[];
for(let p=0;p<2;p++)for(let q=0;q<2;q++)enlargedPairDomain.push({pair:[p,p===q?p:q],relativeParity:permutationParity(routeMaps[p].map(x=>routeMaps[q][x])),phaseDifference:routePhases[p]^routePhases[q]});
assert.deepEqual(enlargedPairDomain.map(x=>[x.relativeParity,x.phaseDifference]),[[0,0],[0,1],[0,1],[0,0]]);
const countermodels={
  scope:'Abstract Boolean equations and observed relation samples only; no game boards, scalar games, or sealed outcomes computed',
  sourceSplit:{assignment:sourceSplit,edgeDeltas:equations(sourceSplit),projection:{sA:'S',sB:'S',b:'B',c:'C',tA:'T',tB:'T'},preserves:'Four projected edges S-B-T and S-C-T, their labels/deltas and one Boolean value per refined node; only source endpoint occurrences are split',limitation:'Countermodel to unguarded endpoint-occurrence refinement prose. It is not a countermodel to the native fixed-source guard, and does not assert a physically realizable full-game/source lift; those stronger premises are absent from the claimed universal prose.'},
  fixedSourceGuard:{assignmentsChecked,fixedSourceModels,guardViolations,guard:'sA=sB',conclusion:'tA!=tB'},
  relativeParity:{observations:[[0,1]],compatibleTotalBooleanFunctions:compatibleFunctions,conclusion:'Observed x!=y disproves y=x and every group homomorphism Z2->Z2 (which must map 0 to 0), but permits an arbitrary function with f(0)=1 and does not alone disprove y=f(x). A second same-input/different-output sample is required for arbitrary non-factorization.',premiseAudit:'SC-IA057 lists only SC-IA056, whose body is the observed parity pair. Neither that body nor the SC-IA057 scope specifies homomorphism-only candidate functions.',possibleRepair:'Explicitly admit diagonal route-pairs with relative parity 0 and phase difference 0, or restrict the assertion to inequality/direct-parity/homomorphism-law falsification. The original sole premise does not state that enlarged comparison domain.'},
  enlargedAllRoutePairs:{status:'VALID_REPAIR_IF_THIS_DOMAIN_IS_EXPLICITLY_ADMITTED',samples:enlargedPairDomain,conclusion:'Including diagonal pairs gives a genuine same-input/different-output witness, hence arbitrary relative-parity factorization fails on all route pairs. The singleton f(0)=1 countermodel does NOT fit this enlarged domain.',nativePremiseAudit:'The inspected kernel binds route A and B separately and defines the single transporter 197502 as composition of 197500 and 197501. It does not declare a general route-pair-to-relative-transporter/difference relation including diagonals; SC-IA057 sole premise is the fixed-pair SC-IA056 observation. General finite-map closure can supply the missing elementary derivation, but it is not the stated proof/body.'},
  nativeGuardsPresent:true,native211056And211057Identical:true
};

const assessments=[
  ['VALID_DEDUCTIVE_IDENTITY','Fixed integer H and h; kappa=(H-h) mod 2.','Reduction in Z/2 gives subtraction=addition. Fixed H makes the recoding invertible.','rolePhaseRecodingAndMoveGauge','Checker sets k=H XOR h before testing the same equality; this is a finite recoding sanity check, not an independent implementation check.'],
  ['VALID_DEDUCTIVE_IDENTITY','A represented residual cell has r=h_c+d, and phase stays attached to that same local role.','Reduce r=h+d modulo 2 and substitute IA-001. Local column permutation does not change vertical row.','rolePhaseRecodingAndMoveGauge','Does not identify a canonical column with a fixed physical column or establish CPC ownership/deadline semantics.'],
  ['VALID_GUARDED_INVARIANT','One legal move in the tracked column; the same absolute-row cell survives, and its role correspondence is transported across recanonicalization.','h increases by one; d decreases by one; both parities toggle, so their XOR is fixed.','rolePhaseRecodingAndMoveGauge','Does not prove quotient transition closure, survival of every residual, or identity of a canonical role index before/after movement.'],
  ['VALID_DEDUCTIVE_MONOID','Counts are nonnegative integers for a fixed descriptor, combined by multiset addition.','Zero iff both summands zero; parity adds modulo 2. The three-state quotient is closed and inherits commutative associativity/identity.','zoeAdditiveHomomorphism + zoeCommutativeMonoid','Addition only: ZOE is not a cancellative group and does not define deletion/cofactor dynamics or a WDL composition law.'],
  ['VALID_DEDUCTIVE_PROJECTION','Descriptor identities are already aligned; combine multiplicities by addition.','Oddness is the additive map to Z/2; positive support is the additive map to Boolean OR.','zoeAdditiveHomomorphism','Changing or merging descriptor identities first changes the coordinates; XOR is not established as final game-value composition.'],
  ['VALID_RELATIVE_MINIMALITY','The quotient must recover both predicates n=0 and n mod 2 on all nonnegative integers.','Each output pair is one of (0,0),(1,0),(1,1); any preserving quotient cannot merge distinct pairs. The ZOE kernel is an additive congruence.','NO_DIRECT_MINIMALITY_TEST','No proof that these are the only game-relevant observables, nor global MSS optimality among arbitrary structural encodings. On smaller restricted count domains the image may have fewer than three realized states.'],
  ['VALID_GUARDED_DEDUCTION','Fixed W,H; components partition every physical column, including isolated/full columns; equal descriptors preserve their capacity-phase checksum; standard player0-first alternating no-pass game.','XOR h_c = WH mod2 XOR XOR kappa_c; group columns by components and descriptor multiplicity; even repeated checksums cancel. Mover is rank mod2 under the start/turn contract.','groupedDescriptorRankContribution + rankParityReconstruction','Checker verifies bit algebra and widths 1..10, but does not execute component coverage, descriptor grouping/canonicalization, or mover schedule. These are necessary premises of the proof.'],
  ['VALID_SCOPE_NONCLAIM','Statement means the preceding parity derivation establishes no stronger rank information.','A theorem recovering rank mod2 alone says nothing about exact rank or mod3 recovery from the full descriptor.','NO_DIRECT_TEST_EXPECTED','Do not reinterpret this as a proof that the full signature can never recover exact rank, mod3 or schedule on a restricted domain.'],
  ['VALID_DEDUCTIVE_IDENTITY','Valid ZOE Boolean coordinates satisfy O=>P.','At O=0 both sides zero; at O=1 valid states have P=1, so PO=O.','binaryZoeAbsorption','This reduces coordinate monomials, not scalar behavior or a native game-theory interaction order.'],
  ['VALID_REPRESENTATION_WARNING','GF(2) ANF over chosen P/O encoding is distinguished from a chosen native operation vocabulary.','OR(a,b)=a+b+ab; a native OR of three arguments has a cubic ANF. Algebraic degree therefore is not representation-independent game interaction degree.','orToGf2AnfEncoding','Does not prove observed OOO correction is caused by OR, or remove the bounded necessity of degree>2 in the frozen feature vocabulary.'],
  ['VALID_LINEAR_ALGEBRA_SCOPE_CORRECTION','The joint target rank gain is actually 2 relative to the declared affine span, not merely two individually nonzero gains.','dim((A+span(y0,y1))/A)=2 says the two cosets are independent; it neither selects a unique basis nor identifies two unique structural syndrome terms.','NO_DIRECT_RANK_OR_TARGET_TEST','Identity checker does not replay target ranks. Joint gain 2 must remain pinned to separate bounded decoder evidence; two individual gains of 1 alone would not suffice.']
];

const headings=['### IA-01:','### IA-02:','### IA-03:','### IA-04:','### IA-05:','### IA-06:','### IA-07:','### IA-08:','## Round 4','## Round 5','## Round 6'];
const lateCoverage=latePacket.implicitAssertions.map((ia,i)=>{const [disposition,premises,derivation,mechanicalCoverage,limit]=assessments[i];return {id:ia.id,statement:ia.statement,declaredStatus:ia.status,auditDisposition:disposition,requiredPremises:premises,derivation,mechanicalCoverage,limit,refs:[ref(lateJsonFile,`"id": "${ia.id}"`,`/implicitAssertions/${i}`),ref(lateMdFile,headings[i])]};});
const affectedRefs=ids=>ids.flatMap(id=>[ref(admissionFile,`"id": "${id}"`),ref(nativeFile,`(^150019 ${211000+Number(id.slice(-3))}`)]);
const immediateDependents=ids=>admission.admitted.filter(ia=>ia.premises.some(p=>ids.includes(p))).map(ia=>({id:ia.id,premises:ia.premises}));
const findings=[
  {id:'IA-PROCESS-F01',kind:'ACTUAL_DROPPED_GUARD_IN_PROSE_AND_ADMISSION',severity:'HIGH',affectedAssertions:['SC-IA044','SC-IA052'],nativeRoots:[211044,211052],statement:'Universal target-necessity prose omits the equal-source guard present in the true native formulas.',evidence:'Native roots explicitly assume a0=a1. SC-IA021 only derives that at least one shared endpoint must split. Source-only split countermodel satisfies all four projected edge equations with target merged.',retain:'Target-only splitting is sufficient; target splitting is necessary when source phase/identity is fixed. Retain guarded native formulas and valid SC-IA021/026/037/051.',correct:'Restore fixed-source guard in human bodies, normalized bodies, admission exact_body_preserved claims and QU-SC-001. Do not infer target asymmetry for all refinements.',immediateDependents:immediateDependents(['SC-IA044','SC-IA052']),downstream:['ROUND_10_0_1.json SC-QR009 target-necessity fixed fact','QU_LEDGER_FINAL_0_6.json QU-SC-001 /fixed/11','COMPLETE_IA_ADMISSION_0_2.json exact_body_preserved on 044/052','Round16 no-support-refinement/completeness disposition'],refs:[...affectedRefs(['SC-IA021','SC-IA044','SC-IA052']),ref(core+'ROUND_10_0_1.json','"id": "SC-IA052"'),ref(core+'QU_LEDGER_FINAL_0_6.json','target separation is necessary')]},
  {id:'IA-PROCESS-F02',kind:'ACTUAL_UNSUPPORTED_NONDETERMINATION_INFERENCE',severity:'HIGH',affectedAssertions:['SC-IA057'],nativeRoots:[211057],statement:'One sample relative-parity=0, phase-difference=1 falsifies direct equality (also homomorphism-only laws), not arbitrary functional determination.',evidence:'SC-IA057 has only SC-IA056 as premise; native 211057 is literally the same body as 211056. No homomorphism-only candidate restriction appears in that premise or scope. The sample admits two total Boolean functions, both f(0)=1.',retain:'Exact observed inequality and falsification of the identity/direct-parity law or any group homomorphism Z2->Z2. No claim that relative parity is in fact globally sufficient.',correct:'Narrow prose to direct equality/homomorphism laws or explicitly enlarge domain to self-pairs and derive a same-input/different-output witness. Do not import unlisted identity-pair comparisons silently.',immediateDependents:immediateDependents(['SC-IA057']),downstream:['ROUND_12_0_2.json SC-QR011 relative-parity exclusion','QU_LEDGER_FINAL_0_6.json QU-SC-004 excluded relative-parity sufficiency','COMPLETE_IA_ADMISSION_0_2.json exact_body_preserved on 057','Round16 family-F saturation/support-refinement disposition'],refs:[...affectedRefs(['SC-IA056','SC-IA057']),ref(core+'ROUND_12_0_2.json','"id": "SC-IA057"'),ref(core+'QU_LEDGER_FINAL_0_6.json','ordinary parity of the exact relative transporter')]},
  {id:'IA-PROCESS-F03',kind:'INCOMPLETE_MECHANICAL_FIXED_POINT_EVIDENCE',severity:'MEDIUM',statement:'The complete verifier checks a recorded stopping decision; it does not compute inference-family saturation or equivalence of every prose/native assertion.',evidence:'Verifier asserts status strings and empty new_assertions/support_refinements/qu_refinements arrays; inference rule file supplies named families and prose authority, without a candidate grammar, executable enumerator or exact normalization equivalence. It also performs substantial independent-in-function finite replay, raw incidence checks, GF(2) certificates, delimiter/free-variable/root checks; those should not be dismissed.',retain:'31 source roots and 64 IA roots as a represented inventory; successful finite replay where separately recorded; operational frozen-packet stopping decision as historical reviewed evidence.',correct:'Call closure reviewed, rule/premise/normalization-relative and not logically exhaustive. F01/F02 require support/body corrections before renewing a zero-refinement stop claim. Root presence and true guarded formulas do not prove stronger prose bodies.',refs:[ref(core+'verify-complete-primitive-campaign.mjs','assert.deepEqual(round16.new_assertions,[])'),ref(core+'verify-complete-primitive-campaign.mjs','const p44=phaseCase'),ref(core+'INFERENCE_RULES_0_2.json','"stop_rule"'),ref(core+'COMPLETE_ROUND_16_FIXED_POINT_0_1.json','"completeness_claim"'),ref(core+'FIXED_POINT_REPORT_0_4_COMPLETE_PRIMITIVE.md','No further IA is licensed')]},
  {id:'IA-PROCESS-F04',kind:'INCOMPLETE_CHECKER_COVERAGE_NOT_FALSE_MATHEMATICS',severity:'LOW',statement:'Late identity PASS covers seven algebra families, not all eleven complete statements or representation premises.',evidence:'Minimality, stronger-rank nonclaim, and target-rank interpretation have no direct tests. Phase check partly checks constructed identities; rank checks do not verify all-column component coverage or physical-to-descriptor transport. The prose derivations do supply the elementary mathematics.',retain:'All eleven late statements remain valid with the recorded guards/nonclaim interpretations.',correct:'Keep proof reasoning distinct from finite implementation sanity checks; do not call this checker a native IsoGraph primitive-closure or all-IA theorem certificate.',refs:[ref(checkerFile,'const k=H^h;'),ref(checkerFile,'for(let W=1;W<=10;W++)'),ref(lateJsonFile,'"iaFixedPoint"'),ref(lateMdFile,'Reapplying the admitted implications')]}
];

const f02=findings.find(f=>f.id==='IA-PROCESS-F02');
f02.kind='UNSUPPORTED_FIXED_PAIR_INFERENCE_REPAIRABLE_BY_EXPLICIT_PAIR_DOMAIN';
f02.scopeClarification='This audit does not refute the non-factorization conclusion on all ordered route pairs. Adding (A,A) or (B,B) gives (0,0), which collides with (A,B)=(0,1). The current single-sample argument and native body omit that domain/derivation; their stronger prose is not verified by the supplied body.';
f02.refs.push(ref(core+'ISOMAX_STRUCTURAL_CONTROL_CORE020_0_2.isg','(^150024 196106 197200'),ref(core+'ISOMAX_STRUCTURAL_CONTROL_CORE020_0_2.isg','(^150010 196113 197502 ?x ?y)'));
const weakened=[
  {assertions:['SC-IA003','SC-IA004','SC-IA018','SC-IA023','SC-IA025','SC-IA035','SC-IA036'],retained:'Extensional distinctions and local fits inside the stated residual/quotient representation.',notLicensed:'Intrinsic physical/action-future distinctions or a universally meaningful repair coordinate.',laterEvidence:['AUD-IA003','AUD-IA004','AUD-IA005','AUD-IA011'],impact:'Canonical-frame sheets can collapse under literal-future identity; canonical slots require transport before physical interpretation. Local residual repair equations are not thereby false.',refs:[ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA003"'),ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA005"'),ref(prior+'IA_AUDIT_ROUND_02_0_1.json','"id": "AUD-IA011"')]},
  {assertions:['SC-IA005','SC-IA020','SC-IA029','SC-IA031','SC-IA064'],retained:'Non-exact cochain/local contradiction on the declared representation graph, with explicit quotient relation.',notLicensed:'Physical-game holonomy or a value obstruction independent of representation.',laterEvidence:['AUD-IA004','AUD-IA006','AUD-IA008','AUD-IA009'],impact:'Behavioral reconstruction can remove the witness two-sheet carrier while original graph arithmetic remains correct. Different carrier/census revisions must not be silently identified.',refs:[ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA004"'),ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA006"'),ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA008"')]},
  {assertions:['SC-IA061','SC-IA064'],retained:'Zero versus nonzero syndrome status and specific pinned-basis census observations.',notLicensed:'Number of nonzero basis syndromes as invariant obstruction dimension/magnitude.',laterEvidence:['AUD-IA002','AUD-IA012'],impact:'Basis change may alter nonzero-count while preserving exactness/non-exactness. The guarded non-determination-by-cell-bound conclusion survives.',refs:[ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA002"'),ref(prior+'IA_AUDIT_ROUND_02_0_1.json','"id": "AUD-IA012"')]},
  {assertions:['IA-LATE-003','IA-LATE-007','L2 RFG structural pipeline'],retained:'Same-cell parity identity, all-column rank checksum, and represented isolated residual feasibility.',notLicensed:'Canonical-index transport, full-game realizability, CPC deadline ownership or signature-level transition congruence.',laterEvidence:['AUD-IA007','AUD-IA011','QU-LATE-05','QU-LATE-07'],impact:'Late artifact already leaves transition closure and CPC relation open. Keep those guards rather than labeling valid identities refuted.',refs:[ref(prior+'IA_AUDIT_ROUND_01_0_1.json','"id": "AUD-IA007"'),ref(lateJsonFile,'"id": "QU-LATE-05"'),ref(lateJsonFile,'"id": "QU-LATE-07"')]}
];
for(const file of ['COMPLETE_SOURCE_CORE020_0_1.isg','ROUND_15_COMPLETE_0_1.json','COMPLETE_ROUND_16_FIXED_POINT_0_1.json','FIXED_POINT_REPORT_0_4_COMPLETE_PRIMITIVE.md','INFERENCE_RULES_0_2.json','QU_LEDGER_FINAL_0_6.json','verify-ia-closure.mjs'])read(core+file);
const result={schema:'connect4.ia_process_audit.v1',status:'SOURCE_AND_TINY_ALGEBRA_AUDIT_COMPLETE',owner:'research/semantic-quotient',sourceHashConvention:'RAW_FILE_BYTES',authorityEffect:'NONE',originalArtifactsModified:false,boardComputationsRun:false,scalarGameComputationsRun:false,sealedOutcomesAccessed:false,coverage:{lateIAsReviewed:11,lateIAsTotal:11,sourceInventoryInspected:31,coreIaInventoryInspected:64,coreSemanticAudit:'selected load-bearing bodies and dependencies, not a claim to independently prove all 64 native bodies'},conclusion:{lateIdentityMathematics:'No false late IA identity found with explicit guards.',coreErrors:'Dropped fixed-source guard in SC-IA044/052; SC-IA057 fixed-pair argument lacks the pair-domain/diagonal proof needed for arbitrary non-factorization. The latter conclusion is repairable on the explicit all-route-pairs domain, not disproved globally. Corresponding weaker/guarded native formulas remain valid.',fixedPoint:'Historical reviewed operational closure relative to frozen premises and named rule/normalization choices. No logically exhaustive closure or mechanically generated saturation certificate. Current source expressly disclaims universal logical completeness; F01/F02 expose material refinements missed by that review.'},lateCoverage,findings,weakenedFoundationalInterpretations:weakened,checks:{existingIdentityChecker:{execution:'Original source executed with output intercepted; no original file overwritten',result:captured,exactlyMatchesSavedArtifact:true},tinyCountermodels:countermodels,completeCampaignVerifier:'SOURCE_INSPECTED_ONLY; not executed because it calls board/scalar producer functions'},sources:[...sources.values()]};
fs.writeFileSync(path.join(here,'IA_PROCESS_AUDIT_0_1.json'),JSON.stringify(result,null,2)+'\n');
fs.writeFileSync(path.join(here,'IA_PROCESS_COUNTERMODELS_0_1.json'),JSON.stringify(countermodels,null,2)+'\n');
console.log(JSON.stringify({status:result.status,lateCoverage:lateCoverage.length,findings:findings.map(f=>({id:f.id,kind:f.kind})),identityChecks:captured.checks,countermodels:'PASS',sourceFiles:sources.size}));
