import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { buildPublishBundle, createJournal, listRecoverableRuns, recoverInterruptedRun } from '../report.mjs';
test('publish bundle sanitizes local paths and bounds oversized logs while preserving the tail', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bsfp-q1-report-')); const journal = createJournal({ spoolRoot: root, runId: 'test-run', initialState: { config: { publish: true } } }); const logDir = path.join(journal.runDir, 'cases', '01'); fs.mkdirSync(logDir, { recursive: true }); fs.writeFileSync(path.join(logDir, 'stderr.log'), `${root}\n${'x'.repeat(3000)}\nTRACEBACK-END\n`, 'utf8'); const bundle = buildPublishBundle({ runDir: journal.runDir, repositoryRoot: root, maxLogBytes: 1000 }); const log = bundle.find((entry) => entry.relativePath.endsWith('stderr.log')); assert.equal(log.truncated, true); assert.match(log.content, /TRACEBACK-END/); assert.doesNotMatch(log.content, new RegExp(root.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))); assert.ok(bundle.some((entry) => entry.relativePath === 'manifest.json')); });
test('interrupted runs are finalized for recovery and later publication', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bsfp-q1-recover-')); createJournal({ spoolRoot: root, runId: 'interrupted', initialState: { config: { publish: true } } }); const [entry] = listRecoverableRuns(root); const recovered = recoverInterruptedRun(entry); assert.equal(recovered.state.status, 'finalized'); assert.equal(recovered.state.outcome, 'aborted-prior-process-or-host'); assert.ok(fs.existsSync(path.join(recovered.runDir, 'failure.json'))); });
test('deliberately local interrupted runs are recoverable but are not marked publication-pending', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bsfp-q1-local-recover-')); createJournal({ spoolRoot: root, runId: 'local-only', initialState: { config: { publish: false } } }); const [entry] = listRecoverableRuns(root); assert.equal(entry.state.config.publish, false); const recovered = recoverInterruptedRun(entry); assert.equal(recovered.state.status, 'finalized'); });
