import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { buildPublishBundle, createJournal, listRecoverableRuns, recoverInterruptedRun } from '../report.mjs';
test('publish bundle sanitizes every absolute-path spelling and excludes log text from manifest', () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bsfp-q1-report-'));
  const journal = createJournal({ spoolRoot: root, runId: 'test-run', initialState: { config: { publish: true } } });
  const logDir = path.join(journal.runDir, 'cases', '01'); fs.mkdirSync(logDir, { recursive: true });
  const fileUrl = `${pathToFileURL(root).href.replace(/\/$/, '')}/private/file.mjs:1:2`;
  const foreignWindowsPath = 'C:\\Users\\private-user\\cache\\file.mjs:3:4';
  const foreignWindowsFileUrl = 'file:///C:/Users/private-user/cache/file.mjs:5:6';
  const foreignPosixPath = '/opt/private/cache/file.mjs:7:8';
  fs.writeFileSync(path.join(logDir, 'stderr.log'), `${root}\n${fileUrl}\n${foreignWindowsPath}\n${foreignWindowsFileUrl}\n${foreignPosixPath}\n${'x'.repeat(3000)}\nTRACEBACK-END\n`, 'utf8');
  const bundle = buildPublishBundle({ runDir: journal.runDir, repositoryRoot: root, maxLogBytes: 1000 });
  const log = bundle.find((entry) => entry.relativePath.endsWith('stderr.log'));
  assert.equal(log.truncated, true);
  assert.match(log.content, /TRACEBACK-END/);
  for (const privateValue of [root, fileUrl, foreignWindowsPath, foreignWindowsFileUrl, foreignPosixPath]) assert.ok(!log.content.includes(privateValue));
  const manifestEntry = bundle.find((entry) => entry.relativePath === 'manifest.json');
  assert.ok(manifestEntry);
  const manifest = JSON.parse(manifestEntry.content);
  const logRecord = manifest.files.find((entry) => entry.relativePath.endsWith('stderr.log'));
  assert.ok(logRecord);
  assert.equal(Object.hasOwn(logRecord, 'text'), false);
  assert.equal(Object.hasOwn(logRecord, 'content'), false);
  assert.ok(!manifestEntry.content.includes('TRACEBACK-END'));
  for (const privateValue of [root, fileUrl, foreignWindowsPath, foreignWindowsFileUrl, foreignPosixPath]) assert.ok(!manifestEntry.content.includes(privateValue));
});
test('interrupted runs are finalized for recovery and later publication', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bsfp-q1-recover-')); createJournal({ spoolRoot: root, runId: 'interrupted', initialState: { config: { publish: true } } }); const [entry] = listRecoverableRuns(root); const recovered = recoverInterruptedRun(entry); assert.equal(recovered.state.status, 'finalized'); assert.equal(recovered.state.outcome, 'aborted-prior-process-or-host'); assert.ok(fs.existsSync(path.join(recovered.runDir, 'failure.json'))); });
test('deliberately local interrupted runs are recoverable but are not marked publication-pending', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'bsfp-q1-local-recover-')); createJournal({ spoolRoot: root, runId: 'local-only', initialState: { config: { publish: false } } }); const [entry] = listRecoverableRuns(root); assert.equal(entry.state.config.publish, false); const recovered = recoverInterruptedRun(entry); assert.equal(recovered.state.status, 'finalized'); });
