import {Worker} from 'node:worker_threads';import{fileURLToPath}from'node:url';import{dirname,resolve}from'node:path';
const SEQ=process.argv[2]??'4126757563',POW=Number(process.argv[3]??18)|0;const WIDTH=7,HEIGHT=6,STRIDE=7;
let bottom=0n;const bm=[],cm=[],tm=[];for(let c=0;c<WIDTH;c++){const sh=BigInt(c*STRIDE);bm[c]=1n<<sh;tm[c]=1n<<BigInt(HEIGHT-1+c*STRIDE);cm[c]=((1n<<6n)-1n)<<sh;bottom|=bm[c];}const board=bottom*((1n<<6n)-1n);
function wins(p,m){let r=(p<<1n)&(p<<2n)&(p<<3n);let q=(p<<7n)&(p<<14n);r|=q&(p<<21n);r|=q&(p>>7n);q=(p>>7n)&(p>>14n);r|=q&(p<<7n);r|=q&(p>>21n);q=(p<<6n)&(p<<12n);r|=q&(p<<18n);r|=q&(p>>6n);q=(p>>6n)&(p>>12n);r|=q&(p<<6n);r|=q&(p>>18n);q=(p<<8n)&(p<<16n);r|=q&(p<<24n);r|=q&(p>>8n);q=(p>>8n)&(p>>16n);r|=q&(p<<8n);r|=q&(p>>24n);return r&(board^m);}const possible=m=>(m+bottom)&board;
function parse(seq){let current=0n,mask=0n,moves=0;for(const ch of seq){const c=ch.charCodeAt(0)-49;if(c<0||c>=7||(mask&tm[c])!==0n||(wins(current,mask)&possible(mask)&cm[c])!==0n)throw Error('bad sequence');const mv=(mask+bm[c])&cm[c];current^=mask;mask|=mv;moves++;}return{current,mask,moves};}
function pair(x){return[Number(x&0xffffffffn)>>>0,Number((x>>32n)&0xffffffffn)>>>0];}
function depSig(s){const opp=s.current^s.mask;let p0,p1;if((s.moves&1)===0){p0=s.current;p1=opp}else{p1=s.current;p0=opp}let sig=0;for(let c=0;c<7;c++){const b=BigInt(c*7),a=Number((p0>>b)&1n),d=Number((p1>>b)&1n);const code=(a|d)?(d?2:1):0;sig|=code<<(c*3);}return sig>>>0;}
const state=parse(SEQ),targetSig=depSig(state),[cLo,cHi]=pair(state.current),[mLo,mHi]=pair(state.mask);const size=1<<POW,total=size*2;
const keyLoSab=new SharedArrayBuffer(total*4),keyHiSab=new SharedArrayBuffer(total*4),valSab=new SharedArrayBuffer(total),ctrlSab=new SharedArrayBuffer(total*4),ownerSab=new SharedArrayBuffer(total);const chunkMapSab=new SharedArrayBuffer((1<<21)*4),descBaseSab=new SharedArrayBuffer(8),descMaskSab=new SharedArrayBuffer(8),descStateSab=new SharedArrayBuffer(8);const chunkMap=new Int32Array(chunkMapSab),descBase=new Uint32Array(descBaseSab),descMask=new Uint32Array(descMaskSab),descState=new Int32Array(descStateSab);descBase[0]=0;descBase[1]=size;descMask[0]=descMask[1]=size-1;descState[0]=descState[1]=1;Atomics.store(chunkMap,targetSig,2);
const wf=resolve(dirname(fileURLToPath(import.meta.url)),'ybwc_chunkmap_forward_worker.mjs');
async function make(id){const w=new Worker(wf,{workerData:{workerId:id,tablePow:POW,keyLoSab,keyHiSab,valSab,ctrlSab,ownerSab,chunkMapSab,descBaseSab,descMaskSab,descStateSab}});await new Promise((res,rej)=>{const f=m=>{if(m.type==='ready'){w.off('message',f);res();}};w.on('message',f);w.once('error',rej)});return w;}
const [a,b]=await Promise.all([make(0),make(1)]);const base={cLo,cHi,mLo,mHi,moves:state.moves,alpha:-19,beta:19};
for(const w of[a,b])await new Promise((res,rej)=>{const f=m=>{if(m.type==='warmed'){w.off('message',f);res();}};w.on('message',f);w.once('error',rej);w.postMessage({type:'warm',...base,alpha:-1,beta:0,limit:30000});});new Uint32Array(keyLoSab).fill(0);new Uint32Array(keyHiSab).fill(0);new Uint8Array(valSab).fill(0);new Int32Array(ctrlSab).fill(0);new Uint8Array(ownerSab).fill(0);chunkMap.fill(0);Atomics.store(chunkMap,targetSig,2);descState[0]=descState[1]=1;
let heldResolve;const heldP=new Promise(r=>heldResolve=r);a.on('message',m=>{if(m.type==='held')heldResolve(m);});a.postMessage({type:'hold',id:1,...base});const held=await heldP;if(held.sig!==targetSig||held.desc!==1)throw Error(`expected stale descriptor 1, got ${JSON.stringify(held)}`);
Atomics.store(descState,1,2);Atomics.store(chunkMap,targetSig,1);
const resultA=new Promise((res,rej)=>{const f=m=>{if(m.type==='result'&&m.id===1){a.off('message',f);res(m);}};a.on('message',f);a.once('error',rej);});
const resultB=new Promise((res,rej)=>{const f=m=>{if(m.type==='result'&&m.id===2){b.off('message',f);res(m);}};b.on('message',f);b.once('error',rej);});
a.postMessage({type:'release',id:1});b.postMessage({type:'task',id:2,...base});const [ra,rb]=await Promise.all([resultA,resultB]);if(ra.desc!==1||rb.desc!==0)throw Error(`descriptor mismatch A=${ra.desc} B=${rb.desc}`);if(ra.score!==rb.score)throw Error(`score mismatch ${ra.score} vs ${rb.score}`);
Atomics.store(descState,1,0);new Uint32Array(keyLoSab,size*4,size).fill(0);new Uint32Array(keyHiSab,size*4,size).fill(0);new Uint8Array(valSab,size,size).fill(0);new Int32Array(ctrlSab,size*4,size).fill(0);new Uint8Array(ownerSab,size,size).fill(0);
const rc=await new Promise((res,rej)=>{const f=m=>{if(m.type==='result'&&m.id===3){b.off('message',f);res(m);}};b.on('message',f);b.once('error',rej);b.postMessage({type:'task',id:3,...base});});if(rc.desc!==0||rc.score!==ra.score)throw Error('post-recycle survivor mismatch');
console.log(JSON.stringify({sequence:SEQ,targetSig,initialMap:2,redirectedMap:Atomics.load(chunkMap,targetSig),oldDescriptorStateAfterRecycle:Atomics.load(descState,1),staleHolder:{desc:ra.desc,score:ra.score,nodes:ra.nodes,sec:ra.seconds,mapLoads:ra.mapLoads},futureHolder:{desc:rb.desc,score:rb.score,nodes:rb.nodes,sec:rb.seconds,mapLoads:rb.mapLoads},postRecycle:{desc:rc.desc,score:rc.score,nodes:rc.nodes,sec:rc.seconds,mapLoads:rc.mapLoads},exactAgreement:ra.score===rb.score&&rb.score===rc.score}));await Promise.all([a.terminate(),b.terminate()]);
