import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';

const W=7,H=6,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const lines=[];
for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}
const uu=new Set();for(const line of lines){const cs=[];for(let i=0;i<CELLS;i++)if((line>>BigInt(i))&1n)cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);uu.add(m.toString());}}
const masks=[...uu].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const id=new Map(masks.map((m,i)=>[m.toString(),i]));
const reqSize=Uint8Array.from(masks,pc),singletonCell=new Int16Array(625).fill(-1),reqCols=new Uint8Array(625);const target=Array.from({length:CELLS},()=>new Int16Array(625).fill(-1)),contains=Array.from({length:CELLS},()=>new Uint8Array(625));
for(let rid=0;rid<625;rid++){let cols=0;for(let cell=0;cell<CELLS;cell++)if((masks[rid]>>BigInt(cell))&1n){const row=Math.trunc(cell/W),col=cell-row*W;cols|=1<<col;if(reqSize[rid]===1)singletonCell[rid]=cell;contains[cell][rid]=1;const n=masks[rid]&~(1n<<BigInt(cell));target[cell][rid]=n===0n?-2:id.get(n.toString());}reqCols[rid]=cols;}
function canon(xs){xs.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of xs){if(rid===prev)continue;prev=rid;const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}
function ownMove(rs,cell){const out=[];for(const rid of rs){const n=target[cell][rid];if(n===-2)return[null,true];out.push(n>=0?n:rid);}return[canon(out),false];}
function oppMove(rs,cell){const out=[];for(const rid of rs)if(!contains[cell][rid])out.push(rid);return out;}
function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}
function parse(seq){let p0=0n,p1=0n;const heights=new Uint8Array(W);for(let mv=0;mv<seq.length;mv++){const c=seq.charCodeAt(mv)-49,r=heights[c];assert(c>=0&&c<W&&r<H);const bit=1n<<BigInt(r*W+c);if(mv&1){p1|=bit;assert(!won(p1,bit));}else{p0|=bit;assert(!won(p0,bit));}heights[c]++;}return{p0,p1,heights,moves:seq.length};}
function compile(root,pl){const occ=root.p0|root.p1,opp=pl?root.p0:root.p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(id.get(rem.toString()));}return canon(out);}
function packH(h){let v=0;for(let c=0;c<W;c++)v|=h[c]<<(3*c);return v>>>0;}function key(h,pool,a,b){return`${packH(h)}:${pool}|${a.join('.')}/${b.join('.')}`;}
function density(rs){let s=0;for(const rid of rs)s+=1<<(4-reqSize[rid]);return s;}
function parity(rs,h,moves){let cls=0,future=0;for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W,d=row-h[col]+1;if(d<=1)continue;future++;const tp=(((W-1)*H)-moves+row+1)&1;if(tp===1)cls=1;}return{cls,future};}
function activeMask(a,b){let z=0;for(const rid of a)z|=reqCols[rid];for(const rid of b)z|=reqCols[rid];return z;}
function playableSingletons(rs,h){const out=[];for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W;if(h[col]===row)out.push(cell);}return out;}
function optimistic(rs,player,moves,stats){if(rs.length===0)return 0;const next=(moves&1)===player;let min=9;for(const rid of rs){stats.boundScans++;if(reqSize[rid]<min)min=reqSize[rid];}const delta=next?2*min-1:2*min,before=moves+delta-1;if(before>=CELLS)return 0;return Math.trunc((CELLS+1-before)/2);}

const columnMasks=[];for(let col=0;col<W;col++){let mask=0n;for(let row=0;row<H;row++)mask|=1n<<BigInt(row*W+col);columnMasks.push(mask);}function swapMask(mask,a,b){if(a===b)return mask;const ma=columnMasks[a],mb=columnMasks[b],aa=mask&ma,bb=mask&mb,rest=mask&~(ma|mb),d=b-a;return d>0?rest|(aa<<BigInt(d))|(bb>>BigInt(d)):rest|(aa>>BigInt(-d))|(bb<<BigInt(-d));}
const swapMap=Array.from({length:W},()=>Array(W).fill(null));for(let a=0;a<W;a++)for(let b=a+1;b<W;b++){const map=new Int16Array(625).fill(-1);for(let rid=0;rid<625;rid++){const x=id.get(swapMask(masks[rid],a,b).toString());if(x!==undefined)map[rid]=x;}swapMap[a][b]=map;swapMap[b][a]=map;}
function hasSorted(v,t){let lo=0,hi=v.length-1;while(lo<=hi){const m=(lo+hi)>>1;if(v[m]===t)return true;if(v[m]<t)lo=m+1;else hi=m-1;}return false;}function invariant(rs,map){for(const rid of rs){const x=map[rid];if(x<0||!hasSorted(rs,x))return false;}return true;}function equivalent(h,a,b,c1,c2,stats){stats.symmetryChecks++;if(h[c1]!==h[c2])return false;const map=swapMap[c1][c2];if(!invariant(a,map)||!invariant(b,map))return false;stats.symmetryHits++;return true;}

function solve(root,{dead=false,orbits=false,cardinality=true,exhaustion=false,order='maturityParity',neutralPlacement='last'}={}){
 const h=root.heights.slice(),p0r=compile(root,0),p1r=compile(root,1),tt=new Map();let nodes=0,forcedTransitions=0,neutralMoves=0,retiredColumns=0,retiredCapacity=0;const stats={boundScans:0,symmetryChecks:0,symmetryHits:0,movesSkipped:0,exhCuts:0,ttHits:0};
 function rec(p0in,p1in,movesIn,poolIn,alpha,beta){let p0=p0in,p1=p1in,moves=movesIn,pool=poolIn;const forced=[];const retired=[];const cleanup=()=>{for(let i=retired.length-1;i>=0;i--)h[retired[i].col]=retired[i].height;for(let i=forced.length-1;i>=0;i--)h[forced[i]]--;};
  // Exact tactical normalization: IWIN -> DTH -> FBLK -> FMAC.
  while(true){const pl=moves&1,mine=pl?p1:p0,other=pl?p0:p1,own=playableSingletons(mine,h);if(own.length){const v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);cleanup();return v;}const opp=[...new Set(playableSingletons(other,h))];if(opp.length>=2){const op=1-pl,v=op?-Math.trunc((CELLS-moves)/2):Math.trunc((CELLS-moves)/2);cleanup();return v;}if(opp.length!==1)break;const cell=opp[0],row=Math.trunc(cell/W),col=cell-row*W,[nm,win]=ownMove(mine,cell);assert(!win);const no=oppMove(other,cell);h[col]++;forced.push(col);forcedTransitions++;moves++;if(pl){p1=nm;p0=no;}else{p0=nm;p1=no;}}
  // DEAD exact form: retire columns with no remaining residual event and preserve every remaining cell in one finite neutral-tempo pool.
  if(dead){const active=activeMask(p0,p1);for(let c=0;c<W;c++)if(((active>>c)&1)===0&&h[c]<H){const cap=H-h[c];retired.push({col:c,height:h[c]});h[c]=H;pool+=cap;retiredColumns++;retiredCapacity+=cap;}}
  nodes++;const alphaOriginal=alpha,betaOriginal=beta,k=key(h,pool,p0,p1);let entry=tt.get(k);if(entry){if(entry.lo===entry.up){stats.ttHits++;const v=entry.lo;cleanup();return v;}if(entry.lo>=beta){stats.ttHits++;const v=entry.lo;cleanup();return v;}if(entry.up<=alpha){stats.ttHits++;const v=entry.up;cleanup();return v;}if(alpha<entry.lo)alpha=entry.lo;if(beta>entry.up)beta=entry.up;}
  if((p0.length===0&&p1.length===0)||(moves===CELLS)){tt.set(k,{lo:0,up:0});cleanup();return 0;}
  let lo=-99,hi=99;if(exhaustion){if(p1.length===0)lo=0;if(p0.length===0)hi=0;}if(cardinality){lo=Math.max(lo,-optimistic(p1,1,moves,stats));hi=Math.min(hi,optimistic(p0,0,moves,stats));}if(alpha<lo)alpha=lo;if(beta>hi)beta=hi;if(alpha>=beta){if(exhaustion&&(p0.length===0||p1.length===0))stats.exhCuts++;const v=alpha;cleanup();return v;}
  const pl=moves&1,reps=[],children=[];for(let oi=0;oi<ORDER.length;oi++){const col=ORDER[oi],row=h[col];if(row===H)continue;if(orbits){let eq=false;for(const rep of reps)if(equivalent(h,p0,p1,col,rep,stats)){eq=true;break;}if(eq){stats.movesSkipped++;continue;}reps.push(col);}const cell=row*W+col,mine=pl?p1:p0,other=pl?p0:p1,[nm,win]=ownMove(mine,cell),no=win?null:oppMove(other,cell),mat=win?1e9:density(nm)-density(no),pf=win?{cls:1,future:99}:parity(nm,h,moves+1);children.push({neutral:false,col,oi,nm,no,win,mat,pcls:pf.cls,pfuture:pf.future});}
  if(pool>0)children.push({neutral:true,col:-1,oi:neutralPlacement==='first'?-1:99,nm:p0,no:p1,win:false,mat:0,pcls:0,pfuture:0});
  if(order==='maturityParity')children.sort((a,b)=>b.mat-a.mat||b.pcls-a.pcls||b.pfuture-a.pfuture||a.oi-b.oi);else if(order==='parityPrimary')children.sort((a,b)=>b.pcls-a.pcls||b.pfuture-a.pfuture||b.mat-a.mat||a.oi-b.oi);else if(order==='center')children.sort((a,b)=>a.oi-b.oi);else throw new Error(order);
  let best=pl?99:-99;for(const ch of children){let v;if(ch.neutral){neutralMoves++;v=rec(p0,p1,moves+1,pool-1,alpha,beta);}else{h[ch.col]++;if(ch.win)v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);else v=pl?rec(ch.no,ch.nm,moves+1,pool,alpha,beta):rec(ch.nm,ch.no,moves+1,pool,alpha,beta);h[ch.col]--;}if(!pl){if(v>best)best=v;if(best>alpha)alpha=best;}else{if(v<best)best=v;if(best<beta)beta=best;}if(alpha>=beta)break;}
  entry=tt.get(k)??{lo:-99,up:99};if(best<=alphaOriginal)entry.up=Math.min(entry.up,best);else if(best>=betaOriginal)entry.lo=Math.max(entry.lo,best);else entry={lo:best,up:best};assert(entry.lo<=entry.up,`TT contradiction ${k}`);tt.set(k,entry);cleanup();return best;
 }
 const t=performance.now(),score=rec(p0r,p1r,root.moves,0,-99,99);return{score:Object.is(score,-0)?0:score,nodes,ms:performance.now()-t,ttSize:tt.size,forcedTransitions,neutralMoves,retiredColumns,retiredCapacity,...stats};
}

const frozen=[['764353221241721325116531',-2],['5563576621726752473477144213',7],['3253472274311154254412135',-9],['24763565123272565531172315',2],['544111352647536626717444135',-8],['3412761563244125763551573',-9],['1174534625627233274533652316',-6],['463141571213634656162165252',7]];
const configs=[];for(const dead of[false,true])for(const orbits of[false,true])for(const cardinality of[false,true])for(const exhaustion of[false,true])for(const order of['center','maturityParity','parityPrimary'])for(const neutralPlacement of(dead?['first','last']:['last']))configs.push({dead,orbits,cardinality,exhaustion,order,neutralPlacement,id:`D${+dead}A${+orbits}C${+cardinality}E${+exhaustion}-${order}-N${neutralPlacement}`});
const REPS=5,WARM=1,records=[],ledger=new Map();for(let rep=0;rep<REPS;rep++){const rotated=configs.slice(rep%configs.length).concat(configs.slice(0,rep%configs.length));for(const cfg of rotated){let nodes=0,ms=0,neutralMoves=0,retiredCapacity=0;for(const[seq,oracle]of frozen){const r=solve(parse(seq),cfg);assert.equal(r.score,oracle,`${cfg.id} ${seq}`);nodes+=r.nodes;ms+=r.ms;neutralMoves+=r.neutralMoves;retiredCapacity+=r.retiredCapacity;}const prior=ledger.get(cfg.id);if(prior===undefined)ledger.set(cfg.id,nodes);else assert.equal(nodes,prior,`nondeterministic nodes ${cfg.id}`);records.push({rep,id:cfg.id,nodes,ms,neutralMoves,retiredCapacity});}}
function med(v){const a=[...v].sort((x,y)=>x-y),n=a.length;return n&1?a[n>>1]:(a[(n>>1)-1]+a[n>>1])/2;}function pct(a,b){return 100*(1-a/b);}const summary={};for(const cfg of configs){const rows=records.filter(r=>r.id===cfg.id),timed=rows.filter(r=>r.rep>=WARM);summary[cfg.id]={...cfg,nodes:ledger.get(cfg.id),medianMs:med(timed.map(r=>r.ms)),neutralMoves:rows[0].neutralMoves,retiredCapacity:rows[0].retiredCapacity};}
const comparisons=[];for(const on of configs.filter(c=>c.dead)){const off=configs.find(c=>!c.dead&&c.orbits===on.orbits&&c.cardinality===on.cardinality&&c.exhaustion===on.exhaustion&&c.order===on.order&&c.neutralPlacement==='last');if(off){const a=summary[on.id],b=summary[off.id];comparisons.push({candidate:'DEAD',placement:on.neutralPlacement,on:on.id,off:off.id,nodePct:pct(a.nodes,b.nodes),timePct:pct(a.medianMs,b.medianMs)});}}
const placement=[];for(const first of configs.filter(c=>c.dead&&c.neutralPlacement==='first')){const last=configs.find(c=>c.dead&&c.neutralPlacement==='last'&&c.orbits===first.orbits&&c.cardinality===first.cardinality&&c.exhaustion===first.exhaustion&&c.order===first.order);const a=summary[first.id],b=summary[last.id];placement.push({context:first.id.replace('-Nfirst',''),firstVsLastNodePct:pct(a.nodes,b.nodes),firstVsLastTimePct:pct(a.medianMs,b.medianMs)});}
console.log(JSON.stringify({kind:'connect4-minimax-dead-neutral-exact-v2',status:'pass',semantic:'exact neutral-tempo pool with interval TT; dead columns retire only when no surviving requirement references any future cell; all remaining capacity is preserved',ordering:'IWIN->DTH->FBLK->FMAC, then DEAD normalization, then AUTO representatives, then E1/E2 child scoring; neutral action priority crossed first vs last',configCount:configs.length,reps:REPS,warmReps:WARM,deadEffects:{minNodePct:Math.min(...comparisons.map(x=>x.nodePct)),medianNodePct:med(comparisons.map(x=>x.nodePct)),maxNodePct:Math.max(...comparisons.map(x=>x.nodePct))},placementEffects:{minNodePct:Math.min(...placement.map(x=>x.firstVsLastNodePct)),medianNodePct:med(placement.map(x=>x.firstVsLastNodePct)),maxNodePct:Math.max(...placement.map(x=>x.firstVsLastNodePct))},best:Object.values(summary).sort((a,b)=>a.nodes-b.nodes).slice(0,16),comparisons,placement},null,2));