import assert from 'node:assert/strict';
import { parse } from '../../../reference/research-prototypes/2026-09-09-winspace-native/support.mjs';
import { Wsl625ResidualSolver } from '../semantic-residual-mq5/residual_solver_wsl625.mjs';
const W=7,H=6;
const lines=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(bits&l)===l)return true;return false;}
function residual(mine,opp){const occ=mine|opp,raw=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)raw.push(rem);}raw.sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));const out=[];let prev=-1n;outer:for(const m of raw){if(m===prev)continue;prev=m;for(const p of out)if((p&~m)===0n)continue outer;out.push(m);}return out;}
function cellOf(x){let n=0;while((x&1n)===0n){x>>=1n;n++;}return n;}function rng(s){let x=s>>>0;return()=>{x=(Math.imul(x,1664525)+1013904223)>>>0;return x;};}
function randomState(rand,target){let p0=0n,p1=0n,seq='';const h=new Uint8Array(W);for(let mv=0;mv<target;mv++){const cs=[];for(let c=0;c<W;c++)if(h[c]<H){const bit=1n<<BigInt(h[c]*W+c),mine=(mv&1)?p1:p0;if(!won(mine|bit,bit))cs.push(c);}if(!cs.length)break;const c=cs[rand()%cs.length],bit=1n<<BigInt(h[c]*W+c);if(mv&1)p1|=bit;else p0|=bit;h[c]++;seq+=String(c+1);}return{p0,p1,h,seq,moves:seq.length};}
function outcome(seq){const p=parse(seq),s=new Wsl625ResidualSolver(19),score=s.solve(p);return{score,p0:score===0?0:(score>0?((p.moves&1)?-1:1):((p.moves&1)?1:-1))};}
const seeds=[0x0ddba11,0xb10dd00d,0xdecafbad],MAX=900000,TARGET=20,rows=[];
for(const seed of seeds){const rand=rng(seed),counts={states:0,blackSingle:0,blackSingleOddRow:0,blackSingleOddNonplayable:0,bothSingleWithBlackOdd:0,bothSingleClassifiable:0},examples=[];for(let attempt=0;attempt<MAX&&examples.length<TARGET;attempt++){const ply=26+(rand()%15),st=randomState(rand,ply);if(st.moves!==ply)continue;counts.states++;const br=residual(st.p1,st.p0);if(br.length!==1||pc(br[0])!==1)continue;counts.blackSingle++;const bt=cellOf(br[0]),brw=Math.trunc(bt/W),bc=bt-brw*W;if((brw&1)!==0)continue;counts.blackSingleOddRow++;if(brw<=st.h[bc])continue;counts.blackSingleOddNonplayable++;const wr=residual(st.p0,st.p1);if(wr.length!==1||pc(wr[0])!==1)continue;counts.bothSingleWithBlackOdd++;const wt=cellOf(wr[0]),wrw=Math.trunc(wt/W),wc=wt-wrw*W;if(wrw<=st.h[wc]||wt===bt||wc===bc)continue;counts.bothSingleClassifiable++;const kind=(wrw&1)?'WE_BO_diff':'WO_BO_diff',o=outcome(st.seq);examples.push({seq:st.seq,kind,whiteTarget:wt,blackTarget:bt,whiteRow:wrw,blackRow:brw,score:o.score,p0Outcome:o.p0});}rows.push({seed:`0x${seed.toString(16)}`,counts,examples});}
console.log(JSON.stringify({kind:'connect4-zpar-black-odd-census',status:'complete',purpose:'target the two parity classes absent from the first singleton-threat differential; no proof authority',rows,totals:rows.reduce((a,r)=>{for(const[k,v]of Object.entries(r.counts))a[k]=(a[k]??0)+v;return a;},{})},null,2));