import assert from 'node:assert/strict';
const CONTROLS=[[3,3,3],[3,4,3],[4,3,3],[4,4,3],[4,4,4],[5,3,3],[5,3,4]];
function run(C,R,K){
 const N=C*R,bit=i=>1n<<BigInt(i),cell=(c,r)=>r*C+c;const pop=x=>{let n=0;while(x){x&=x-1n;n++;}return n};
 const lines=[];for(let r=0;r<R;r++)for(let c=0;c<C;c++)for(const [dc,dr] of [[1,0],[0,1],[1,1],[1,-1]]){const a=[];for(let k=0;k<K;k++){const cc=c+dc*k,rr=r+dr*k;if(cc<0||cc>=C||rr<0||rr>=R){a.length=0;break}a.push(cell(cc,rr))}if(a.length)lines.push(a)}
 const masks=lines.map(a=>a.reduce((m,x)=>m|bit(x),0n)), win=b=>masks.some(m=>(b&m)===m);
 function hs(p0,p1){const o=p0|p1,h=Array(C).fill(0);for(let c=0;c<C;c++)while(h[c]<R&&(o&bit(cell(c,h[c]))))h[c]++;return h}
 const S=[],M=new Map();function intern(p0,p1){const k=`${p0}/${p1}`;if(M.has(k))return M.get(k);const ply=pop(p0|p1);let t=win(p0)?1:win(p1)?-1:ply===N?0:null;const s={id:S.length,p0,p1,ply,side:ply&1,terminal:t,children:[]};M.set(k,s.id);S.push(s);return s.id}intern(0n,0n);for(let i=0;i<S.length;i++){const s=S[i];if(s.terminal!==null)continue;const h=hs(s.p0,s.p1);for(let c=0;c<C;c++)if(h[c]<R){const x=cell(c,h[c]),p0=s.side? s.p0:s.p0|bit(x),p1=s.side?s.p1|bit(x):s.p1;s.children.push({landing:x,child:intern(p0,p1)})}}
 const val=new Int8Array(S.length);val.fill(2);function V(id){if(val[id]!==2)return val[id];const s=S[id];if(s.terminal!==null)return val[id]=s.terminal;let v=s.side?-1:1;if(s.side){v=1;for(const e of s.children)v=Math.min(v,V(e.child))}else{v=-1;for(const e of s.children)v=Math.max(v,V(e.child))}return val[id]=v}for(let i=S.length-1;i>=0;i--)V(i);
 function residual(s,p){const own=p?s.p1:s.p0,opp=p?s.p0:s.p1,rs=[];for(let i=0;i<lines.length;i++){if(masks[i]&opp)continue;rs.push(lines[i].filter(x=>!(own&bit(x))))}rs.sort((a,b)=>a.length-b.length||a.join(',').localeCompare(b.join(',')));const out=[];for(const r of rs){const set=new Set(r);if(out.some(q=>q.every(x=>set.has(x))))continue;out.push(r)}return out}
 function playable(s){const h=hs(s.p0,s.p1),set=new Set;for(let c=0;c<C;c++)if(h[c]<R)set.add(cell(c,h[c]));return set}
 function tactical(s){if(s.terminal!==null)return {kind:'terminal',value:s.terminal};const p=playable(s),own=residual(s,s.side),opp=residual(s,1-s.side);const imm=new Set(own.filter(r=>r.length===1&&p.has(r[0])).map(r=>r[0]));if(imm.size)return{kind:'immediate',value:s.side?-1:1};const th=new Set(opp.filter(r=>r.length===1&&p.has(r[0])).map(r=>r[0]));if(th.size>=2)return{kind:'double',value:s.side?1:-1};if(!own.length&&!opp.length)return{kind:'draw',value:0};if(th.size===1)return{kind:'forced'};return{kind:'decision'}}
 const tplCache=new Map();function templates(h){const key=h.join(',');if(tplCache.has(key))return tplCache.get(key);const rem=h.map(x=>R-x),active=[...Array(C).keys()].filter(c=>rem[c]>0),out=[];
  function addVert(resp,map,c,start){for(let r=start;r+1<R;r+=2){const lo=cell(c,r),up=cell(c,r+1);resp.push(up);map.set(lo,up)}}
  function rec(left,cross,resp,map,desc){if(!left.length){out.push({cross:cross.slice(),responses:resp.slice(),map:new Map(map),desc:desc.slice()});return}const c=left[0],rest=left.slice(1);if((rem[c]&1)===0){const rr=resp.slice(),mm=new Map(map);addVert(rr,mm,c,h[c]);rec(rest,cross,rr,mm,desc.concat([['v',c]]))}for(let j=0;j<rest.length;j++){const d=rest[j];if((rem[c]&1)!==(rem[d]&1))continue;const max=Math.min(rem[c],rem[d]);for(let l=(rem[c]&1)?1:2;l<=max;l+=2){const cc=cross.slice(),rr=resp.slice(),mm=new Map(map);for(let q=0;q<l;q++){const a=cell(c,h[c]+q),b=cell(d,h[d]+q);cc.push([a,b]);mm.set(a,b);mm.set(b,a)}addVert(rr,mm,c,h[c]+l);addVert(rr,mm,d,h[d]+l);const next=rest.slice(0,j).concat(rest.slice(j+1));rec(next,cc,rr,mm,desc.concat([['c',c,d,l]]))}}}
  rec(active,[],[],new Map(),[]);tplCache.set(key,out);return out}
 function cover(rs,t){return rs.every(r=>{const set=new Set(r);if(t.responses.some(x=>set.has(x)))return true;return t.cross.some(([a,b])=>set.has(a)&&set.has(b))})}
 function channelCert(s){if(s.terminal!==null)return null;const rs=residual(s,s.side),h=hs(s.p0,s.p1);if(!rs.length)return null;for(const t of templates(h))if(cover(rs,t))return t;return null}
 function pooledCert(s){if(s.terminal!==null)return false;const h=hs(s.p0,s.p1),pool=[],resp=new Set;for(let c=0;c<C;c++){let st=h[c],m=R-h[c];if(m&1){pool.push(cell(c,h[c]));st++}for(let r=st;r+1<R;r+=2)resp.add(cell(c,r+1))}if(pool.length&1)return false;const rs=residual(s,s.side);return rs.length&&rs.every(r=>r.some(x=>resp.has(x)))}
 function policyVerify(start,t){const attacker=start.side,memo=new Map();let visited=0;function go(id){if(memo.has(id))return memo.get(id);visited++;const s=S[id];assert.equal(s.side,attacker);for(const ae of s.children){const a=S[ae.child];if(a.terminal!==null){const aw=attacker===0?1:-1;if(a.terminal===aw){memo.set(id,false);return false}continue}const target=t.map.get(ae.landing);if(target===undefined){memo.set(id,false);return false}const de=a.children.find(e=>e.landing===target);if(!de){memo.set(id,false);return false}const d=S[de.child];if(d.terminal!==null)continue;if(!go(d.id)){memo.set(id,false);return false}}memo.set(id,true);return true}return{safe:go(start.id),visited}}
 const qkey=s=>`${hs(s.p0,s.p1).join(',')};${residual(s,0).map(r=>r.join('.')).sort().join('|')};${residual(s,1).map(r=>r.join('.')).sort().join('|')}`;
 function interval(s,mode){let lo=-1,hi=1;const t=tactical(s);if(t.value!==undefined)lo=hi=t.value;const cert=mode==='channel'?channelCert(s):pooledCert(s);if(cert){if(s.side===0)hi=Math.min(hi,0);else lo=Math.max(lo,0)}return{lo,hi}}
 function strictStats(mode){let parents=0,parentsReduced=0,edges=0,mismatch=0;for(const p of S){if(p.terminal!==null||tactical(p).kind!=='decision'||p.children.length<2)continue;parents++;const cs=p.children.map(e=>({i:interval(S[e.child],mode),v:val[e.child]}));const rm=Array(cs.length).fill(false);for(let i=0;i<cs.length;i++)for(let j=0;j<cs.length;j++)if(i!==j){if(p.side===0&&cs[i].i.hi<cs[j].i.lo)rm[i]=true;if(p.side===1&&cs[i].i.lo>cs[j].i.hi)rm[i]=true}const n=rm.filter(Boolean).length;if(!n)continue;parentsReduced++;edges+=n;const keep=cs.filter((_,i)=>!rm[i]);const v=p.side===0?Math.max(...keep.map(x=>x.v)):Math.min(...keep.map(x=>x.v));if(v!==val[p.id])mismatch++}assert.equal(mismatch,0);return{parents,parentsReduced,edges,mismatch}}
 function weakStats(mode){let parents=0,parentsReduced=0,edges=0,mismatch=0;for(const p of S){if(p.terminal!==null||tactical(p).kind!=="decision"||p.children.length<2)continue;parents++;const cs=p.children.map(e=>({i:interval(S[e.child],mode),v:val[e.child]}));const rm=Array(cs.length).fill(false);for(let i=0;i<cs.length;i++)for(let j=0;j<cs.length;j++)if(i!==j){if(p.side===0&&cs[i].i.hi<=cs[j].i.lo)rm[i]=true;if(p.side===1&&cs[i].i.lo>=cs[j].i.hi)rm[i]=true}if(rm.every(Boolean)){const best=p.side===0?Math.max(...cs.map(x=>x.i.lo)):Math.min(...cs.map(x=>x.i.hi));let keep=0;for(let i=0;i<cs.length;i++){if(p.side===0&&cs[i].i.lo===best){keep=i;break}if(p.side===1&&cs[i].i.hi===best){keep=i;break}}rm[keep]=false}const n=rm.filter(Boolean).length;if(!n)continue;parentsReduced++;edges+=n;const keep=cs.filter((_,i)=>!rm[i]);const v=p.side===0?Math.max(...keep.map(x=>x.v)):Math.min(...keep.map(x=>x.v));if(v!==val[p.id])mismatch++}assert.equal(mismatch,0);return{parents,parentsReduced,edges,mismatch}}
 let pooled=0,channel=0,newc=0,missingPooled=0,mis=0,dec=0,newdec=0,policyFailures=0,policyVisited=0,maxPolicy=0;const q=new Set,dq=new Set;let maxTpl=0;for(const s of S){if(s.terminal!==null)continue;const pc=pooledCert(s),cc=channelCert(s);if(pc)pooled++;if(pc&&!cc)missingPooled++;if(cc){channel++;q.add(qkey(s));maxTpl=Math.max(maxTpl,templates(hs(s.p0,s.p1)).length);const ok=s.side===0?val[s.id]<=0:val[s.id]>=0;if(!ok)mis++;const pv=policyVerify(s,cc);policyVisited+=pv.visited;maxPolicy=Math.max(maxPolicy,pv.visited);if(!pv.safe)policyFailures++;if(tactical(s).kind==='decision'){dec++;dq.add(qkey(s))}}if(cc&&!pc){newc++;if(tactical(s).kind==='decision')newdec++}}
 assert.equal(mis,0);assert.equal(policyFailures,0);assert.equal(missingPooled,0);const pooledChoice=strictStats('pooled'),channelChoice=strictStats('channel'),pooledWeak=weakStats('pooled'),channelWeak=weakStats('channel');return{domain:[C,R,K],states:S.length,pooled,channel,newc,missingPooled,decision:dec,newdec,q:q.size,dq:dq.size,maxTpl,supportTemplates:tplCache.size,policyFailures,policyVisited,maxPolicy,pooledChoice,channelChoice,incrementalStrictEdges:channelChoice.edges-pooledChoice.edges,pooledWeak,channelWeak,incrementalWeakEdges:channelWeak.edges-pooledWeak.edges};
}
const arg=process.argv[2];const controls=arg===undefined?CONTROLS:[CONTROLS[Number(arg)]];const out=controls.map(x=>run(...x));console.log(JSON.stringify(out,null,2));
