import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';

const W=7,H=6,CELLS=42;
const lines=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}
const uu=new Set();for(const l of lines){const cs=[];for(let i=0;i<CELLS;i++)if((l>>BigInt(i))&1n)cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);uu.add(m.toString());}}
const masks=[...uu].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const id=new Map(masks.map((m,i)=>[m.toString(),i]));
const upBits=new Array(625);for(let b=0;b<625;b++){let z=0n,bm=masks[b];for(let r=0;r<625;r++)if((bm&~masks[r])===0n)z|=1n<<BigInt(r);upBits[b]=z;}
const singletonId=new Int16Array(CELLS),pairId=new Int16Array(CELLS*CELLS);pairId.fill(-1);const pairMask=new Array(CELLS*CELLS);for(let a=0;a<CELLS;a++){singletonId[a]=id.get((1n<<BigInt(a)).toString());for(let b=0;b<CELLS;b++){const m=(1n<<BigInt(a))|(1n<<BigInt(b));pairMask[a*CELLS+b]=m;const q=id.get(m.toString());if(q!==undefined)pairId[a*CELLS+b]=q;}}
const adjResource=Array.from({length:W},()=>new Array(H-1)),adjPairId=Array.from({length:W},()=>new Int16Array(H-1)),adjSingletonId=Array.from({length:W},()=>new Int16Array(H-1));for(let c=0;c<W;c++)for(let lo=0;lo<H-1;lo++){const up=lo+1,a=lo*W+c,b=up*W+c;adjResource[c][lo]=pairMask[a*CELLS+b];adjPairId[c][lo]=pairId[a*CELLS+b];adjSingletonId[c][lo]=singletonId[b];assert(adjPairId[c][lo]>=0);assert(adjSingletonId[c][lo]>=0);}
function canon(xs){xs.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of xs){if(rid===prev)continue;prev=rid;const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}function compile(st,pl){const occ=st.p0|st.p1,opp=pl?st.p0:st.p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(id.get(rem.toString()));}return canon(out);}
let seed=0x91a2b3c4>>>0;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;}function randomState(ply){let p0=0n,p1=0n;const h=new Uint8Array(W);let moves=0;for(;moves<ply;){const cs=[];for(let c=0;c<W;c++)if(h[c]<H){const bit=1n<<BigInt(h[c]*W+c),bits=(moves&1)?p1:p0;if(!won(bits|bit,bit))cs.push(c);}if(!cs.length)break;const c=cs[rnd()%cs.length],bit=1n<<BigInt(h[c]*W+c);if(moves&1)p1|=bit;else p0|=bit;h[c]++;moves++;}return{p0,p1,h,moves};}
function empty(h,cell){const row=Math.trunc(cell/W),col=cell-row*W;return row>=h[col];}function reqBits(reqs){let z=0n;for(const rid of reqs)z|=1n<<BigInt(rid);return z;}function lowBitIndex(z){const lo=Number(z&0xffffffffn);if(lo)return 31-Math.clz32(lo&-lo);let shift=32;z>>=32n;while(z){const w=Number(z&0xffffffffn);if(w)return shift+31-Math.clz32(w&-w);z>>=32n;shift+=32;}return-1;}
function dynamicCover(reqs,h,moves,limit=10000){const n=reqs.length;if(!n)return true;const full=(1n<<BigInt(n))-1n,inst=[],controller=1-(moves&1);function add(cells,solved){if(solved)inst.push({cells,solved});}for(let col=0;col<W;col++)for(let lo=0;lo<H-1;lo++){const up=lo+1,a=lo*W+col,b=up*W+col;if(!empty(h,a)||!empty(h,b))continue;const pair=pairMask[a*CELLS+b];let solved=0n;if((up&1)===controller){for(let i=0;i<n;i++)if((masks[reqs[i]]>>BigInt(b))&1n)solved|=1n<<BigInt(i);}else for(let i=0;i<n;i++)if((masks[reqs[i]]&pair)===pair)solved|=1n<<BigInt(i);add(pair,solved);}const ps=[];for(let c=0;c<W;c++)if(h[c]<H)ps.push(h[c]*W+c);for(let x=0;x<ps.length;x++)for(let y=x+1;y<ps.length;y++){const pair=pairMask[ps[x]*CELLS+ps[y]];let solved=0n;for(let i=0;i<n;i++)if((masks[reqs[i]]&pair)===pair)solved|=1n<<BigInt(i);add(pair,solved);}let union=0n;for(const q of inst)union|=q.solved;if(union!==full)return false;const by=Array.from({length:n},()=>[]);for(let j=0;j<inst.length;j++){let z=inst[j].solved;for(let i=0;z;i++,z>>=1n)if(z&1n)by[i].push(j);}let steps=0;function dfs(cov,used){if(++steps>limit)return false;if(cov===full)return true;const miss=full&~cov;let ri=0;while(((miss>>BigInt(ri))&1n)===0n)ri++;for(const j of by[ri]){const q=inst[j];if(q.cells&used)continue;if((q.solved&~cov)===0n)continue;if(dfs(cov|q.solved,used|q.cells))return true;}return false;}return dfs(0n,0n);}
function makeScratch(){return{resources:new Array(64),blockers:new Int16Array(64),count:0,play:new Int16Array(W),playCount:0,builds:0,candidates:0,zeroAuthority:0,dfsSteps:0};}
function buildGeometry(h,moves,s){let n=0;const controller=1-(moves&1);for(let c=0;c<W;c++)for(let lo=h[c];lo<H-1;lo++){const up=lo+1;s.resources[n]=adjResource[c][lo];s.blockers[n]=(up&1)===controller?adjSingletonId[c][lo]:adjPairId[c][lo];n++;}let pcnt=0;for(let c=0;c<W;c++)if(h[c]<H)s.play[pcnt++]=h[c]*W+c;for(let i=0;i<pcnt;i++)for(let j=i+1;j<pcnt;j++){const a=s.play[i],b=s.play[j],bid=pairId[a*CELLS+b];if(bid<0){s.zeroAuthority++;continue;}s.resources[n]=pairMask[a*CELLS+b];s.blockers[n]=bid;n++;}s.count=n;s.playCount=pcnt;s.builds++;s.candidates+=n;}
function geometryCover(reqs,h,moves,s,limit=10000){if(!reqs.length)return true;buildGeometry(h,moves,s);const active=reqBits(reqs);let union=0n;for(let i=0;i<s.count;i++)union|=upBits[s.blockers[i]]&active;if(union!==active)return false;let steps=0;function dfs(cov,used){if(++steps>limit)return false;if(cov===active)return true;const rid=lowBitIndex(active&~cov),bit=1n<<BigInt(rid);for(let i=0;i<s.count;i++){const closure=upBits[s.blockers[i]];if((closure&bit)===0n)continue;const res=s.resources[i];if(res&used)continue;const solved=closure&active;if((solved&~cov)===0n)continue;if(dfs(cov|solved,used|res))return true;}return false;}const out=dfs(0n,0n);s.dfsSteps+=steps;return out;}
const samples=[];for(const ply of[18,20,22,24,26,28,30,32,34,36])for(let k=0;k<180;k++){const st=randomState(ply),reqs=compile(st,st.moves&1);samples.push({h:st.h.slice(),moves:st.moves,reqs});}
const ds=makeScratch();let covers=0;for(const x of samples){const a=dynamicCover(x.reqs,x.h,x.moves),b=geometryCover(x.reqs,x.h,x.moves,ds);assert.equal(b,a,`mismatch reqs=${x.reqs.join('.')}`);if(a)covers++;}
function runDynamic(){let hits=0;const t=performance.now();for(const x of samples)if(dynamicCover(x.reqs,x.h,x.moves))hits++;return{ms:performance.now()-t,hits};}function runGeometry(){let hits=0,s=makeScratch();const t=performance.now();for(const x of samples)if(geometryCover(x.reqs,x.h,x.moves,s))hits++;return{ms:performance.now()-t,hits,s};}
const dyn=[],geo=[];for(let r=0;r<11;r++){if(r&1){const b=runGeometry(),a=runDynamic();geo.push(b.ms);dyn.push(a.ms);assert.equal(a.hits,b.hits);}else{const a=runDynamic(),b=runGeometry();dyn.push(a.ms);geo.push(b.ms);assert.equal(a.hits,b.hits);}}
function med(v){const a=[...v].sort((x,y)=>x-y);return a[a.length>>1];}const d=med(dyn),g=med(geo);const final=runGeometry();
console.log(JSON.stringify({kind:'connect4-a123-geometry-u1u2-micro',status:'pass',samples:samples.length,covers,differentialMismatches:0,geometry:{avgCandidatesPerBuild:final.s.candidates/final.s.builds,zeroAuthorityPairs:final.s.zeroAuthority,staticPairTableEntries:CELLS*CELLS,staticAdjacentEntries:W*(H-1)},timing:{dynamicMedianMs:d,geometryMedianMs:g,speedupVsDynamic:d/g},semantics:'future owner of row r is player r mod 2 on standard 7x6; singleton/pair blocker IDs and resource masks are precompiled geometry; runtime uses fixed scratch arrays and global WSL-625 closures with no support cache or blocker Map lookup'},null,2));
