import assert from 'node:assert/strict';

const W=7,H=6,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const lines=[];
for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}
const uu=new Set();for(const line of lines){const cs=[];for(let i=0;i<CELLS;i++)if((line>>BigInt(i))&1n)cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);uu.add(m.toString());}}
const masks=[...uu].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const id=new Map(masks.map((m,i)=>[m.toString(),i]));
const reqSize=Uint8Array.from(masks,pc),singletonCell=new Int16Array(625).fill(-1),target=Array.from({length:CELLS},()=>new Int16Array(625).fill(-1)),contains=Array.from({length:CELLS},()=>new Uint8Array(625));
for(let rid=0;rid<625;rid++){if(reqSize[rid]===1)for(let cell=0;cell<CELLS;cell++)if((masks[rid]>>BigInt(cell))&1n){singletonCell[rid]=cell;break;}for(let cell=0;cell<CELLS;cell++)if((masks[rid]>>BigInt(cell))&1n){contains[cell][rid]=1;const n=masks[rid]&~(1n<<BigInt(cell));target[cell][rid]=n===0n?-2:id.get(n.toString());}}
function canon(xs){xs.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of xs){if(rid===prev)continue;prev=rid;const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}
function ownMove(rs,cell){const out=[];for(const rid of rs){const n=target[cell][rid];if(n===-2)return[null,true];out.push(n>=0?n:rid);}return[canon(out),false];}
function oppMove(rs,cell){const out=[];for(const rid of rs)if(!contains[cell][rid])out.push(rid);return out;}
function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}
function parse(seq){let p0=0n,p1=0n;const h=new Uint8Array(W);for(let mv=0;mv<seq.length;mv++){const c=seq.charCodeAt(mv)-49,r=h[c];assert(c>=0&&c<W&&r<H);const bit=1n<<BigInt(r*W+c);if(mv&1){p1|=bit;assert(!won(p1,bit));}else{p0|=bit;assert(!won(p0,bit));}h[c]++;}return{p0,p1,h,moves:seq.length,sequence:seq};}
function compile(root,pl){const occ=root.p0|root.p1,opp=pl?root.p0:root.p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(id.get(rem.toString()));}return canon(out);}
function packH(h){let v=0;for(let c=0;c<W;c++)v|=h[c]<<(3*c);return v>>>0;}function key(h,a,b){return`${packH(h)}|${a.join('.')}/${b.join('.')}`;}
function solveExact(root){const h=root.h.slice(),p0r=compile(root,0),p1r=compile(root,1),tt=new Map();let nodes=0;
 function optimistic(rs,player,moves){if(rs.length===0)return 0;let min=9;for(const rid of rs)if(reqSize[rid]<min)min=reqSize[rid];const d=((moves&1)===player)?2*min-1:2*min,before=moves+d-1;return before>=CELLS?0:Math.trunc((CELLS+1-before)/2);}
 function playable(rs){const out=[];for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W;if(h[col]===row)out.push(cell);}return out;}
 function rec(p0in,p1in,movesIn,alpha,beta){let p0=p0in,p1=p1in,moves=movesIn;const forced=[];const undo=()=>{for(let i=forced.length-1;i>=0;i--)h[forced[i]]--;};while(true){const pl=moves&1,mine=pl?p1:p0,other=pl?p0:p1,own=playable(mine);if(own.length){const v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);undo();return v;}const opp=[...new Set(playable(other))];if(opp.length>=2){const op=1-pl,v=op?-Math.trunc((CELLS-moves)/2):Math.trunc((CELLS-moves)/2);undo();return v;}if(opp.length!==1)break;const cell=opp[0],row=Math.trunc(cell/W),col=cell-row*W,[nm,win]=ownMove(mine,cell);assert(!win);const no=oppMove(other,cell);h[col]++;forced.push(col);moves++;if(pl){p1=nm;p0=no;}else{p0=nm;p1=no;}}
  nodes++;const a0=alpha,b0=beta,k=key(h,p0,p1);let e=tt.get(k);if(e){if(e.lo===e.up){undo();return e.lo;}if(e.lo>=beta){undo();return e.lo;}if(e.up<=alpha){undo();return e.up;}if(alpha<e.lo)alpha=e.lo;if(beta>e.up)beta=e.up;}if((!p0.length&&!p1.length)||moves===CELLS){tt.set(k,{lo:0,up:0});undo();return 0;}const lo=-optimistic(p1,1,moves),hi=optimistic(p0,0,moves);if(alpha<lo)alpha=lo;if(beta>hi)beta=hi;if(alpha>=beta){undo();return alpha;}const pl=moves&1;let best=pl?99:-99;for(const col of ORDER){const row=h[col];if(row===H)continue;const cell=row*W+col,mine=pl?p1:p0,other=pl?p0:p1,[nm,win]=ownMove(mine,cell);h[col]++;let v;if(win)v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);else{const no=oppMove(other,cell);v=pl?rec(no,nm,moves+1,alpha,beta):rec(nm,no,moves+1,alpha,beta);}h[col]--;if(!pl){if(v>best)best=v;if(best>alpha)alpha=best;}else{if(v<best)best=v;if(best<beta)beta=best;}if(alpha>=beta)break;}e=tt.get(k)??{lo:-99,up:99};if(best<=a0)e.up=Math.min(e.up,best);else if(best>=b0)e.lo=Math.max(e.lo,best);else e={lo:best,up:best};tt.set(k,e);undo();return best;}
 const score=rec(p0r,p1r,root.moves,-99,99);return{score:Object.is(score,-0)?0:score,nodes,p0r,p1r};}
function empty(h,cell){const row=Math.trunc(cell/W),col=cell-row*W;return row>=h[col];}
function eventOwner(row,moves){const delta=(W-1)*H-moves+row+1,pl=moves&1;return(delta&1)?pl:1-pl;}
function add(instances,type,cells,solved){if(solved!==0n)instances.push({type,cells,solved});}
function a123Role(reqs,h,moves){const n=reqs.length,targetBits=n?(1n<<BigInt(n))-1n:0n,instances=[],controller=1-(moves&1);let pairChecks=0,legacyMismatch=0;
 for(let col=0;col<W;col++)for(let lower=0;lower<H-1;lower++){const upper=lower+1,a=lower*W+col,b=upper*W+col;if(!empty(h,a)||!empty(h,b))continue;pairChecks++;const owner=eventOwner(upper,moves),isClaim=owner===controller;if((moves&1)===0){const legacyClaim=((upper+1)&1)===0;if(isClaim!==legacyClaim)legacyMismatch++;}let solved=0n;if(isClaim){for(let i=0;i<n;i++)if((masks[reqs[i]]>>BigInt(b))&1n)solved|=1n<<BigInt(i);add(instances,'CL',1n<<BigInt(a)|1n<<BigInt(b),solved);}else{const pair=1n<<BigInt(a)|1n<<BigInt(b);for(let i=0;i<n;i++)if((masks[reqs[i]]&pair)===pair)solved|=1n<<BigInt(i);add(instances,'VE',pair,solved);}}
 const playable=[];for(let col=0;col<W;col++)if(h[col]<H)playable.push(h[col]*W+col);for(let x=0;x<playable.length;x++)for(let y=x+1;y<playable.length;y++){const a=playable[x],b=playable[y],pair=1n<<BigInt(a)|1n<<BigInt(b);let solved=0n;for(let i=0;i<n;i++)if((masks[reqs[i]]&pair)===pair)solved|=1n<<BigInt(i);add(instances,'BI',pair,solved);}
 let union=0n;for(const q of instances)union|=q.solved;return{instances,union,target:targetBits,controller,pairChecks,legacyMismatch};}
function popBig(v){let n=0;while(v){v&=v-1n;n++;}return n;}
function compatibleCover(data,limit=200000){const{instances,target}=data;if(target===0n)return{found:true,steps:0,size:0};const count=popBig(target),byReq=Array.from({length:count},()=>[]);for(let j=0;j<instances.length;j++){let s=instances[j].solved;for(let i=0;s;i++,s>>=1n)if(s&1n)byReq[i].push(j);}for(const a of byReq)a.sort((x,y)=>popBig(instances[y].solved)-popBig(instances[x].solved));let steps=0,size=null;function dfs(covered,used,depth){if(++steps>limit)return false;if(covered===target){size=depth;return true;}const missing=target&~covered;let ri=0;while(((missing>>BigInt(ri))&1n)===0n)ri++;for(const j of byReq[ri]){const q=instances[j];if(q.cells&used)continue;if((q.solved&~covered)===0n)continue;if(dfs(covered|q.solved,used|q.cells,depth+1))return true;}return false;}const found=dfs(0n,0n,0);return{found,steps,capped:steps>limit,size};}
let seed=0x1234abcd>>>0;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;}
function randomRoot(targetPly){let p0=0n,p1=0n;const h=new Uint8Array(W),seq=[];for(let mv=0;mv<targetPly;mv++){const cs=[];for(let c=0;c<W;c++)if(h[c]<H){const bit=1n<<BigInt(h[c]*W+c),bits=(mv&1)?p1:p0;if(!won(bits|bit,bit))cs.push(c);}if(!cs.length)return null;const c=cs[rnd()%cs.length],bit=1n<<BigInt(h[c]*W+c);if(mv&1)p1|=bit;else p0|=bit;h[c]++;seq.push(String(c+1));}return parse(seq.join(''));}

const stats={roots:0,evenRoots:0,oddRoots:0,coverFound:0,evenCovers:0,oddCovers:0,falseClaims:0,capped:0,pairChecks:0,legacyMismatch:0,solveNodes:0,byPly:{}};const examples=[];
for(const ply of [21,22,23,24,25,26,27,28,29,30,31,32]){const ps=stats.byPly[ply]={roots:0,covers:0,falseClaims:0};let got=0,attempt=0;while(got<8&&attempt++<800){const root=randomRoot(ply);if(!root)continue;const exact=solveExact(root);if(exact.nodes<30||exact.nodes>20000)continue;got++;stats.roots++;ps.roots++;stats.solveNodes+=exact.nodes;if(ply&1)stats.oddRoots++;else stats.evenRoots++;const pl=ply&1,reqs=pl?exact.p1r:exact.p0r,data=a123Role(reqs,root.h,root.moves);stats.pairChecks+=data.pairChecks;stats.legacyMismatch+=data.legacyMismatch;const cov=compatibleCover(data);if(cov.capped)stats.capped++;if(!cov.found)continue;stats.coverFound++;ps.covers++;if(pl)stats.oddCovers++;else stats.evenCovers++;const falseClaim=pl?exact.score<0:exact.score>0;if(falseClaim){stats.falseClaims++;ps.falseClaims++;examples.push({kind:'false',seq:root.sequence,ply,pl,score:exact.score,nodes:exact.nodes,reqs:reqs.length,instances:data.instances.length,coverSize:cov.size});}else if(examples.length<20)examples.push({kind:'hold',seq:root.sequence,ply,pl,score:exact.score,nodes:exact.nodes,reqs:reqs.length,instances:data.instances.length,coverSize:cov.size});}}
assert.equal(stats.legacyMismatch,0,'U1 classification must reproduce legacy even-ply CL/VE split');assert.equal(stats.falseClaims,0,'role-generalized A1-A3 produced false no-win claim');
console.log(JSON.stringify({kind:'connect4-allis-a123-u1-role',status:'pass',semantics:'controller = player not to move; adjacent empty pair is CL iff U1 event rank assigns upper cell to controller, otherwise VE; BI unchanged; compatible cover uses disjoint rule resources',stats,examples},null,2));
