import assert from 'node:assert/strict';

const W=7,H=6,CELLS=42,TYPES=['A1','A2','A3','A4','A5','A6','A7','A8','A9'];
const lines=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}
const uu=new Set();for(const l of lines){const cs=[];for(let i=0;i<CELLS;i++)if((l>>BigInt(i))&1n)cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);uu.add(m.toString());}}
const masks=[...uu].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const id=new Map(masks.map((m,i)=>[m.toString(),i]));
function canon(ids){ids.sort((a,b)=>a-b);const out=[];outer:for(const rid of ids){const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}
function compile(p0,p1,pl){const occ=p0|p1,opp=pl?p0:p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(id.get(rem.toString()));}return canon(out);}
function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}
let seed=0x71f0cafe>>>0;function rnd(){seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed;}
function randomRoot(ply){let p0=0n,p1=0n;const h=new Uint8Array(W);for(let mv=0;mv<ply;mv++){const cs=[];for(let c=0;c<W;c++)if(h[c]<H){const bit=1n<<BigInt(h[c]*W+c),b=(mv&1)?p1:p0;if(!won(b|bit,bit))cs.push(c);}if(!cs.length)return null;const c=cs[rnd()%cs.length],bit=1n<<BigInt(h[c]*W+c);if(mv&1)p1|=bit;else p0|=bit;h[c]++;}return{p0,p1,h,ply};}
function empty(h,cell){const row=Math.trunc(cell/W),col=cell-row*W;return row>=h[col];}function playable(h,cell){const row=Math.trunc(cell/W),col=cell-row*W;return h[col]===row;}
function directContains(reqs,bm){let z=0n;for(let i=0;i<reqs.length;i++)if((masks[reqs[i]]&bm)===bm)z|=1n<<BigInt(i);return z;}
function componentBlocker(q,s){const srow=Math.trunc(s/W);return (((srow+1)&1)===0)?(1n<<BigInt(s)):((1n<<BigInt(q))|(1n<<BigInt(s)));}
function liveOwnGroups(p0,p1,pl){const opp=pl?p0:p1,occ=p0|p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push({line:l,rem});}return out;}
function enumerateTailBlockers(cols,starts){const out=[];function rec(i,m){if(i===cols.length){out.push(m);return;}const c=cols[i],start=starts[i];for(let r=start+1;r<H;r++)rec(i+1,m|(1n<<BigInt(r*W+c)));}rec(0,0n);return out;}
function add(cov,count,type,bm,reqs){count[type]++;cov[type]|=directContains(reqs,bm);}
function collect(root){const reqs=compile(root.p0,root.p1,0),h=root.h,cov=Object.fromEntries(TYPES.map(t=>[t,0n])),count=Object.fromEntries(TYPES.map(t=>[t,0]));
 for(let c=0;c<W;c++)for(let lo=0;lo<H-1;lo++){const u=lo+1,a=lo*W+c,b=u*W+c;if(!empty(h,a)||!empty(h,b))continue;if(((u+1)&1)===0)add(cov,count,'A1',1n<<BigInt(b),reqs);else add(cov,count,'A3',(1n<<BigInt(a))|(1n<<BigInt(b)),reqs);}
 const play=[];for(let c=0;c<W;c++)if(h[c]<H)play.push(h[c]*W+c);for(let i=0;i<play.length;i++)for(let j=i+1;j<play.length;j++)add(cov,count,'A2',(1n<<BigInt(play[i]))|(1n<<BigInt(play[j])),reqs);
 for(let c1=0;c1<W;c1++)for(let c2=c1+1;c2<W;c2++)for(let l1=0;l1<H-1;l1++)for(let l2=0;l2<H-1;l2++){const u1=l1+1,u2=l2+1;if(((u1+1)&1)!==1||((u2+1)&1)!==1)continue;const a=l1*W+c1,b=u1*W+c1,c=l2*W+c2,d=u2*W+c2;if(!empty(h,a)||!empty(h,b)||!empty(h,c)||!empty(h,d))continue;for(const bm of[(1n<<BigInt(a))|(1n<<BigInt(b)),(1n<<BigInt(c))|(1n<<BigInt(d)),(1n<<BigInt(b))|(1n<<BigInt(d))])add(cov,count,'A5',bm,reqs);}
 for(let c1=0;c1<W;c1++)for(let c2=c1+1;c2<W;c2++)for(let l1=0;l1<H-2;l1++)for(let l2=0;l2<H-2;l2++){const m1=l1+1,u1=l1+2,m2=l2+1,u2=l2+2;if(((u1+1)&1)!==0||((u2+1)&1)!==0)continue;const a=l1*W+c1,b=m1*W+c1,c=u1*W+c1,d=l2*W+c2,e=m2*W+c2,f=u2*W+c2;if(![a,b,c,d,e,f].every(x=>empty(h,x)))continue;const bs=[(1n<<BigInt(b))|(1n<<BigInt(c)),(1n<<BigInt(e))|(1n<<BigInt(f)),(1n<<BigInt(c))|(1n<<BigInt(f)),(1n<<BigInt(b))|(1n<<BigInt(e))];if(playable(h,a))bs.push((1n<<BigInt(a))|(1n<<BigInt(f)));if(playable(h,d))bs.push((1n<<BigInt(d))|(1n<<BigInt(c)));for(const bm of bs)add(cov,count,'A6',bm,reqs);}
 for(let j=0;j<play.length;j++){const p2=play[j],r2=Math.trunc(p2/W),c2=p2-r2*W;if(r2+1>=H)continue;const q2=(r2+1)*W+c2;if(((r2+2)&1)!==0||!empty(h,q2))continue;for(let i=0;i<play.length;i++)if(i!==j)for(let z=i+1;z<play.length;z++)if(z!==j){const p1=play[i],p3=play[z];add(cov,count,'A7',(1n<<BigInt(p1))|(1n<<BigInt(q2)),reqs);add(cov,count,'A7',(1n<<BigInt(p2))|(1n<<BigInt(p3)),reqs);}}
 for(const g of liveOwnGroups(root.p0,root.p1,1)){const empt=[];for(let cell=0;cell<CELLS;cell++)if((g.rem>>BigInt(cell))&1n)empt.push(cell);if(!empt.length||empt.some(q=>Math.trunc(q/W)===H-1))continue;const succ=empt.map(q=>q+W);let sb=0n;for(const x of succ)sb|=1n<<BigInt(x);add(cov,count,'A8',sb,reqs);for(let i=0;i<empt.length;i++)add(cov,count,'A8',componentBlocker(empt[i],succ[i]),reqs);
  let ae=true;const cols=[],starts=[],cl=[];for(const q of empt){const r=Math.trunc(q/W),c=q-r*W;if(((r+1)&1)!==0||r===0||!empty(h,q-W)){ae=false;break;}cols.push(c);starts.push(r);cl.push(1n<<BigInt(q));}if(ae){const uniq=[],st=[];for(let i=0;i<cols.length;i++){const j=uniq.indexOf(cols[i]);if(j<0){uniq.push(cols[i]);st.push(starts[i]);}else st[j]=Math.min(st[j],starts[i]);}for(const bm of cl)add(cov,count,'A4',bm,reqs);for(const bm of enumerateTailBlockers(uniq,st))add(cov,count,'A4',bm,reqs);}
  for(const q of empt){if(!playable(h,q))continue;const qr=Math.trunc(q/W),qc=q-qr*W;for(const x of play){const xr=Math.trunc(x/W),xc=x-xr*W;if(xc===qc||x===q)continue;let sblock=1n<<BigInt(x);for(const si of succ)sblock|=1n<<BigInt(si);add(cov,count,'A9',sblock,reqs);add(cov,count,'A9',(1n<<BigInt(q))|(1n<<BigInt(x)),reqs);for(let i=0;i<empt.length;i++)add(cov,count,'A9',componentBlocker(empt[i],succ[i]),reqs);}}
 }
 return{reqs,cov,count};}
const totals=Object.fromEntries(TYPES.map(t=>[t,{instances:0,covered:0,marginalAfterA123:0,rootsActive:0,rootsAddsAfterA123:0}]));let roots=0,totalReq=0,baseCovered=0,allCovered=0,baseFull=0,allRawFull=0;const greedyFirst=Object.fromEntries(TYPES.map(t=>[t,0])),greedyRanks=Object.fromEntries(TYPES.map(t=>[t,0]));
for(const ply of[8,12,16,20,24,28,32,34])for(let k=0;k<220;k++){const root=randomRoot(ply);if(!root)continue;const {reqs,cov,count}=collect(root);if(!reqs.length)continue;roots++;totalReq+=reqs.length;for(const t of TYPES){totals[t].instances+=count[t];const n=pc(cov[t]);totals[t].covered+=n;if(count[t])totals[t].rootsActive++;}let base=cov.A1|cov.A2|cov.A3;baseCovered+=pc(base);if(pc(base)===reqs.length)baseFull++;let all=0n;for(const t of TYPES)all|=cov[t];allCovered+=pc(all);if(pc(all)===reqs.length)allRawFull++;for(const t of TYPES.slice(3)){const m=pc(cov[t]&~base);totals[t].marginalAfterA123+=m;if(m)totals[t].rootsAddsAfterA123++;}
 let covered=0n,remaining=[...TYPES];for(let rank=0;rank<TYPES.length;rank++){remaining.sort((a,b)=>pc(cov[b]&~covered)-pc(cov[a]&~covered)||count[a]-count[b]||a.localeCompare(b));const pick=remaining.shift(),gain=pc(cov[pick]&~covered);if(rank===0)greedyFirst[pick]++;greedyRanks[pick]+=rank+1;covered|=cov[pick];if(gain===0&&covered===all)break;}}
for(const t of TYPES){const x=totals[t];x.avgInstancesPerRoot=x.instances/roots;x.avgCoveragePerRoot=x.covered/roots;x.avgMarginalAfterA123=x.marginalAfterA123/roots;x.activeRootRate=x.rootsActive/roots;x.addsAfterA123Rate=x.rootsAddsAfterA123/roots;x.greedyFirstCount=greedyFirst[t];x.avgGreedyRank=greedyRanks[t]/roots;}
console.log(JSON.stringify({kind:'connect4-allis-a1-a9-marginal-coverage',status:'pass',warning:'coverage only; A4-A9 unions are not A10 proof authority until compatibility/controller preconditions are established',roots,totalRequirements:totalReq,a123:{covered:baseCovered,coverage:baseCovered/totalReq,rawFullRoots:baseFull,rawFullRate:baseFull/roots},a1a9Raw:{covered:allCovered,coverage:allCovered/totalReq,rawFullRoots:allRawFull,rawFullRate:allRawFull/roots},families:totals},null,2));