import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';

const W=7,H=6,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const lines=[];
for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pc(v){let n=0;while(v){v&=v-1n;n++;}return n;}
const universe=new Set();for(const line of lines){const cs=[];for(let i=0;i<CELLS;i++)if((line>>BigInt(i))&1n)cs.push(i);for(let s=1;s<16;s++){let m=0n;for(let j=0;j<4;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);universe.add(m.toString());}}
const masks=[...universe].map(BigInt).sort((a,b)=>pc(a)-pc(b)||(a<b?-1:a>b?1:0));assert.equal(masks.length,625);const id=new Map(masks.map((m,i)=>[m.toString(),i]));
const reqSize=Uint8Array.from(masks,pc),singletonCell=new Int16Array(625).fill(-1),reqCols=new Uint8Array(625);const target=Array.from({length:CELLS},()=>new Int16Array(625).fill(-1)),contains=Array.from({length:CELLS},()=>new Uint8Array(625));
for(let rid=0;rid<625;rid++){let cols=0;for(let cell=0;cell<CELLS;cell++)if((masks[rid]>>BigInt(cell))&1n){const col=cell%W;cols|=1<<col;if(reqSize[rid]===1)singletonCell[rid]=cell;contains[cell][rid]=1;const n=masks[rid]&~(1n<<BigInt(cell));target[cell][rid]=n===0n?-2:id.get(n.toString());}reqCols[rid]=cols;}
function canon(xs){xs.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of xs){if(rid===prev)continue;prev=rid;const m=masks[rid];for(const p of out)if((masks[p]&~m)===0n)continue outer;out.push(rid);}return out;}
function ownMove(rs,cell){const out=[];for(const rid of rs){const n=target[cell][rid];if(n===-2)return [null,true];out.push(n>=0?n:rid);}return [canon(out),false];}
function oppMove(rs,cell){const out=[];for(const rid of rs)if(!contains[cell][rid])out.push(rid);return out;}
function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}
function parse(seq){let p0=0n,p1=0n;const heights=new Uint8Array(W);for(let mv=0;mv<seq.length;mv++){const c=seq.charCodeAt(mv)-49,r=heights[c];assert(c>=0&&c<W&&r<H);const bit=1n<<BigInt(r*W+c);if(mv&1){p1|=bit;assert(!won(p1,bit));}else{p0|=bit;assert(!won(p0,bit));}heights[c]++;}return{p0,p1,heights,moves:seq.length,seq};}
function compile(root,pl){const occ=root.p0|root.p1,opp=pl?root.p0:root.p1,out=[];for(const l of lines){if(l&opp)continue;const rem=l&~occ;if(rem)out.push(id.get(rem.toString()));}return canon(out);}
function packH(h){let v=0;for(let c=0;c<W;c++)v|=h[c]<<(3*c);return v>>>0;}function stateKey(h,a,b){return`${packH(h)}|${a.join('.')}/${b.join('.')}`;}
function density(rs){let s=0;for(const rid of rs)s+=1<<(4-reqSize[rid]);return s;}function parity(rs,h,moves){let cls=0,future=0;for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W,d=row-h[col]+1;if(d<=1)continue;future++;const tp=(((W-1)*H)-moves+row+1)&1;if(tp===1)cls=1;}return{cls,future};}
const columnMasks=[];for(let col=0;col<W;col++){let mask=0n;for(let row=0;row<H;row++)mask|=1n<<BigInt(row*W+col);columnMasks.push(mask);}function swapMask(mask,a,b){if(a===b)return mask;const ma=columnMasks[a],mb=columnMasks[b],aa=mask&ma,bb=mask&mb,rest=mask&~(ma|mb),d=b-a;return d>0?rest|(aa<<BigInt(d))|(bb>>BigInt(d)):rest|(aa>>BigInt(-d))|(bb<<BigInt(-d));}
const swapMap=Array.from({length:W},()=>Array(W).fill(null));for(let a=0;a<W;a++)for(let b=a+1;b<W;b++){const map=new Int16Array(625).fill(-1);for(let rid=0;rid<625;rid++){const x=id.get(swapMask(masks[rid],a,b).toString());if(x!==undefined)map[rid]=x;}swapMap[a][b]=map;swapMap[b][a]=map;}
function hasSorted(v,t){let lo=0,hi=v.length-1;while(lo<=hi){const m=(lo+hi)>>1;if(v[m]===t)return true;if(v[m]<t)lo=m+1;else hi=m-1;}return false;}function invariantUnder(rs,map){for(const rid of rs){const x=map[rid];if(x<0||!hasSorted(rs,x))return false;}return true;}function isAuto(h,p0,p1,a,b,s){s.symmetryChecks++;if(h[a]!==h[b])return false;const map=swapMap[a][b];if(!invariantUnder(p0,map)||!invariantUnder(p1,map))return false;s.symmetryHits++;return true;}
function playableSingletons(rs,h){const out=[];for(const rid of rs){if(reqSize[rid]!==1)continue;const cell=singletonCell[rid],row=Math.trunc(cell/W),col=cell-row*W;if(h[col]===row)out.push(cell);}return out;}
function optimistic(rs,player,moves,s){if(rs.length===0)return 0;const next=(moves&1)===player;let min=9;for(const rid of rs){s.boundScans++;if(reqSize[rid]<min)min=reqSize[rid];}const delta=next?2*min-1:2*min,before=moves+delta-1;if(before>=CELLS)return 0;return Math.trunc((CELLS+1-before)/2);}
function activeColumnMask(p0,p1){let z=0;for(const rid of p0)z|=reqCols[rid];for(const rid of p1)z|=reqCols[rid];return z;}
function children(order,p0,p1,h,moves,dead,s){const pl=moves&1,mine=pl?p1:p0,other=pl?p0:p1,active=dead?activeColumnMask(p0,p1):127,out=[];let keptDead=false;for(let oi=0;oi<ORDER.length;oi++){const col=ORDER[oi],row=h[col];if(row===H)continue;if(dead&&((active>>col)&1)===0){if(keptDead){s.deadMovesSkipped++;continue;}keptDead=true;}const cell=row*W+col,[nm,win]=ownMove(mine,cell),no=win?null:oppMove(other,cell),mat=win?1e9:density(nm)-density(no),pf=win?{cls:1,future:99}:parity(nm,h,moves+1);out.push({col,oi,nm,no,win,mat,pcls:pf.cls,pfuture:pf.future});}if(order==='center')return out;if(order==='parityPrimary')return out.sort((a,b)=>b.pcls-a.pcls||b.pfuture-a.pfuture||b.mat-a.mat||a.oi-b.oi);if(order==='maturityParity')return out.sort((a,b)=>b.mat-a.mat||b.pcls-a.pcls||b.pfuture-a.pfuture||a.oi-b.oi);throw new Error(order);}
function solve(root,{cardinality=true,macro=true,orbits=false,order='center',exhaustion=false,dead=false}={}){const h=root.heights.slice(),p0r=compile(root,0),p1r=compile(root,1),tt=new Map();let nodes=0,ttCuts=0,boundCuts=0,exhCuts=0,forcedTransitions=0;const s={boundScans:0,symmetryChecks:0,symmetryHits:0,movesSkipped:0,deadMovesSkipped:0};
 function rec(p0in,p1in,movesIn,alpha,beta){let p0=p0in,p1=p1in,moves=movesIn;const forcedCols=[];const undo=()=>{for(let i=forcedCols.length-1;i>=0;i--)h[forcedCols[i]]--;};if(macro){while(true){const pl=moves&1,mine=pl?p1:p0,other=pl?p0:p1,own=playableSingletons(mine,h);if(own.length){const v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);undo();return v;}const opp=[...new Set(playableSingletons(other,h))];if(opp.length>=2){const op=1-pl,v=op?-Math.trunc((CELLS-moves)/2):Math.trunc((CELLS-moves)/2);undo();return v;}if(opp.length!==1)break;const cell=opp[0],row=Math.trunc(cell/W),col=cell-row*W,[nm,win]=ownMove(mine,cell);assert(!win);const no=oppMove(other,cell);h[col]++;forcedCols.push(col);forcedTransitions++;moves++;if(pl){p1=nm;p0=no;}else{p0=nm;p1=no;}}}
  nodes++;const a0=alpha,b0=beta,k=stateKey(h,p0,p1);let e=tt.get(k);if(e){if(e.lo===e.up){ttCuts++;undo();return e.lo;}if(e.lo>=beta){ttCuts++;undo();return e.lo;}if(e.up<=alpha){ttCuts++;undo();return e.up;}if(alpha<e.lo)alpha=e.lo;if(beta>e.up)beta=e.up;}
  if((p0.length===0&&p1.length===0)||moves===CELLS){tt.set(k,{lo:0,up:0});undo();return 0;}
  let lo=-99,hi=99;if(exhaustion){if(p1.length===0)lo=0;if(p0.length===0)hi=0;}if(cardinality){lo=Math.max(lo,-optimistic(p1,1,moves,s));hi=Math.min(hi,optimistic(p0,0,moves,s));}
  if(exhaustion||cardinality){if(alpha<lo)alpha=lo;if(beta>hi)beta=hi;if(lo>=b0){boundCuts++;if(exhaustion&&(p1.length===0||p0.length===0))exhCuts++;e=e??{lo:-99,up:99};e.lo=Math.max(e.lo,lo);tt.set(k,e);undo();return lo;}if(hi<=a0){boundCuts++;if(exhaustion&&(p1.length===0||p0.length===0))exhCuts++;e=e??{lo:-99,up:99};e.up=Math.min(e.up,hi);tt.set(k,e);undo();return hi;}if(alpha>=beta){boundCuts++;if(exhaustion&&(p1.length===0||p0.length===0))exhCuts++;undo();return alpha;}}
  const pl=moves&1;let best=pl?99:-99,reps=[];for(const ch of children(order,p0,p1,h,moves,dead,s)){if(orbits){let eq=false;for(const rep of reps)if(isAuto(h,p0,p1,ch.col,rep,s)){eq=true;break;}if(eq){s.movesSkipped++;continue;}reps.push(ch.col);}h[ch.col]++;let v;if(ch.win)v=pl?-Math.trunc((CELLS+1-moves)/2):Math.trunc((CELLS+1-moves)/2);else v=pl?rec(ch.no,ch.nm,moves+1,alpha,beta):rec(ch.nm,ch.no,moves+1,alpha,beta);h[ch.col]--;if(!pl){if(v>best)best=v;if(best>alpha)alpha=best;}else{if(v<best)best=v;if(best<beta)beta=best;}if(alpha>=beta)break;}e=tt.get(k)??{lo:-99,up:99};if(best<=a0)e.up=Math.min(e.up,best);else if(best>=b0)e.lo=Math.max(e.lo,best);else e={lo:best,up:best};assert(e.lo<=e.up);tt.set(k,e);undo();return best;}
 const t=performance.now(),score=rec(p0r,p1r,root.moves,-99,99);return{score:Object.is(score,-0)?0:score,nodes,ms:performance.now()-t,ttSize:tt.size,ttCuts,boundCuts,exhCuts,forcedTransitions,...s};}
const frozen=[['764353221241721325116531',-2],['5563576621726752473477144213',7],['3253472274311154254412135',-9],['24763565123272565531172315',2],['544111352647536626717444135',-8],['3412761563244125763551573',-9],['1174534625627233274533652316',-6],['463141571213634656162165252',7]];
const configs=[];for(const cardinality of[false,true])for(const macro of[false,true])for(const orbits of[false,true])for(const exhaustion of[false,true])for(const dead of[false,true])for(const order of['center','parityPrimary','maturityParity'])configs.push({cardinality,macro,orbits,exhaustion,dead,order,id:`C${+cardinality}M${+macro}A${+orbits}E${+exhaustion}D${+dead}-${order}`});
const REPS=4,WARM=1,records=[],ledger=new Map();for(let rep=0;rep<REPS;rep++){const rotated=configs.slice(rep%configs.length).concat(configs.slice(0,rep%configs.length));for(const cfg of rotated){let nodes=0,ms=0,deadMovesSkipped=0,exhCuts=0;for(const[seq,oracle]of frozen){const r=solve(parse(seq),cfg);assert.equal(r.score,oracle,`${cfg.id} ${seq}`);nodes+=r.nodes;ms+=r.ms;deadMovesSkipped+=r.deadMovesSkipped;exhCuts+=r.exhCuts;}const old=ledger.get(cfg.id);if(old===undefined)ledger.set(cfg.id,nodes);else assert.equal(nodes,old);records.push({rep,id:cfg.id,nodes,ms,deadMovesSkipped,exhCuts});}}
function med(v){const a=[...v].sort((x,y)=>x-y),n=a.length;return n&1?a[n>>1]:(a[(n>>1)-1]+a[n>>1])/2;}function pct(a,b){return 100*(1-a/b);}const summary={};for(const cfg of configs){const rows=records.filter(r=>r.id===cfg.id),timed=rows.filter(r=>r.rep>=WARM);summary[cfg.id]={...cfg,nodes:ledger.get(cfg.id),medianMs:med(timed.map(r=>r.ms)),deadMovesSkipped:rows[0].deadMovesSkipped,exhCuts:rows[0].exhCuts};}
const comparisons=[];function toggle(name,onPred,offMatch){for(const on of configs.filter(onPred)){const off=configs.find(c=>offMatch(c,on));if(!off)continue;const a=summary[on.id],b=summary[off.id];comparisons.push({candidate:name,on:on.id,off:off.id,nodePct:pct(a.nodes,b.nodes),timePct:pct(a.medianMs,b.medianMs)});}}
toggle('EXH',c=>c.exhaustion,(c,o)=>!c.exhaustion&&c.cardinality===o.cardinality&&c.macro===o.macro&&c.orbits===o.orbits&&c.dead===o.dead&&c.order===o.order);toggle('DEAD',c=>c.dead,(c,o)=>!c.dead&&c.cardinality===o.cardinality&&c.macro===o.macro&&c.orbits===o.orbits&&c.exhaustion===o.exhaustion&&c.order===o.order);toggle('CARD',c=>c.cardinality,(c,o)=>!c.cardinality&&c.macro===o.macro&&c.orbits===o.orbits&&c.exhaustion===o.exhaustion&&c.dead===o.dead&&c.order===o.order);toggle('FMAC',c=>c.macro,(c,o)=>!c.macro&&c.cardinality===o.cardinality&&c.orbits===o.orbits&&c.exhaustion===o.exhaustion&&c.dead===o.dead&&c.order===o.order);toggle('AUTO',c=>c.orbits,(c,o)=>!c.orbits&&c.cardinality===o.cardinality&&c.macro===o.macro&&c.exhaustion===o.exhaustion&&c.dead===o.dead&&c.order===o.order);toggle('E2-primary',c=>c.order==='parityPrimary',(c,o)=>c.order==='center'&&c.cardinality===o.cardinality&&c.macro===o.macro&&c.orbits===o.orbits&&c.exhaustion===o.exhaustion&&c.dead===o.dead);toggle('E1+E2',c=>c.order==='maturityParity',(c,o)=>c.order==='center'&&c.cardinality===o.cardinality&&c.macro===o.macro&&c.orbits===o.orbits&&c.exhaustion===o.exhaustion&&c.dead===o.dead);
const candidateSummary={};for(const name of[...new Set(comparisons.map(x=>x.candidate))]){const xs=comparisons.filter(x=>x.candidate===name);candidateSummary[name]={contexts:xs.length,nodePct:{min:Math.min(...xs.map(x=>x.nodePct)),median:med(xs.map(x=>x.nodePct)),max:Math.max(...xs.map(x=>x.nodePct))},timePct:{min:Math.min(...xs.map(x=>x.timePct)),median:med(xs.map(x=>x.timePct)),max:Math.max(...xs.map(x=>x.timePct))},best:xs.reduce((a,b)=>a.nodePct>b.nodePct?a:b),worst:xs.reduce((a,b)=>a.nodePct<b.nodePct?a:b)};}
const best=Object.values(summary).sort((a,b)=>a.nodes-b.nodes).slice(0,20).map(x=>({id:x.id,nodes:x.nodes,medianMs:x.medianMs,deadMovesSkipped:x.deadMovesSkipped,exhCuts:x.exhCuts}));console.log(JSON.stringify({kind:'connect4-minimax-synergy-wave2-semantic',status:'pass',policy:'No single context rejects a candidate. Effects are retained by context and compared against directional synergy hypotheses.',configCount:configs.length,reps:REPS,warmReps:WARM,candidateSummary,best},null,2));