import assert from 'node:assert/strict';
import { performance } from 'node:perf_hooks';

function mixBin(id,salt,bits){let x=(id+Math.imul(salt+1,0x9e3779b9))>>>0;x^=x>>>16;x=Math.imul(x,0x7feb352d);x^=x>>>15;x=Math.imul(x,0x846ca68b);x^=x>>>16;return x&((1<<bits)-1);}
function geom(w,h,k){
  const lines=[];for(let r=0;r<h;r++)for(let c=0;c<w;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+(k-1)*dx,y=r+(k-1)*dy;if(x<0||x>=w||y<0||y>=h)continue;let m=0n;for(let j=0;j<k;j++)m|=1n<<BigInt((r+j*dy)*w+c+j*dx);lines.push(m);}
  const pop=x=>{let n=0;while(x){x&=x-1n;n++;}return n;},us=new Set();for(const line of lines){const cs=[];for(let i=0;i<w*h;i++)if((line>>BigInt(i))&1n)cs.push(i);for(let s=1;s<(1<<k);s++){let m=0n;for(let j=0;j<k;j++)if((s>>j)&1)m|=1n<<BigInt(cs[j]);us.add(m.toString());}}
  const req=[...us].map(BigInt).sort((a,b)=>pop(a)-pop(b)||(a<b?-1:a>b?1:0)),id=new Map(req.map((m,i)=>[m.toString(),i])),size=Uint8Array.from(req,pop);
  const sig=Array.from({length:4},()=>new Uint32Array(req.length)),idxSig=new Uint8Array(req.length);for(let s=0;s<4;s++)for(let rid=0;rid<req.length;rid++)sig[s][rid]=(1<<mixBin(rid,s,5))>>>0;for(let rid=0;rid<req.length;rid++)idxSig[rid]=1<<mixBin(rid,9,3);
  const up=new Array(req.length),upSig=Array.from({length:4},()=>new Uint32Array(req.length)),upIdx=new Uint8Array(req.length);
  for(let b=0;b<req.length;b++){let z=0n,ii=0;const ss=[0,0,0,0],bm=req[b];for(let r=0;r<req.length;r++)if((bm&~req[r])===0n){z|=1n<<BigInt(r);ii|=idxSig[r];for(let s=0;s<4;s++)ss[s]=(ss[s]|sig[s][r])>>>0;}up[b]=z;upIdx[b]=ii;for(let s=0;s<4;s++)upSig[s][b]=ss[s];}
  return{w,h,k,cells:w*h,lines,req,id,size,sig,idxSig,up,upSig,upIdx};
}
function packH(h){let x=0n;for(let c=0;c<h.length;c++)x|=BigInt(h[c])<<BigInt(c*3);return x;}
function run(w,h,k,mode){
  const g=geom(w,h,k),hs=new Uint8Array(w),memo=new Map(),buckets=new Map();
  function canonIds(xs){xs.sort((a,b)=>a-b);const out=[];let prev=-1;outer:for(const rid of xs){if(rid===prev)continue;prev=rid;const m=g.req[rid];for(const p of out)if((g.req[p]&~m)===0n)continue outer;out.push(rid);}return out;}
  const init=canonIds(g.lines.map(m=>g.id.get(m.toString())));
  function recMeta(ids){let bits=0n,upUnion=0n,min=255,idxBits=0,idxUp=0;const bs=[0,0,0,0],us=[0,0,0,0];for(const rid of ids){bits|=1n<<BigInt(rid);upUnion|=g.up[rid];if(g.size[rid]<min)min=g.size[rid];idxBits|=g.idxSig[rid];idxUp|=g.upIdx[rid];for(let s=0;s<4;s++){bs[s]=(bs[s]|g.sig[s][rid])>>>0;us[s]=(us[s]|g.upSig[s][rid])>>>0;}}return{ids,bits,upUnion,minSize:ids.length?min:0,idxBits,idxUp,bitsSig:bs,unionSig:us};}
  function key(a,b){return`${packH(hs).toString(16)}|${a.ids.join('.')}/${b.ids.join('.')}`;}
  function impliesClosure(A,B){stats.fullClosureChecks++;if(A.ids.length===0)return true;if(B.ids.length===0)return false;return(A.bits&~B.upUnion)===0n;}
  function impliesFast(A,B){stats.fastChecks++;if(A.ids.length===0)return true;if(B.ids.length===0)return false;if(A.minSize<B.minSize){stats.fastRejects++;return false;}for(let s=0;s<4;s++)if((A.bitsSig[s]&~B.unionSig[s])!==0){stats.fastRejects++;return false;}return impliesClosure(A,B);}
  const implies=mode==='closure'?impliesClosure:impliesFast;
  function fav(A,B){return implies(B.r0,A.r0)&&implies(A.r1,B.r1);}
  function makeList(){return{items:[],r0:new Map(),r1:new Map(),live:0};}
  function addEntry(list,x){const e={r0:x.r0,r1:x.r1,v:x.v,alive:true};list.items.push(e);for(const [which,sigv] of[['r0',e.r0.idxUp],['r1',e.r1.idxUp]]){const map=list[which];let a=map.get(sigv);if(!a){a=[];map.set(sigv,a);}a.push(e);}list.live++;return e;}
  function eachCandidate(list,which,q,fn){
    if(mode!=='index8'||q===0){for(const e of list.items)if(e.alive){stats.indexCandidateChecks++;if(fn(e))return true;}return false;}
    const map=list[which];for(const[sigv,a]of map){stats.indexGroupChecks++;if((q&~sigv)!==0)continue;for(const e of a)if(e.alive){stats.indexCandidateChecks++;if(fn(e))return true;}}return false;
  }
  function kill(e,list){if(e.alive){e.alive=false;list.live--;stats.retiredItems++;}}
  function bucket(){const kk=packH(hs).toString(16);let z=buckets.get(kk);if(!z){z={wins:makeList(),losses:makeList(),drawLo:makeList(),drawHi:makeList()};buckets.set(kk,z);}return z;}
  function insertMin(list,x){if(eachCandidate(list,'r1',x.r1.idxBits,y=>{stats.maintChecks++;return fav(x,y);} ))return;eachCandidate(list,'r0',x.r0.idxBits,y=>{stats.maintChecks++;if(fav(y,x))kill(y,list);return false;});addEntry(list,x);}
  function insertMax(list,x){if(eachCandidate(list,'r0',x.r0.idxBits,y=>{stats.maintChecks++;return fav(y,x);} ))return;eachCandidate(list,'r1',x.r1.idxBits,y=>{stats.maintChecks++;if(fav(x,y))kill(y,list);return false;});addEntry(list,x);}
  function lookup(r0,r1){if(mode==='none')return null;const A={r0,r1},z=bucket();let lo=-1,hi=1;if(eachCandidate(z.wins,'r1',A.r1.idxBits,y=>{stats.lookupChecks++;return fav(A,y);})){stats.domHits++;return 1;}if(eachCandidate(z.losses,'r0',A.r0.idxBits,y=>{stats.lookupChecks++;return fav(y,A);})){stats.domHits++;return-1;}if(eachCandidate(z.drawLo,'r1',A.r1.idxBits,y=>{stats.lookupChecks++;if(fav(A,y)){lo=0;return true;}return false;})){}if(eachCandidate(z.drawHi,'r0',A.r0.idxBits,y=>{stats.lookupChecks++;if(fav(y,A)){hi=0;return true;}return false;})){}if(lo===0&&hi===0){stats.domHits++;return 0;}return null;}
  function store(r0,r1,v){if(mode==='none')return;const x={r0,r1,v},z=bucket();if(v===1)insertMin(z.wins,x);else if(v===-1)insertMax(z.losses,x);else{insertMin(z.drawLo,x);insertMax(z.drawHi,x);}const n=z.wins.live+z.losses.live+z.drawLo.live+z.drawHi.live;if(n>stats.maxFrontier)stats.maxFrontier=n;}
  const stats={calls:0,expanded:0,exactHits:0,domHits:0,lookupChecks:0,maintChecks:0,fullClosureChecks:0,fastChecks:0,fastRejects:0,indexGroupChecks:0,indexCandidateChecks:0,retiredItems:0,maxFrontier:0};
  function rec(r0,r1,m){stats.calls++;const kk=key(r0,r1);if(memo.has(kk)){stats.exactHits++;return memo.get(kk);}if((r0.ids.length===0&&r1.ids.length===0)||m===g.cells){memo.set(kk,0);store(r0,r1,0);return 0;}const d=lookup(r0,r1);if(d!==null)return d;stats.expanded++;const p=m&1;let best=p?1:-1;for(let c=0;c<w;c++){const r=hs[c];if(r===h)continue;const bit=1n<<BigInt(r*w+c);hs[c]++;const mine=p?r1:r0,opp=p?r0:r1;let win=false,nm=[];for(const rid of mine.ids){const q=g.req[rid],nq=q&~bit;if(nq===0n){win=true;break;}nm.push(nq);}let v;if(win)v=p?-1:1;else{const no=[];for(const rid of opp.ids){const q=g.req[rid];if((q&bit)===0n)no.push(q);}const a=recMeta(canonIds(nm.map(q=>g.id.get(q.toString())))),b=recMeta(canonIds(no.map(q=>g.id.get(q.toString()))));v=p?rec(b,a,m+1):rec(a,b,m+1);}hs[c]--;if(p){if(v<best)best=v;if(best===-1)break;}else{if(v>best)best=v;if(best===1)break;}}memo.set(kk,best);store(r0,r1,best);return best;}
  const r0=recMeta(init),r1=recMeta(init),t=performance.now(),score=rec(r0,r1,0),ms=performance.now()-t;let frontierItems=0,allocatedItems=0;for(const z of buckets.values())for(const n of['wins','losses','drawLo','drawHi']){frontierItems+=z[n].live;allocatedItems+=z[n].items.length;}return{geometry:`${w}x${h} connect${k}`,mode,universe:g.req.length,score,states:memo.size,frontierItems,allocatedItems,ms,...stats};
}

const games=[[4,3,3],[4,4,4],[5,3,4],[4,5,4]],results=[];
for(const cfg of games){const none=run(...cfg,'none'),closure=run(...cfg,'closure'),fast=run(...cfg,'fast'),index8=run(...cfg,'index8');for(const x of[fast,index8]){assert.equal(x.score,closure.score);assert.equal(x.expanded,closure.expanded,`${x.mode} changed proof work ${cfg}`);assert.equal(x.domHits,closure.domHits,`${x.mode} changed dominance hits ${cfg}`);assert.equal(x.frontierItems,closure.frontierItems,`${x.mode} changed frontier ${cfg}`);}results.push({geometry:none.geometry,baseline:{expanded:none.expanded,ms:none.ms},closure:{expanded:closure.expanded,domHits:closure.domHits,ms:closure.ms,lookupChecks:closure.lookupChecks,maintChecks:closure.maintChecks,fullClosureChecks:closure.fullClosureChecks},fast:{ms:fast.ms,indexCandidateChecks:fast.indexCandidateChecks,fullClosureChecks:fast.fullClosureChecks},index8:{ms:index8.ms,indexGroupChecks:index8.indexGroupChecks,indexCandidateChecks:index8.indexCandidateChecks,lookupChecks:index8.lookupChecks,maintChecks:index8.maintChecks,fullClosureChecks:index8.fullClosureChecks,allocatedItems:index8.allocatedItems,retiredItems:index8.retiredItems,speedupVsClosure:closure.ms/index8.ms,speedupVsFast:fast.ms/index8.ms,candidateReductionPct:100*(1-index8.indexCandidateChecks/fast.indexCandidateChecks)},nodeReductionPct:100*(1-closure.expanded/none.expanded)});}
console.log(JSON.stringify({kind:'connect4-impl-rid-index8',status:'pass',semantics:'8-bit conservative up-closure projection indexes each support-local frontier; only signature groups capable of dominance are visited, and every surviving comparison still passes 4-signature filters plus exact RID closure authority',results},null,2));
