import { Worker } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const WIDTH=7,HEIGHT=6,STRIDE=7,CELLS=42,SEQ=process.argv[2]??'663152175',ROOT_MOVE=Number(process.argv[3]??3),REPEATS=Number(process.argv[4]??5);
const CHUNK_SIZE=1<<15, CHUNKS=8, TOTAL_SIZE=CHUNK_SIZE*CHUNKS;
const workerFile=resolve(dirname(fileURLToPath(import.meta.url)),'multicore_worker.mjs');
let bottom=0n;const bot=[],col=[],top=[];for(let c=0;c<7;c++){const sh=BigInt(c*STRIDE);bot[c]=1n<<sh;top[c]=1n<<BigInt(HEIGHT-1+c*STRIDE);col[c]=((1n<<6n)-1n)<<sh;bottom|=bot[c];}const board=bottom*((1n<<6n)-1n);
function wp(p,m){let r=(p<<1n)&(p<<2n)&(p<<3n);let q=(p<<7n)&(p<<14n);r|=q&(p<<21n);r|=q&(p>>7n);q=(p>>7n)&(p>>14n);r|=q&(p<<7n);r|=q&(p>>21n);q=(p<<6n)&(p<<12n);r|=q&(p<<18n);r|=q&(p>>6n);q=(p>>6n)&(p>>12n);r|=q&(p<<6n);r|=q&(p>>18n);q=(p<<8n)&(p<<16n);r|=q&(p<<24n);r|=q&(p>>8n);q=(p>>8n)&(p>>16n);r|=q&(p<<8n);r|=q&(p>>24n);return r&(board^m)}
const poss=m=>(m+bottom)&board,can=(m,c)=>(m&top[c])===0n,win=(p,m,c)=>(wp(p,m)&poss(m)&col[c])!==0n,play=(m,c)=>(m+bot[c])&col[c];
function parse(seq){let p=0n,m=0n,n=0;for(const ch of seq){const c=ch.charCodeAt(0)-49;if(!can(m,c)||win(p,m,c))throw new Error('bad');const mv=play(m,c);p^=m;m|=mv;n++;}return{p,m,n};}
const pair=x=>[Number(x&0xffffffffn)>>>0,Number((x>>32n)&0xffffffffn)>>>0];
function afterMove(s,c){if(!can(s.m,c))throw new Error('bad move');if(win(s.p,s.m,c))return{immediate:true,score:Math.trunc((CELLS+1-s.n)/2)};const mv=play(s.m,c);return{p:s.p^s.m,m:s.m|mv,n:s.n+1,immediate:false};}
const root=parse(SEQ);const heavy=afterMove(root,ROOT_MOVE);if(heavy.immediate)throw new Error('root move immediate');
const tasks=[],imm=[];let id=0;for(let c=0;c<7;c++){if(!can(heavy.m,c))continue;if(win(heavy.p,heavy.m,c)){imm.push({move:c,score:Math.trunc((CELLS+1-heavy.n)/2)});continue;}const g=afterMove(heavy,c);const [cLo,cHi]=pair(g.p),[mLo,mHi]=pair(g.m);tasks.push({id:id++,move:c,cLo,cHi,mLo,mHi,moves:g.n,chunkIndex:c});}
const keyLoSab=new SharedArrayBuffer(TOTAL_SIZE*4),keyHiSab=new SharedArrayBuffer(TOTAL_SIZE*4),valSab=new SharedArrayBuffer(TOTAL_SIZE);const keyLo=new Uint32Array(keyLoSab),keyHi=new Uint32Array(keyHiSab),val=new Uint8Array(valSab);
function wait(w,p){return new Promise((res,rej)=>{const f=m=>{if(p(m)){w.off('message',f);w.off('error',rej);res(m)}};w.on('message',f);w.once('error',rej)});}
async function make(n){const ws=[];for(let i=0;i<n;i++){const w=new Worker(workerFile,{workerData:{keyLoSab,keyHiSab,valSab}});await wait(w,m=>m.type==='ready');ws.push(w);}const [cLo,cHi]=pair(heavy.p),[mLo,mHi]=pair(heavy.m);await Promise.all(ws.map((w,i)=>{const q=wait(w,m=>m.type==='warmed');w.postMessage({type:'warm',chunkIndex:i%7,limit:100000,state:{cLo,cHi,mLo,mHi,moves:heavy.n}});return q;}));return ws;}
async function run(ws){keyLo.fill(0);keyHi.fill(0);val.fill(0);let next=0,done=0;const results=[];const t0=process.hrtime.bigint();await new Promise((resolve,reject)=>{const launch=w=>{if(next<tasks.length)w.postMessage({type:'task',task:tasks[next++]});};for(const w of ws){w.on('message',m=>{if(m.type!=='result')return;results.push(m.result);done++;if(done===tasks.length)resolve();else launch(w);});w.once('error',reject);launch(w);}});const seconds=Number(process.hrtime.bigint()-t0)/1e9,nodes=results.reduce((a,r)=>a+r.nodes,0);const scores=new Array(7).fill(null);for(const x of imm)scores[x.move]=x.score;for(const r of results)scores[r.move]=-r.score;const heavyScore=Math.max(...scores.filter(v=>v!==null));return{seconds,nodes,nps:nodes/seconds,heavyScore,results};}
const median=xs=>{const a=[...xs].sort((a,b)=>a-b);return a[(a.length-1)>>1];};
console.log(JSON.stringify({sequence:SEQ,rootMove:ROOT_MOVE,heavyPly:heavy.n,tasks:tasks.length,immediate:imm.length,repeats:REPEATS}));
for(const n of [1,2,3,4]){const ws=await make(n);const runs=[];for(let i=0;i<REPEATS;i++)runs.push(await run(ws));for(const w of ws)await w.terminate();console.log(JSON.stringify({workers:n,medianSeconds:median(runs.map(x=>x.seconds)),medianNodes:median(runs.map(x=>x.nodes)),medianNps:median(runs.map(x=>x.nps)),scores:[...new Set(runs.map(x=>x.heavyScore))],runs:runs.map(x=>({seconds:x.seconds,nodes:x.nodes,nps:x.nps,score:x.heavyScore}))}));if(n===4){const d=runs[0].results.sort((a,b)=>b.seconds-a.seconds);console.log(JSON.stringify({detail4:d}));}}
