import { Worker } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
const WIDTH=7,HEIGHT=6,STRIDE=7,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const SEQ=process.argv[2]??'663152175';
const WORKERS=Math.max(1,Number(process.argv[3]??4)|0), SPLIT_DEPTH=Math.max(0,Number(process.argv[4]??4)|0), REPEATS=Math.max(1,Number(process.argv[5]??3)|0), LANE_CAP=Math.max(1,Number(process.argv[6]??2)|0);
const LOCAL_POW=15;
const workerFile=resolve(dirname(fileURLToPath(import.meta.url)),'ybwc_sharedtt_worker.mjs');
let bottom=0n;const bottomMasks=[],columnMasks=[],topMasks=[];
for(let c=0;c<WIDTH;c++){const sh=BigInt(c*STRIDE);bottomMasks[c]=1n<<sh;topMasks[c]=1n<<BigInt(HEIGHT-1+c*STRIDE);columnMasks[c]=((1n<<6n)-1n)<<sh;bottom|=bottomMasks[c];}
const board=bottom*((1n<<6n)-1n);
function winningPositions(position,mask){let r=(position<<1n)&(position<<2n)&(position<<3n);let p=(position<<7n)&(position<<14n);r|=p&(position<<21n);r|=p&(position>>7n);p=(position>>7n)&(position>>14n);r|=p&(position<<7n);r|=p&(position>>21n);p=(position<<6n)&(position<<12n);r|=p&(position<<18n);r|=p&(position>>6n);p=(position>>6n)&(position>>12n);r|=p&(position<<6n);r|=p&(position>>18n);p=(position<<8n)&(position<<16n);r|=p&(position<<24n);r|=p&(position>>8n);p=(position>>8n)&(position>>16n);r|=p&(position<<8n);r|=p&(position>>24n);return r&(board^mask);}
const possible=mask=>(mask+bottom)&board,canPlay=(mask,c)=>(mask&topMasks[c])===0n,isWinningMove=(cur,mask,c)=>(winningPositions(cur,mask)&possible(mask)&columnMasks[c])!==0n,playColumn=(mask,c)=>(mask+bottomMasks[c])&columnMasks[c];
function parse(seq){let current=0n,mask=0n,moves=0;for(const ch of seq){const c=ch.charCodeAt(0)-49;if(c<0||c>=7||!canPlay(mask,c)||isWinningMove(current,mask,c))throw Error('bad sequence');const mv=playColumn(mask,c);current^=mask;mask|=mv;moves++;}return{current,mask,moves};}
function pair(x){return[Number(x&0xffffffffn)>>>0,Number((x>>32n)&0xffffffffn)>>>0];}
function popBig(x){let n=0;while(x){x&=x-1n;n++;}return n;}function multiBit(x){return x!==0n&&(x&(x-1n))!==0n;}
const median=xs=>{const a=[...xs].sort((a,b)=>a-b);return a[(a.length-1)>>1];};
class Pool{
  constructor(n,mode){this.n=n;this.mode=mode;this.workers=[];this.id=1;this.waiters=new Map();this.idle=[];this.queue=[];this.resetMetrics();}
  layout(){if(this.mode.startsWith('localPow')){const pow=Number(this.mode.slice(8)),size=1<<pow;return{totalEntries:this.n*size,tablePow:pow,offset:i=>i*size};}if(this.mode==='local32')return{totalEntries:this.n*(1<<LOCAL_POW),tablePow:LOCAL_POW,offset:i=>i*(1<<LOCAL_POW)};if(this.mode.startsWith('sharedPow')){const pow=Number(this.mode.slice(9));return{totalEntries:1<<pow,tablePow:pow,offset:()=>0};}if(this.mode==='shared32')return{totalEntries:1<<LOCAL_POW,tablePow:LOCAL_POW,offset:()=>0};const pow=LOCAL_POW+Math.ceil(Math.log2(this.n));return{totalEntries:1<<pow,tablePow:pow,offset:()=>0};}
  resetMetrics(){this.nodes=0;this.workerSeconds=0;this.ttHits=0;this.crossHits=0;this.writeAttempts=0;this.writeSuccess=0;this.writeBusy=0;this.tasks=0;}
  async init(root){const L=this.layout();this.L=L;this.keyLoSab=new SharedArrayBuffer(L.totalEntries*4);this.keyHiSab=new SharedArrayBuffer(L.totalEntries*4);this.valSab=new SharedArrayBuffer(L.totalEntries);this.ctrlSab=new SharedArrayBuffer(L.totalEntries*4);this.ownerSab=new SharedArrayBuffer(L.totalEntries);
    for(let i=0;i<this.n;i++){const w=new Worker(workerFile,{workerData:{keyLoSab:this.keyLoSab,keyHiSab:this.keyHiSab,valSab:this.valSab,ctrlSab:this.ctrlSab,ownerSab:this.ownerSab,offsetEntries:L.offset(i),tablePow:L.tablePow,workerId:i}});w.on('message',m=>this.onMessage(w,m));await new Promise((res,rej)=>{const f=m=>{if(m.type==='ready'){w.off('message',f);res();}};w.on('message',f);w.once('error',rej)});this.workers.push(w);this.idle.push(w);}
    const [cLo,cHi]=pair(root.current),[mLo,mHi]=pair(root.mask);await Promise.all(this.workers.map(w=>new Promise((res,rej)=>{const f=m=>{if(m.type==='warmed'){w.off('message',f);res();}};w.on('message',f);w.once('error',rej);w.postMessage({type:'warm',cLo,cHi,mLo,mHi,moves:root.moves,alpha:-1,beta:0,limit:30000});})));this.clear();}
  clear(){new Uint32Array(this.keyLoSab).fill(0);new Uint32Array(this.keyHiSab).fill(0);new Uint8Array(this.valSab).fill(0);new Int32Array(this.ctrlSab).fill(0);new Uint8Array(this.ownerSab).fill(0);}
  onMessage(w,m){if(m.type!=='result')return;for(const k of ['nodes','ttHits','crossHits','writeAttempts','writeSuccess','writeBusy'])this[k]+=m[k]??0;this.workerSeconds+=m.seconds;this.tasks++;const x=this.waiters.get(m.id);if(x){this.waiters.delete(m.id);x.resolve(m);}this.idle.push(w);this.pump();}
  pump(){while(this.idle.length&&this.queue.length){const w=this.idle.pop(),m=this.queue.shift();w.postMessage(m);}}
  run(state,alpha,beta){const id=this.id++,[cLo,cHi]=pair(state.current),[mLo,mHi]=pair(state.mask);return new Promise((resolve,reject)=>{this.waiters.set(id,{resolve,reject});this.queue.push({type:'task',id,cLo,cHi,mLo,mHi,moves:state.moves,alpha,beta});this.pump();});}
  async drain(){while(this.waiters.size||this.queue.length||this.idle.length!==this.workers.length)await new Promise(r=>setImmediate(r));}
  async close(){await Promise.all(this.workers.map(w=>w.terminate()));}
}
let shellNodes=0,splitNodes=0,siblingTasks=0;
function prepare(state,alpha,beta){shellNodes++;const{current,mask,moves}=state;let candidates=possible(mask);const opponentWins=winningPositions(current^mask,mask),forced=candidates&opponentWins;if(forced!==0n){if(multiBit(forced))return{terminal:-Math.trunc((CELLS-moves)/2)};candidates=forced;}candidates&=~(opponentWins>>1n);if(candidates===0n)return{terminal:-Math.trunc((CELLS-moves)/2)};if(moves>=CELLS-2)return{terminal:0};const min=-Math.trunc((CELLS-2-moves)/2);if(alpha<min){alpha=min;if(alpha>=beta)return{terminal:alpha};}const max=Math.trunc((CELLS-1-moves)/2);if(beta>max){beta=max;if(alpha>=beta)return{terminal:beta};}const children=[];for(let oi=0;oi<WIDTH;oi++){const c=ORDER[oi],mv=candidates&columnMasks[c];if(mv===0n)continue;const sc=popBig(winningPositions(current|mv,mask)),child={current:current^mask,mask:mask|mv,moves:moves+1,sc};let at=children.length;while(at>0&&children[at-1].sc<sc)at--;children.splice(at,0,child);}return{alpha,beta,children};}
async function pneg(pool,state,alpha,beta,depth){if(depth<=0){const r=await pool.run(state,alpha,beta);return r.score;}const p=prepare(state,alpha,beta);if('terminal'in p)return p.terminal;alpha=p.alpha;beta=p.beta;const children=p.children;if(!children.length)return alpha;splitNodes++;let score=-await pneg(pool,children[0],-beta,-alpha,depth-1);if(score>=beta)return score;if(score>alpha)alpha=score;if(children.length===1)return alpha;siblingTasks+=children.length-1;let next=1,cutoff=null,best=alpha;const laneCount=Math.min(pool.n,LANE_CAP,Math.max(1,pool.idle.length),children.length-1);async function lane(){while(cutoff===null){const i=next++;if(i>=children.length)return;const s=-await pneg(pool,children[i],-beta,-best,depth-1);if(s>=beta){cutoff=s;return;}if(s>best)best=s;}}await Promise.all(Array.from({length:laneCount},()=>lane()));return cutoff===null?best:cutoff;}
async function solve(pool,state){let min=-Math.trunc((CELLS-state.moves)/2),max=Math.trunc((CELLS+1-state.moves)/2);while(min<max){let med=min+Math.trunc((max-min)/2);if(med<=0&&Math.trunc(min/2)<med)med=Math.trunc(min/2);else if(med>=0&&Math.trunc(max/2)>med)med=Math.trunc(max/2);const s=await pneg(pool,state,med,med+1,SPLIT_DEPTH);await pool.drain();if(s<=med)max=s;else min=s;}return min===0?0:min;}
const root=parse(SEQ);console.log(JSON.stringify({type:'config',sequence:SEQ,moves:root.moves,workers:WORKERS,splitDepth:SPLIT_DEPTH,laneCap:LANE_CAP,repeats:REPEATS}));
for(const mode of (process.env.MODES??'local32,sharedPow15,sharedPow16,sharedPow17,sharedPow18').split(',')){const pool=new Pool(WORKERS,mode);await pool.init(root);const runs=[];for(let r=0;r<REPEATS;r++){pool.clear();pool.resetMetrics();shellNodes=0;splitNodes=0;siblingTasks=0;const t0=process.hrtime.bigint();const score=await solve(pool,root);await pool.drain();const sec=Number(process.hrtime.bigint()-t0)/1e9;const totalNodes=pool.nodes+shellNodes;runs.push({score,sec,totalNodes,nps:totalNodes/sec,ttHits:pool.ttHits,crossHits:pool.crossHits,crossPct:pool.ttHits?100*pool.crossHits/pool.ttHits:0,writeAttempts:pool.writeAttempts,writeSuccess:pool.writeSuccess,writeBusy:pool.writeBusy,tasks:pool.tasks,shellNodes,splitNodes,siblingTasks});}
console.log(JSON.stringify({type:'mode',mode,totalEntries:pool.L.totalEntries,tableEntries:1<<pool.L.tablePow,medianSec:median(runs.map(x=>x.sec)),medianNodes:median(runs.map(x=>x.totalNodes)),medianNps:median(runs.map(x=>x.nps)),medianHits:median(runs.map(x=>x.ttHits)),medianCrossHits:median(runs.map(x=>x.crossHits)),scores:[...new Set(runs.map(x=>x.score))],runs}));await pool.close();}
