const WIDTH=7, HEIGHT=6, STRIDE=7, CELLS=42;
const MIN_SCORE=-18, MAX_SCORE=18;
const TT_UPPER_LIMIT=MAX_SCORE-MIN_SCORE+1; //37
const TT_LOWER_OFFSET=MAX_SCORE-2*MIN_SCORE+2; //56
const TT_UPPER_OFFSET=-MIN_SCORE+1; //19
const ORDER=[3,4,2,5,1,6,0];
function pairFromBig(x){return [Number(x & 0xffffffffn)>>>0, Number((x>>32n)&0xffffffffn)>>>0];}
let bottom=0n;const colLo=new Uint32Array(WIDTH), colHi=new Uint32Array(WIDTH),botLo=new Uint32Array(WIDTH), botHi=new Uint32Array(WIDTH),topLo=new Uint32Array(WIDTH), topHi=new Uint32Array(WIDTH);
for(let c=0;c<WIDTH;c++){const sh=BigInt(c*STRIDE),b=1n<<sh,t=1n<<BigInt(HEIGHT-1+c*STRIDE),cm=((1n<<6n)-1n)<<sh;bottom|=b;[botLo[c],botHi[c]]=pairFromBig(b);[topLo[c],topHi[c]]=pairFromBig(t);[colLo[c],colHi[c]]=pairFromBig(cm);}const board=bottom*((1n<<6n)-1n),[BOTTOM_LO,BOTTOM_HI]=pairFromBig(bottom),[BOARD_LO,BOARD_HI]=pairFromBig(board);
const shlLo=(lo,k)=>(lo<<k)>>>0,shlHi=(lo,hi,k)=>((hi<<k)|(lo>>>(32-k)))>>>0,shrLo=(lo,hi,k)=>((lo>>>k)|(hi<<(32-k)))>>>0,shrHi=(hi,k)=>(hi>>>k)>>>0;let WLO=0,WHI=0;
function winning(pLo,pHi,mLo,mHi){let aLo,aHi,bLo,bHi,pairLo,pairHi,rLo,rHi;aLo=shlLo(pLo,1);aHi=shlHi(pLo,pHi,1);bLo=shlLo(pLo,2);bHi=shlHi(pLo,pHi,2);rLo=aLo&bLo&shlLo(pLo,3);rHi=aHi&bHi&shlHi(pLo,pHi,3);aLo=shlLo(pLo,7);aHi=shlHi(pLo,pHi,7);bLo=shlLo(pLo,14);bHi=shlHi(pLo,pHi,14);pairLo=aLo&bLo;pairHi=aHi&bHi;rLo|=pairLo&shlLo(pLo,21);rHi|=pairHi&shlHi(pLo,pHi,21);rLo|=pairLo&shrLo(pLo,pHi,7);rHi|=pairHi&shrHi(pHi,7);aLo=shrLo(pLo,pHi,7);aHi=shrHi(pHi,7);bLo=shrLo(pLo,pHi,14);bHi=shrHi(pHi,14);pairLo=aLo&bLo;pairHi=aHi&bHi;rLo|=pairLo&shlLo(pLo,7);rHi|=pairHi&shlHi(pLo,pHi,7);rLo|=pairLo&shrLo(pLo,pHi,21);rHi|=pairHi&shrHi(pHi,21);aLo=shlLo(pLo,6);aHi=shlHi(pLo,pHi,6);bLo=shlLo(pLo,12);bHi=shlHi(pLo,pHi,12);pairLo=aLo&bLo;pairHi=aHi&bHi;rLo|=pairLo&shlLo(pLo,18);rHi|=pairHi&shlHi(pLo,pHi,18);rLo|=pairLo&shrLo(pLo,pHi,6);rHi|=pairHi&shrHi(pHi,6);aLo=shrLo(pLo,pHi,6);aHi=shrHi(pHi,6);bLo=shrLo(pLo,pHi,12);bHi=shrHi(pHi,12);pairLo=aLo&bLo;pairHi=aHi&bHi;rLo|=pairLo&shlLo(pLo,6);rHi|=pairHi&shlHi(pLo,pHi,6);rLo|=pairLo&shrLo(pLo,pHi,18);rHi|=pairHi&shrHi(pHi,18);aLo=shlLo(pLo,8);aHi=shlHi(pLo,pHi,8);bLo=shlLo(pLo,16);bHi=shlHi(pLo,pHi,16);pairLo=aLo&bLo;pairHi=aHi&bHi;rLo|=pairLo&shlLo(pLo,24);rHi|=pairHi&shlHi(pLo,pHi,24);rLo|=pairLo&shrLo(pLo,pHi,8);rHi|=pairHi&shrHi(pHi,8);aLo=shrLo(pLo,pHi,8);aHi=shrHi(pHi,8);bLo=shrLo(pLo,pHi,16);bHi=shrHi(pHi,16);pairLo=aLo&bLo;pairHi=aHi&bHi;rLo|=pairLo&shlLo(pLo,8);rHi|=pairHi&shlHi(pLo,pHi,8);rLo|=pairLo&shrLo(pLo,pHi,24);rHi|=pairHi&shrHi(pHi,24);WLO=(rLo&(~mLo)&BOARD_LO)>>>0;WHI=(rHi&(~mHi)&BOARD_HI)>>>0;}
function addPair(aLo,aHi,bLo,bHi){const lo=(aLo+bLo)>>>0,carry=lo<aLo?1:0;WLO=lo;WHI=(aHi+bHi+carry)>>>0;}function possible(mLo,mHi){addPair(mLo,mHi,BOTTOM_LO,BOTTOM_HI);WLO=(WLO&BOARD_LO)>>>0;WHI=(WHI&BOARD_HI)>>>0;}function pop32(x){x>>>=0;x=x-((x>>>1)&0x55555555);x=(x&0x33333333)+((x>>>2)&0x33333333);return Math.imul((x+(x>>>4))&0x0f0f0f0f,0x01010101)>>>24;}function popPair(lo,hi){return pop32(lo)+pop32(hi);}function multiBit(lo,hi){lo>>>=0;hi>>>=0;if(hi!==0){if(lo!==0)return true;return(hi&((hi-1)>>>0))!==0;}return lo!==0&&(lo&((lo-1)>>>0))!==0;}
class Solver{constructor(pow=17,shared=true,workerId=0){this.size=1<<pow;this.mask=this.size-1;this.workerId=workerId|0;this.bankOffset=new Uint32Array(CELLS+1);this.bankMask=new Uint32Array(CELLS+1);this.bankMask.fill(this.mask);const B=shared?SharedArrayBuffer:ArrayBuffer;this.keyLo=new Uint32Array(new B(this.size*4));this.keyHi=new Uint32Array(new B(this.size*4));this.val=new Uint8Array(new B(this.size));this.ctrl=new Int32Array(new B(this.size*4));this.owner=new Uint8Array(new B(this.size));this.moveLo=new Uint32Array((CELLS+1)*WIDTH);this.moveHi=new Uint32Array((CELLS+1)*WIDTH);this.moveScore=new Int8Array((CELLS+1)*WIDTH);this.nodes=0;this.limit=Infinity;this.resetMetrics();}
resetMetrics(){this.nodes=0;this.ttHits=0;this.crossHits=0;this.writeAttempts=0;this.writeSuccess=0;this.writeBusy=0;}hash(lo,hi){let x=(lo^Math.imul(hi,0x9e3779b1))>>>0;return Math.imul(x^(x>>>16),0x85ebca6b)>>>0;}configureBanks(banks){this.bankOffset.fill(0);this.bankMask.fill(this.mask);for(const b of banks){const size=1<<b.pow,mask=size-1;for(let m=b.lo;m<=b.hi&&m<=CELLS;m++){this.bankOffset[m]=b.offset>>>0;this.bankMask[m]=mask;}}}
publish(slot,kLo,kHi,value){this.writeAttempts++;const v=Atomics.load(this.ctrl,slot);if((v&1)!==0||Atomics.compareExchange(this.ctrl,slot,v,(v+1)|0)!==v){this.writeBusy++;return;}this.keyLo[slot]=kLo;this.keyHi[slot]=kHi;this.val[slot]=value;this.owner[slot]=(this.workerId+1)&255;Atomics.store(this.ctrl,slot,(v+2)|0);this.writeSuccess++;}
solveBits(cLo,cHi,mLo,mHi,moves){winning(cLo,cHi,mLo,mHi);const winLo=WLO,winHi=WHI;possible(mLo,mHi);if(((winLo&WLO)|(winHi&WHI))!==0)return Math.trunc((CELLS+1-moves)/2);let min=-Math.trunc((CELLS-moves)/2),max=Math.trunc((CELLS+1-moves)/2);while(min<max){let med=min+Math.trunc((max-min)/2);if(med<=0&&Math.trunc(min/2)<med)med=Math.trunc(min/2);else if(med>=0&&Math.trunc(max/2)>med)med=Math.trunc(max/2);const score=this.negamax(cLo,cHi,mLo,mHi,moves,med,med+1);if(score<=med)max=score;else min=score;}return min===0?0:min;}
negamax(cLo,cHi,mLo,mHi,moves,alpha,beta){this.nodes++;possible(mLo,mHi);let candLo=WLO,candHi=WHI;winning((cLo^mLo)>>>0,(cHi^mHi)>>>0,mLo,mHi);const owLo=WLO,owHi=WHI;let forcedLo=(candLo&owLo)>>>0,forcedHi=(candHi&owHi)>>>0;if((forcedLo|forcedHi)!==0){if(multiBit(forcedLo,forcedHi))return-Math.trunc((CELLS-moves)/2);candLo=forcedLo;candHi=forcedHi;}const rsLo=((owLo>>>1)|(owHi<<31))>>>0,rsHi=(owHi>>>1)>>>0;candLo=(candLo&~rsLo)>>>0;candHi=(candHi&~rsHi)>>>0;if((candLo|candHi)===0)return-Math.trunc((CELLS-moves)/2);if(moves>=CELLS-2)return 0;let min=-Math.trunc((CELLS-2-moves)/2);if(alpha<min){alpha=min;if(alpha>=beta)return alpha;}let max=Math.trunc((CELLS-1-moves)/2);if(beta>max){beta=max;if(alpha>=beta)return beta;}addPair(cLo,cHi,mLo,mHi);const kLo=WLO,kHi=WHI,slot=(this.bankOffset[moves]+(this.hash(kLo,kHi)&this.bankMask[moves]))>>>0;if(this.keyLo[slot]===kLo){const v1=Atomics.load(this.ctrl,slot);if((v1&1)===0&&this.keyLo[slot]===kLo&&this.keyHi[slot]===kHi){const cached=this.val[slot],own=this.owner[slot],v2=Atomics.load(this.ctrl,slot);if(v1===v2&&(v2&1)===0&&cached!==0){this.ttHits++;if(own!==0&&own!==(this.workerId+1))this.crossHits++;if(cached>TT_UPPER_LIMIT){min=cached-TT_LOWER_OFFSET;if(alpha<min){alpha=min;if(alpha>=beta)return alpha;}}else{max=cached-TT_UPPER_OFFSET;if(beta>max){beta=max;if(alpha>=beta)return beta;}}}}}const base=moves*WIDTH;let count=0;for(let oi=0;oi<WIDTH;oi++){const col=ORDER[oi],mvLo=(candLo&colLo[col])>>>0,mvHi=(candHi&colHi[col])>>>0;if((mvLo|mvHi)===0)continue;winning((cLo|mvLo)>>>0,(cHi|mvHi)>>>0,mLo,mHi);const sc=popPair(WLO,WHI);let at=count;while(at>0&&this.moveScore[base+at-1]<sc){this.moveScore[base+at]=this.moveScore[base+at-1];this.moveLo[base+at]=this.moveLo[base+at-1];this.moveHi[base+at]=this.moveHi[base+at-1];at--;}this.moveScore[base+at]=sc;this.moveLo[base+at]=mvLo;this.moveHi[base+at]=mvHi;count++;}for(let i=0;i<count;i++){const mvLo=this.moveLo[base+i],mvHi=this.moveHi[base+i],score=-this.negamax((cLo^mLo)>>>0,(cHi^mHi)>>>0,(mLo|mvLo)>>>0,(mHi|mvHi)>>>0,moves+1,-beta,-alpha);if(score>=beta){this.publish(slot,kLo,kHi,score+TT_LOWER_OFFSET);return score;}if(score>alpha)alpha=score;}this.publish(slot,kLo,kHi,alpha+TT_UPPER_OFFSET);return alpha;}}
export {Solver,winning};
