import assert from 'node:assert/strict';import {performance} from 'node:perf_hooks';
const W=7,H=6,CELLS=42,ORDER=[3,4,2,5,1,6,0];
const lines=[];for(let r=0;r<H;r++)for(let c=0;c<W;c++)for(const [dx,dy] of [[1,0],[0,1],[1,1],[1,-1]]){const x=c+3*dx,y=r+3*dy;if(x<0||x>=W||y<0||y>=H)continue;let m=0n;for(let j=0;j<4;j++)m|=1n<<BigInt((r+j*dy)*W+c+j*dx);lines.push(m);}assert.equal(lines.length,69);
function pop(x){let n=0;while(x){x&=x-1n;n++;}return n;}function normalize(rs){const a=[...new Set(rs.map(x=>x.toString()))].map(BigInt).sort((a,b)=>pop(a)-pop(b)||(a<b?-1:a>b?1:0)),out=[];outer:for(const x of a){for(const y of out)if((y&~x)===0n)continue outer;out.push(x);}return out;}
function won(bits,bit){for(const l of lines)if((l&bit)!==0n&&(l&bits)===l)return true;return false;}
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return x>>>0;};}
function rollout(n,rnd){let p0=0n,p1=0n;const h=new Uint8Array(W);let seq='';for(let m=0;m<n;m++){const p=m&1,legal=[];for(let c=0;c<W;c++){if(h[c]===H)continue;const bit=1n<<BigInt(h[c]*W+c),mine=(p?p1:p0)|bit;if(!won(mine,bit))legal.push(c);}if(!legal.length)return null;const c=legal[rnd()%legal.length],bit=1n<<BigInt(h[c]*W+c);if(p)p1|=bit;else p0|=bit;h[c]++;seq+=c+1;}return{p0,p1,h,moves:n,seq};}
function compile(s){const occ=s.p0|s.p1,goals=[];for(let p=0;p<2;p++){const opp=p?s.p0:s.p1,rs=[];for(const l of lines)if((l&opp)===0n){const q=l&~occ;if(q!==0n)rs.push(q);}goals.push(normalize(rs));}return goals;}
function hkey(h){let x=0;for(let c=0;c<W;c++)x|=h[c]<<(c*3);return x>>>0;}function rkey(h,r0,r1){return `${hkey(h).toString(16)}|${r0.map(x=>x.toString(16)).join('.')}/${r1.map(x=>x.toString(16)).join('.')}`;}
function solvePhysical(root,cap=2500000){const memo=new Map(),h=root.h.slice();let calls=0;function rec(p0,p1,m){if(++calls>cap)throw 'CAP';const key=(p0<<42n)|p1;if(memo.has(key))return memo.get(key);if(m===CELLS){memo.set(key,0);return 0;}const pl=m&1;let best=-99;for(const c of ORDER){const r=h[c];if(r===H)continue;const bit=1n<<BigInt(r*W+c);h[c]++;const mine=(pl?p1:p0)|bit;const v=won(mine,bit)?Math.trunc((43-m)/2):-rec(pl?p0:mine,pl?mine:p1,m+1);h[c]--;if(v>best)best=v;}best=best===0?0:best;memo.set(key,best);return best;}const t=performance.now(),score=rec(root.p0,root.p1,root.moves);return{score,states:memo.size,calls,ms:performance.now()-t};}
function solveReq(root,cap=2500000){const memo=new Map(),h=root.h.slice();let calls=0,drawCuts=0;const initial=compile(root);function rec(r0,r1,m){if(++calls>cap)throw 'CAP';const key=rkey(h,r0,r1);if(memo.has(key))return memo.get(key);if(r0.length===0&&r1.length===0){drawCuts++;memo.set(key,0);return 0;}if(m===CELLS){memo.set(key,0);return 0;}const pl=m&1;let best=-99;for(const c of ORDER){const r=h[c];if(r===H)continue;const bit=1n<<BigInt(r*W+c);h[c]++;const mine=pl?r1:r0,opp=pl?r0:r1;let win=false,nMine=[];for(const q of mine){const nq=q&~bit;if(nq===0n){win=true;break;}nMine.push(nq);}let v;if(win)v=Math.trunc((43-m)/2);else{const nOpp=[];for(const q of opp)if((q&bit)===0n)nOpp.push(q);const a=normalize(nMine),b=normalize(nOpp);v=pl?-rec(b,a,m+1):-rec(a,b,m+1);}h[c]--;if(v>best)best=v;}best=best===0?0:best;memo.set(key,best);return best;}const t=performance.now(),score=rec(initial[0],initial[1],root.moves);return{score,states:memo.size,calls,drawCuts,initialReq:[initial[0].length,initial[1].length],ms:performance.now()-t};}
const rnd=rng(0x7a61c4d2),roots=[];for(const ply of [34,34,34,33,33,33,32,32,32,31,31,31]){let s;for(let tries=0;tries<1000&&!s;tries++)s=rollout(ply,rnd);if(s)roots.push(s);}for(const s of roots){let a,b;try{a=solvePhysical(s);}catch{a={cap:true};}try{b=solveReq(s);}catch{b={cap:true};}if(!a.cap&&!b.cap)assert.equal(a.score,b.score,s.seq);console.log(JSON.stringify({seq:s.seq,ply:s.moves,physical:a,winspace:b,reductionPct:!a.cap&&!b.cap?100*(1-b.states/a.states):null}));}
