// Rendering metadata, not solver code. Every record is embedded in NATIVE.isg.
// These are model/implementation leaves, not proposed IsoGraph primitives.
const syntax={
  Program:['module-semantics','body: ordered ModuleItemList; sourceType=module'],
  ImportDeclaration:['imports','source: ModuleSpecifier; specifiers: ordered ImportClause'],
  ImportSpecifier:['imports','imported: ImportName; local: BindingIdentifier'],
  ExportNamedDeclaration:['exports','declaration or ordered specifiers; optional source ModuleSpecifier'],
  ExportAllDeclaration:['exports','source ModuleSpecifier; exported null means star export'],
  ExportSpecifier:['exports','local binding; exported ExportName'],
  Identifier:['identifiers','name is exact IdentifierName; declaration/use role follows enclosing production, not spelling alone'],
  Literal:['primary-expression-literals','raw preserves lexical token; value preserves decoded value; regex/bigint fields select their literal production'],
  VariableDeclaration:['let-and-const-declarations','kind selects var/let/const; declarations preserve ordered binding/initializer pairs'],
  VariableDeclarator:['destructuring-binding-patterns','id is BindingIdentifier or BindingPattern; init null means absent initializer'],
  ObjectPattern:['destructuring-binding-patterns','ordered binding properties and defaults, not an object value'],
  AssignmentPattern:['destructuring-binding-patterns','left binding target; right default expression evaluated only when required'],
  FunctionDeclaration:['function-definitions','id binding; ordered params; body; async/generator flags select corresponding productions'],
  FunctionExpression:['function-definitions','optional local id; ordered params; body; async/generator flags retained'],
  ArrowFunctionExpression:['arrow-function-definitions','params, body, expression flag, async flag; lexical this, not ordinary FunctionExpression'],
  BlockStatement:['block','body is ordered StatementList and lexical scope; not unordered conjunction'],
  ExpressionStatement:['expression-statement','expression evaluated for effects; directive preserved if supplied'],
  IfStatement:['if-statement','test; consequent iff ToBoolean(test); alternate otherwise, null means absent'],
  ConditionalExpression:['conditional-operator','test; evaluate only selected consequent/alternate expression'],
  ForStatement:['for-statement','init once, test before body when present, update after body/continue; break exits'],
  WhileStatement:['while-statement','test before each body; abrupt completion and continue/break preserved'],
  ForInStatement:['for-in-and-for-of-statements','left binding/target; right object; property-key enumeration; body'],
  ForOfStatement:['for-in-and-for-of-statements','left binding/target; right iterable; body; await flag retained; iterator close semantics'],
  ContinueStatement:['continue-statement','label null or exact label; abrupt continue completion'],
  BreakStatement:['break-statement','label null or exact label; abrupt break completion'],
  ReturnStatement:['return-statement','argument nullable; abrupt return completion to current function'],
  ThrowStatement:['throw-statement','argument evaluated then abrupt throw completion'],
  TryStatement:['try-statement','block; handler nullable; finalizer nullable; completion replacement/order retained'],
  CallExpression:['function-calls','callee Reference then ordered arguments; optional flag; receiver preserved for property calls'],
  NewExpression:['new-operator','callee constructor and ordered arguments; new instance and abrupt completion'],
  MemberExpression:['property-accessors','object before property; computed selects bracket expression versus literal property name; optional flag retained'],
  ChainExpression:['optional-chains','expression carries optional-chain short circuit boundary'],
  ParenthesizedExpression:['grouping-operator','expression preserves grouping without introducing binding scope'],
  BinaryExpression:['ecmascript-language-expressions','operator selects numeric/bitwise/relational/equality production; left and right ordered; coercion and exceptions retained'],
  LogicalExpression:['binary-logical-operators','operator &&/||/?? selects short-circuit semantics; right conditional, not eager'],
  UnaryExpression:['unary-operators','operator, prefix, argument; operator selects typeof/!/~/unary +/-/void/delete semantics'],
  UpdateExpression:['update-expressions','operator and prefix distinguish value before/after update; argument is assignment target'],
  AssignmentExpression:['assignment-operators','operator; left reference once; right; conversion/read-modify-write follows chosen operator'],
  ArrayExpression:['array-initializer','ordered elements, holes=null; spread selected by element node kind'],
  ObjectExpression:['object-initializer','ordered properties; evaluation order and duplicate property overwrite retained'],
  Property:['object-initializer','key,value,kind,method,shorthand,computed; enclosing ObjectPattern changes binding interpretation'],
  SpreadElement:['object-initializer','argument; parent production selects object spread or argument/array iterator spread'],
  ClassDeclaration:['class-definitions','id,superClass,body; lexical class binding and inheritance'],
  ClassBody:['class-definitions','ordered method definitions'],
  MethodDefinition:['class-definitions','key,value,kind,computed,static; method receiver and constructor semantics'],
  ThisExpression:['this-keyword','ResolveThisBinding from execution environment'],
  Super:['super-keyword','super binding under method/derived-constructor environment'],
  AwaitExpression:['async-function-definitions','argument; suspend and resume with fulfilled/rejected completion'],
  MetaProperty:['meta-properties','meta/property exact names distinguish import.meta/new.target'],
  TemplateLiteral:['template-literals','ordered quasis interleaved with ordered expressions; raw/cooked distinctions preserved'],
  TemplateElement:['template-literals','value.raw,value.cooked,tail preserved'],
};
export function semanticBridge(counts){
  for(const type of Object.keys(counts))if(!syntax[type])throw new Error(`unmapped syntax kind ${type}`);
  return {
    status:'CANDIDATE_REQUIRES_COLD_ADMISSION',
    claim:'source-faithful executable algorithm structure under declared ECMAScript/Node model; not theorem of solver correctness, timing or optimizer benefit',
    modelAuthority:{category:'stipulated source model / frozen implementation environment',
      language:{repository:'tc39/ecma262',revision:'84b38ad852ff426795fa29cebc06949027336c64',path:'spec.html',sha256:'525626fffc5737ad2eab8898f36e2a29189ada2d31316cc5beffEEa1b4122321'.toLowerCase()},
      runtime:{repository:'nodejs/node',revision:'b4f23d3619c98bed09af93a21192f6080197a8c6',version:'26.7.0',
        interfaces:['doc/api/worker_threads.md','doc/api/perf_hooks.md','doc/api/timers.md','doc/api/globals.md','doc/api/url.md','doc/api/process.md','doc/api/events.md']},
      parser:{name:'acorn',version:'8.15.0',integrity:'sha512-NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg=='},
    },
    nodeBindings:Object.entries(syntax).filter(([type])=>counts[type]).map(([type,[section,fieldRoles]])=>({type,section:'sec-'+section,fieldRoles})),
    environment:['sec-environment-records','sec-execution-contexts','sec-static-semantics-boundnames','sec-functiondeclarationinstantiation','sec-module-semantics'],
    numbers:['sec-ecmascript-language-types-number-type','sec-numeric-types-number-bitwiseNOT','sec-type-conversion','sec-math.imul'],
    memory:['sec-typedarray-objects','sec-typedarray-exotic-objects','sec-atomics-object','sec-memory-model'],
    binding:'Resolve syntax names in owning ECMAScript module/function/block environments. Identifier spelling is not a cross-scope/global semantic identity. Member names are property keys, not lexical variables. Import/export bindings connect modules at represented source paths. No alpha renaming.',
    execution:'Interpret each reconstructed production under referenced ECMAScript static/runtime semantics. Propagate Reference and Completion records; preserve short circuit, ordered operand effects, lexical captures, receivers, abrupt exits, await and finalization. No executable branch is deleted merely because a current profile makes it unreachable.',
    runtimeBoundary:{
      Worker:'Node Worker from worker_threads: module URL plus structured workerData; typed shared views retain underlying SharedArrayBuffer sharing; separate isolates and private state; error/exit events and terminate Promise under pinned Node contract.',
      timers:'Node setTimeout/setInterval/clearTimeout/clearInterval. Delay is requested scheduling threshold, not an exact wall-time guarantee; event ordering constrained by Node, not by source listing across agents.',
      Atomics:'All represented operations retain ECMAScript shared-memory/Atomics semantics; no data-race-freedom or unique-work theorem inferred from syntax.',
      performance:'performance.now is external elapsed-time observation; no static cycles or latency assigned.',
      AbortSignal:'Externally supplied cancellation/event object under Node AbortSignal contract. Access and event effects remain calls in native tree.',
      process:'process.execArgv is external launch configuration; source filtering remains represented. Launch flags and scheduling are not guessed.',
    },
    unknownFamily:{carrier:'environment traces consistent with pinned Node and ECMAScript agent/shared-memory contracts',
      parameters:['worker scheduling','event delivery timing','failure occurrence and diagnostic text','clock readings','JIT lowering','hardware resource costs'],
      exclusions:['no fabricated deterministic scheduling','no invented probability measure','no timing bound stronger than the runtime guarantees'],
      downstream:'Any candidate depending on cost, overlap, fairness, failure ordering or unqualified memory-policy assumptions remains open until corresponding evidence is supplied.'},
    normalization:{removed:['comments','source offsets'],preserved:['all AST fields otherwise','raw literal spelling','parentheses','binder/use spellings','operator order','statement order','module boundaries'],
      claimBoundary:'algorithm/control/data effects; excludes byte-identical source introspection and stack-trace formatting; neither is used as performance-discovery evidence'},
  };
}
