import assert from 'node:assert/strict';
function geom(w,h,k){const lines=[];for(let r=0;r<h;r++)for(let c=0;c<w;c++)for(const[dx,dy]of[[1,0],[0,1],[1,1],[1,-1]]){const x=c+(k-1)*dx,y=r+(k-1)*dy;if(x<0||x>=w||y<0||y>=h)continue;let m=0n;for(let j=0;j<k;j++)m|=1n<<BigInt((r+j*dy)*w+c+j*dx);lines.push(m);}return{w,h,k,cells:w*h,lines};}
function pop(x){let n=0;while(x){x&=x-1n;n++;}return n;}function norm(rs){const a=[...new Set(rs.map(String))].map(BigInt).sort((x,y)=>pop(x)-pop(y)||(x<y?-1:x>y?1:0)),o=[];outer:for(const x of a){for(const y of o)if((y&~x)===0n)continue outer;o.push(x);}return o;}function packH(h){let x=0n;for(let c=0;c<h.length;c++)x|=BigInt(h[c])<<BigInt(c*3);return x;}function key(h,a,b){return`${packH(h).toString(16)}|${a.map(x=>x.toString(16)).join('.')}/${b.map(x=>x.toString(16)).join('.')}`;}function implies(A,B){if(A.length===0)return true;if(B.length===0)return false;for(const a of A){let ok=false;for(const b of B)if((b&~a)===0n){ok=true;break;}if(!ok)return false;}return true;}function fav(A,B){return implies(B.r0,A.r0)&&implies(A.r1,B.r1);} // A>=B P0
function insertMin(list,x,stats){for(const y of list){stats.maintChecks++;if(fav(x,y))return;}for(let i=list.length-1;i>=0;i--){stats.maintChecks++;if(fav(list[i],x))list.splice(i,1);}list.push(x);}
function insertMax(list,x,stats){for(const y of list){stats.maintChecks++;if(fav(y,x))return;}for(let i=list.length-1;i>=0;i--){stats.maintChecks++;if(fav(x,list[i]))list.splice(i,1);}list.push(x);}
function run(w,h,k,mode){const g=geom(w,h,k),hs=new Uint8Array(w),memo=new Map(),buckets=new Map(),init=norm(g.lines);let calls=0,expanded=0,exactHits=0,domHits=0;const stats={lookupChecks:0,maintChecks:0,maxFrontier:0};function bucket(){const bk=packH(hs).toString(16);let z=buckets.get(bk);if(!z){z={wins:[],losses:[],drawLo:[],drawHi:[]};buckets.set(bk,z);}return z;}
function lookup(r0,r1){if(mode==='none')return null;const A={r0,r1},z=bucket();let lo=-1,hi=1;if(mode==='scan'){for(const y of [...z.wins,...z.losses,...z.drawLo]){stats.lookupChecks++;if(fav(A,y)){const v=y.v;lo=Math.max(lo,v);}if(fav(y,A)){const v=y.v;hi=Math.min(hi,v);}if(lo===1||hi===-1||lo===hi)return lo===1?1:hi===-1?-1:lo;}return null;}
 for(const y of z.wins){stats.lookupChecks++;if(fav(A,y))return 1;}for(const y of z.losses){stats.lookupChecks++;if(fav(y,A))return -1;}for(const y of z.drawLo){stats.lookupChecks++;if(fav(A,y)){lo=0;break;}}for(const y of z.drawHi){stats.lookupChecks++;if(fav(y,A)){hi=0;break;}}if(lo===0&&hi===0)return 0;return null;}
function store(r0,r1,v){if(mode==='none')return;const x={r0:r0.slice(),r1:r1.slice(),v},z=bucket();if(mode==='scan'){if(v===1)z.wins.push(x);else if(v===-1)z.losses.push(x);else z.drawLo.push(x);return;}
 if(v===1)insertMin(z.wins,x,stats);else if(v===-1)insertMax(z.losses,x,stats);else{insertMin(z.drawLo,x,stats);insertMax(z.drawHi,x,stats);}stats.maxFrontier=Math.max(stats.maxFrontier,z.wins.length+z.losses.length+z.drawLo.length+z.drawHi.length);}
function rec(r0,r1,m){calls++;const kk=key(hs,r0,r1);if(memo.has(kk)){exactHits++;return memo.get(kk);}if(r0.length===0&&r1.length===0){memo.set(kk,0);store(r0,r1,0);return 0;}if(m===g.cells){memo.set(kk,0);store(r0,r1,0);return 0;}const d=lookup(r0,r1);if(d!==null){domHits++;return d;}expanded++;const p=m&1;let best=p?1:-1;for(let c=0;c<w;c++){const r=hs[c];if(r===h)continue;const bit=1n<<BigInt(r*w+c);hs[c]++;const mine=p?r1:r0,opp=p?r0:r1;let win=false,nm=[];for(const q of mine){const nq=q&~bit;if(nq===0n){win=true;break;}nm.push(nq);}let v;if(win)v=p?-1:1;else{const no=[];for(const q of opp)if((q&bit)===0n)no.push(q);const a=norm(nm),b=norm(no);v=p?rec(b,a,m+1):rec(a,b,m+1);}hs[c]--;if(p){if(v<best)best=v;if(best===-1)break;}else{if(v>best)best=v;if(best===1)break;}}
memo.set(kk,best);store(r0,r1,best);return best;}
const t0=performance.now(),score=rec(init,init,0),ms=performance.now()-t0;let frontierItems=0;for(const z of buckets.values())frontierItems+=z.wins.length+z.losses.length+z.drawLo.length+z.drawHi.length;return{geometry:`${w}x${h} connect${k}`,mode,score,states:memo.size,calls,expanded,exactHits,domHits,lookupChecks:stats.lookupChecks,maintChecks:stats.maintChecks,frontierItems,maxFrontier:stats.maxFrontier,ms};}
for(const c of[[4,3,3],[4,4,4],[5,3,4],[4,5,4]]){const a=run(...c,'none'),b=run(...c,'frontier');assert.equal(a.score,b.score);console.log(JSON.stringify({baseline:a,frontier:b,expandedReductionPct:100*(1-b.expanded/a.expanded),callReductionPct:100*(1-b.calls/a.calls)}));}
